### ISSUE TITLE
Instructions 

### ISSUE THREAD

**Issue by Guilty-King** [xmrig/xmrig-proxy#1]
Can you provide dependencies needed ?
I tired to run on ubuntu 16.04 lts but after deploying 
It shows status : errored in pm2 show xmrig-proxy
Also if possible the supported pools
 Good luck for your work
[35.185.227.100_20170501172813.txt](https://github.com/xmrig/xmrig-proxy/files/967799/35.185.227.100_20170501172813.txt)

**Comment by xmrig** [comment]
To install dependencies you need to run `npm install` in app folder. If it's not help please show `/home/ubuntu/xmrig-proxy/log/xmrig-proxy.err`.

Proxy should work with any CryptoNight pool.

Sorry for delayed answer i did't receive notification for this issue.

**Comment by systemroot** [comment]
> If it's not help please show /home/ubuntu/xmrig-proxy/log/xmrig-proxy.err.

lol.

anyway.
```bash
root@node1:~/xmrig-proxy# ls
app  app.sh  config  index.js  log  node_modules  package.json  README.md
root@node1:~/xmrig-proxy# ./app.sh start
2.5.0
root@node1:~/xmrig-proxy# ./app.sh restart
Use --update-env to update environment variables
[PM2][ERROR] Process xmrig-proxy not found
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
root@node1:~/xmrig-proxy# ls log/
root@node1:~/xmrig-proxy# 
```

**Comment by xmrig** [comment]
Proxy rewritten on C++, there no more node.js

**Comment by systemroot** [comment]
@xmrig does it support only windows now?!

if no, did u tried to compile on linux? if yes what's your libuv library version? and on what distro did u tried..
i tried on ubuntu 14.04 but i'm having some problems caused by libuv library
![](http://i.imgur.com/e5o0u1R.png)

**Comment by xmrig** [comment]
Yeah right
