### ISSUE TITLE
Monitoring!!!

### ISSUE THREAD

**Issue by javietanh** [xmrig/xmrig-proxy#10]
Dear,

Is it possible to add the monitor tools? i don't know how to see each miner hash rate on the proxy. 

Cheers

**Comment by xmrig** [comment]
It already planned to 2.4 release.
Thank you.

**Comment by javietanh** [comment]
Is it possible to set fix diff with proxy? 
Ex: port 3333 -> fix diff 10000
     port 5555 -> fix diff 5000

Cheers

**Comment by Guilty-King** [comment]
@javietanh you can set --custom-diff=10000 -b 0.0.0.0:3333 , repeat the same for 5555 , so you should be running 2 proxy at different ports on same machine , as of now you can set different custom-diff for different ports as per me , I could be mistaken

**Comment by sergneo** [comment]
> Is it possible to set fix diff with proxy?
> Ex: port 3333 -> fix diff 10000
> port 5555 -> fix diff 5000
Really, really need a function, is it possible to do now?
