### ISSUE TITLE
local ip

### ISSUE THREAD

**Issue by yobagu** [xmrig/xmrig-proxy#101]
It would be highly appreciated if in next release you can add in api local ip too, for the lan that have one ip out  and 50 locals is hard to keep track what is offline/online.thank you!
Great work with xmrig miner and proxy too! Congrat's

**Comment by xmrig** [comment]
Proxy can see local IPs only if proxy located in same network with miners, over Internet visible only public IP.
Thank you.

**Comment by yobagu** [comment]
thank you for your quick answer, my interest is to have local ips on all workers, over the internet too.if i got a lan apart of the xmrig proxy network is hard to monitor it if no local ip is are available, but thank you, i am aware work is and will be made always to improve it and just for that i want to thank you.
