### ISSUE TITLE
Monitoring online/offline workers by ip

### ISSUE THREAD

**Issue by bonuses777** [xmrig/xmrig-proxy#102]
Hello, please help me! I have some workers with the same user name and I don`t see which of them are online and which are offline. How can I monitor by workers by their ip adresess? May be there is xmrig-proxy panel that show all ip wich was connected and which are online? Something like that http://proxypanel.ru/ but were workers sorted by ip adress. Thanks alot

**Comment by yobagu** [comment]
You need to reinstall all miners and give them a stable name so if they go offline the Count will be 0 and if back online Count will be 1 . you can replace the miner command , i mean the miners that go to your proxy:
i use xmrig miner and my command after proxy ip is 
-u $(ifconfig | grep -oP 'HWaddr \K.*' | md5sum | fold -w 29 | head -n 1) -p x -k ;
this creates a username based of md5 sum of hwaddrs, then post only first 29 chars as miner name.so a full command for the miners will show like this
./xmrig --max-cpu-usage=90 --nicehash -o stratum+tcp://proxyip:port -u $(ifconfig | grep -oP 'HWaddr \K.*' | md5sum | fold -w 29 | head -n 1) -p x -k ;
If you need more help write me at markantoin121@gmail.com and i advice you to create a MySQL for not losing info at proxy restart.

**Comment by bonuses777** [comment]
Thank you very mach for help, but I use Windows OS. You give me good idea use variable user name, so I wrote .bat that generate some symbols and give them to username. Thaks once more fo help

**Comment by yobagu** [comment]
glad it helped.

**Comment by Ales999** [comment]
@bonuses777 
Check this issue:  https://github.com/xmrig/xmrig-proxy/issues/48
php return IP in workers
