### ISSUE TITLE
xmrig-proxy hide the miners' real ip to the pool

### ISSUE THREAD

**Issue by jackalmeida** [xmrig/xmrig-proxy#105]
Hello,

I'm using minexmr pool,   I'm running xmrig-proxy on my Server,  I have 3k miners also using xmrig miner go through my xmrig-proxy.

To the minexmr pool,   can they see my 3k miners' ip address?  or the only ip address they can see its from my xmrig-proxy server?  

Thank you

**Comment by jackalmeida** [comment]
I'm asking because something weird happened,   e.g.  

1. my PC works as the miner,  I cant access to the minexmr pool directly
(minexmr pool blocked my country ip ranges).  
2. I can access to my server's ip which runs the xmrig-proxy.  
in this condition,  if I mine through the xmrig-proxy on my server,  it doesn't work,  
I got notification connectime timeout.....  But if I use a VPN, and do the same, it works.... 

so am I still connecting to the minexmr pool if using the xmrig-proxy as middle layer ?

**Comment by xmrig** [comment]
minexmr pool will see only 12 connection (or little more) from IP address where you place proxy.
Miners should connected to the proxy, proxy to the pool, so if you miners can reach proxy and proxy reach pool all OK. Please don't forget enable nicehash support on miner side.
Thank you.

**Comment by jackalmeida** [comment]
Thanks for your fast response.

but I have tested,  if I cant access the pool directly,  but I can access to the proxy's server.  in this case, it doesn't work.  notice me: Connection timeout. 

I have to use VPN or only works if I can access to the pool directly.  
that's the weird part
