### ISSUE TITLE
xmrig-proxy: src/unix/core.c:233: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.

### ISSUE THREAD

**Issue by alebeta90** [xmrig/xmrig-proxy#108]
Hello friends,

I'm running xmrig proxy in ubuntu 16.04:

i have around 1240 users using the proxy, and sometimes I'm getting this error:
xmrig-proxy: src/unix/core.c:233: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.

Do you know why it is happening?

thanks

**Comment by alebeta90** [comment]
Hello friends,

I had reported the issue also with libuv. They told me the problem is in the way how xmrig-proxy is using the library. for reference here is the issue I opened there: https://github.com/libuv/libuv/issues/1743

I already tried libuv 1.8.2 in ubuntu 16.04 and libuv 1.10.2 in CenOS7

@xmrig

**Comment by whidrasl** [comment]
+1
this error, for example, with this command, and there is no error if change mode to nicehash
`-m simple -b 0.0.0.0:7777 -o "${STRATUM_HOST}" -u .main --variant`
also, on other instances with much less traffic there is no such error

instance log with error:
```
 * VERSIONS    xmrig-proxy/2.6.2 libuv/1.17.0 gcc/6.4.0
 * MODE        simple
 * ALGO        cryptonight
 * POOL #1     *.*.*.*:3333 variant 1
 * BIND #1     0.0.0.0:7777
 * COMMANDS    hashrate, connections, verbose, workers
Assertion failed: handle->flags & UV_CLOSING (src/unix/core.c: uv__finish_close: 250)
```

**Comment by xmrig** [comment]
@whidrasl How many connections?
Thank you.

**Comment by whidrasl** [comment]
upstreams: 119, miners: 30014 (max 30014) +585/-219
for <10k connections -m simple working good

**Comment by xmrig** [comment]
Fixed https://github.com/xmrig/xmrig-proxy/commit/4654e809e295e57e01c3f3aea07323db53bd1568
