### ISSUE TITLE
Expand hashrate reporting

### ISSUE THREAD

**Issue by swampfighter** [xmrig/xmrig-proxy#109]
While hashrate reporting in xmrig-proxy is not very accurate because it is calculated based on submitted shares, it is still useful for general monitoring, and comparing pool hashrates to the proxy calculated rate.  

Workers/Hashrate currently reports only one digit to right of the decimal. Ex: 0.4
Please expand to two digits to the right. Ex: 0.45

**Comment by xmrig** [comment]
Fixed, also added 24 hours interval to workers list.
Thank you.
