### ISSUE TITLE
speed issuse. very low.

### ISSUE THREAD

**Issue by PQFitz** [xmrig/xmrig-proxy#11]
I have about 8000 computer.
use xmrig-proxy nodejs 800khs.
I couldn't use it the day before yesterday. connect error.

i use this version.
ubuntu 16.04 .

[2017-08-25 07:35:41] 19.4 KH/s, shares: 257/0 +50, upstreams: 38, miners: 6113 (max 6300) +1904/-2030

19.4KH/S...

I should 800khs ...  please help me T_T... thank you....

**Comment by xmrig** [comment]
Did you enable nicehash on miner side? It required.
I see 1904 new connections per minute and 2030 disconnects.

**Comment by PQFitz** [comment]
Thanks for your help.
I use xmrig.  But did not enable nicehash. 
if did not enable  Is there a solution?
I prefer use nodejs version.  But he does not seem to be able to use it now..T_T...

**Comment by xmrig** [comment]
What version of xmrig? all versions require to add option `--nicehash`, since version 2.1.0 nicehash support detected in most cases without specify this option, but not 100% detection ratio.

You mean old node.js version of this proxy? it still here in `legacy` branch, but I know only one pool who can handle 8k connections from single IP address.

**Comment by PQFitz** [comment]
i use about 2016.6 version. 

i use pool monero fr and dwarfpool.

I can't find it node.js version xmrig-proxy.

nodejs version yesterday can't use.

T_T.. help me...

i use Atrides/xmr-proxy about 400khs.    but my hash : 800khs


https://github.com/Atrides/xmr-proxy/issues/10

**Comment by xmrig** [comment]
You need to add option `--nicehash` to all your workers, to work with current proxy.

Old version there https://github.com/xmrig/xmrig-proxy/tree/legacy

**Comment by MineMoneroPRO** [comment]
Hi!
Just drop me an email to support@minemonero.pro and we'll configure this proxy with the most efficient way.

**Comment by MineMoneroPRO** [comment]
Hi!
Just drop me an email to support@minemonero.pro and we'll configure this proxy with the most efficient way.

**Comment by xmrig** [comment]
I am on mentioned above pool too and we will happy see 800 khs there, you can send email or join our chat.

**Comment by PQFitz** [comment]
Thank you.
I sent to Email.
^_^.

**Comment by PQFitz** [comment]
Hello.
I need to execute npm update

  "repository": {
    "type": "git",
    "url": "git+https://github.com/xmrig/xmrig-proxy.git"
  },

How do I modify it?
