### ISSUE TITLE
hashrate without and with proxy

### ISSUE THREAD

**Issue by Meyer01** [xmrig/xmrig-proxy#110]
Hello
I have 20+ mining PC's. I'm using supportxmr pool.
When each PC was connected directly to pool, hashrate was stable (+/- 500H/s).
After configuring them to use xmrig proxy, hashrate is not stable anymore. It's +/- 3000 or even more.
The charts looks very different too. Average hashrate is lower with proxy. What can be wrong?
First picture is before using proxy. Second is after.
![before](https://user-images.githubusercontent.com/36437117/36197996-7bd3abd8-1186-11e8-8761-32a0457e94ee.PNG)
![with proxy](https://user-images.githubusercontent.com/36437117/36197997-7bf09a9a-1186-11e8-8e08-8aa78633be0c.PNG)

**Comment by xmrig** [comment]
1. Please make sure nicehash option enabled on each PC.
2. If you want more smooth hashrate set fixed diff (please note lower values increase pool load), to view current diff press `v` in terminal or permanently enable via `verbose` option.
Thank you.

**Comment by Meyer01** [comment]
1) nicehash enabled, keepalive disabled
2) increase pool or proxy load?
Thank you!

**Comment by xmrig** [comment]
Sorry, missed your reply. Actually both, but for proxy it doesn't matter much. Pool load increased because pool need validate shares, lower diff => more shares.
Thank you.
