### ISSUE TITLE
XMRig Proxy - two network interfaces.

### ISSUE THREAD

**Issue by Pbotton** [xmrig/xmrig-proxy#111]
Hello! I'm using XMRig Proxy on Windows 10 machine with two network cards.
Is it possible to listen miners on card 1 and connect to pool on card 2?
Thanks:-)

**Comment by xmrig** [comment]
> Is it possible to listen miners on card 1

Use IP address from this card, instead of `0.0.0.0`.

> and connect to pool on card 2?

Only if card 2 connected to Internet and card 1 not, anyway OS control it.
Thank you.

**Comment by Pbotton** [comment]
>> Is it possible to listen miners on card 1
>Use IP address from this card, instead of 0.0.0.0.
>>and connect to pool on card 2?
>Only if card 2 connected to Internet and card 1 not, anyway OS control it.

Thank you.
