### ISSUE TITLE
Redundany proxy setup/configuration

### ISSUE THREAD

**Issue by setiawani** [xmrig/xmrig-proxy#112]
I want to run 2 proxy node for redundancy purposes.
For failover I plan to use vrrp to enable ip failover from one proxy node to another.
do you see any session/data loss/connection issue with this plan?

**Comment by xmrig** [comment]
If you want chain proxies, eg connect one to another it not supported.
Thank you.

**Comment by marki555** [comment]
@setiawani Why not just use failover in the miner itself? I guess all miners allow you to specify more than one "pool". That way you can have the proxies on completely different networks (something not possible with vrrp).

**Comment by garrylachman** [comment]
I use DNS load balancing for this.
just create 2 A records to the same IP
proxy.domain.tld -> 1.1.1.1
proxy.domain.tld -> 2.2.2.2
