### ISSUE TITLE
Feature Request: Graceful shutdown and graceful restart option

### ISSUE THREAD

**Issue by nutsnax** [xmrig/xmrig-proxy#113]
I hope this is in the right place... but I have a feature request for xmrig-proxy....

A graceful shutdown/restart option whereby when the shutdown request is received, xmrig-proxy 'waits' for workers to finish up their work and then stops accepting work from them. 

Process flow example using 2 mining rigs connecting to a proxy:

Graceful shutdown/restart request received:
1. echo "Shutdown request received... waiting for rigs to finish up...."
2. Rig #1 submits share, further shares blocked from that worker
3. Proxy knows 2 rigs are connected and waits for final share from Rig #2
4. Rig #2 submits share, xmrig-proxy blocks further shares and shuts down/restarts

Configurable option "Timeout" : Wait X number of seconds for shares when shutdown received.

Hopefully self-explanatory why I'm asking for this... but I'll explain anyway:

The idea here being that when the shutdown/restart request is received, the miners aren't losing the work they are currently doing.

**Comment by xmrig** [comment]
In next version (2.5) will be added graceful reload (config reload without loosing state) but there no reason for waiting, mining work is pure random here is no any kind of final share. One true solution is switch job as fast as possible.
Thank you.

**Comment by xmrig** [comment]
In dev branch added graceful reload support, more details: #119

**Comment by nutsnax** [comment]
I'm working with dev branch... getting this error:  
![image](https://user-images.githubusercontent.com/35117940/36943938-43f0e2f2-1f60-11e8-8ea0-54860cc707d5.png)

**Comment by xmrig** [comment]
I figured it out, it expired share, itself it not issue and sometimes happen.
Please note this share will lost anyway, bug is only it bypassed to upstream pool. I will fix it later today.
Thank you.

**Comment by xmrig** [comment]
Fixed.

**Comment by nutsnax** [comment]
could it be possible to send 'old shares' received after the switch to the previous pool?

**Comment by xmrig** [comment]
It possible, but required non trivial logic to track both connections new one and old one for some time, but in worst case on few second can be loose (network latency + miner latency, especially for GPU).
Thank you.
