### ISSUE TITLE
v2.5 changes overview

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig-proxy#119]
## Configuration
In version **2.5** introduced graceful reload, pools and some other settings now can changed without proxy restart. 2 mechanism available:

- [x] File system watcher (via uv_fs_event_t) if config file changed or replaced proxy will automatically load new configuration after 500 ms delay.
- [x] Change config remotely via HTTP API.

File system watcher enabled by default, this feature can disabled via `--no-watch` command line option or `"watch": false,` config file option. If used multiple config files, only last will be watched. If config file not used at all this feature not available.

Options supports graceful reload:

- All `pools` options.
- `colors`.
- `debug`.
- `verbose`.
- `custom-diff`, only for new connections.
- `api/worker-id`
- `reuse-timeout`

## Monero v7 PoW
Added addition option `variant` to override algorithm variation on miner side, works only with xmrig miners, it's optional for better convenience. PoW changes not affect stratum protocol so no changes required.

## API
Old endpoints now deprecated but still available, please update your monitoring tools.

- [x] `GET /1/summary` instead of `GET /`
- [x] `GET /1/workers` instead of `GET /workers.json`
- [x] `GET /1/config` :new:
- [x] `PUT /1/config` :new: [example](https://github.com/xmrig/xmrig-proxy/issues/40#issuecomment-370202169)

## IPv6
IPv6 now fully supported:

- [x] connect to upstream pools.
- [x] incoming connections.
- [x] incoming connections to HTTP API.

## Other changes
- Added alternative working mode, in that mode proxy support chaining and nicehash.com but lose ability to reduce connection count. More details #118
- Option `coin` now deprecated, use `algo` instead, too many coins now, but only 2 algorithm, also new option unify proxy with miners.

**Comment by nutsnax** [comment]
Thank you!!!

**Comment by xmrig** [comment]
I decided to stop add new features in v2.5, release will be available after all testing passed.

**Comment by xmrig** [comment]
v2.5.0 released.
