### ISSUE TITLE
Why my hash rate is 0

### ISSUE THREAD

**Issue by VakhoQ** [xmrig/xmrig-proxy#120]
Hi all,

**Idea:**
Let's say that my  IP address is **1.1.1.1.1**.  I don't have permission to connect  pool.supportxmr.com:3333  (blocked by firewall). Generally, I have **only 80** port open.

**Try to solve problem**
I've  build xmrig-proxy on AWS EC2 T2.Micro.  Let's say that my AWS EC2 IP adress is **2.2.2.2.**

So I run the proxy on AWS EC2 like this:

```
./xmrig-proxy  -b 0.0.0.0:80 -o pool.supportxmr.com:3333 -u WALLET_ID -p x
```

Now instead of **pool.supportxmr.com:3333** I'm connecting to **2.2.2.2:80** (From my local machine  to AWS EC2)

I **really** have access to from 1.1.1.1 to 2.2.2.2:80. Here is **nmap** log:
```
nmap 2.2.2.2 -p 80
PORT   STATE SERVICE
80/tcp open  http
Nmap done: 1 IP address (1 host up) scanned in 0.60 seconds
```
Off course I have access **from EC2** server to   **pool.supportxmr.com**:3333 too.

**Mining from my local machine:**

```
./xmrig 
VERSIONS:     XMRig/2.4.5 libuv/1.8.0 gcc/7.1.0
* HUGE PAGES:   available, disabled
* CPU:          Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (1) x64 AES-NI
* CPU L2/L3:    1.0 MB/6.0 MB
* THREADS:      3, cryptonight, av=1, donate=10%
* POOL #1:      2.2.2.2:80
* COMMANDS:     hashrate, pause, resume
[2018-02-28 19:10:33] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-02-28 19:10:43] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-02-28 19:10:53] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-02-28 19:11:03] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
[2018-02-28 19:11:13] speed 2.5s/60s/15m n/a n/a n/a H/s max: n/a H/s
```

config:
```

   "pools": [
        {
            "url": "2.2.2.2:80",   
            "user": "WALLET_ADRESS",                     
            "pass": "x",                       
            "keepalive": true,                 
            "nicehash": false                  
        }
    ],
    "api": {
        "port": 0,                             
        "access-token": null,                 
        "worker-id": null                    
    }
}

```
**Problem**
Hashr ate is 0

**Log:**
```
./xmrig-proxy  -b 0.0.0.0:80 -o pool.supportxmr.com:80 -u WALLET 6CHrqTpucoccKhUmGZV  -p x
 * VERSIONS:     xmrig-proxy/2.4.5 libuv/1.8.0 gcc/5.4.0
 * POOL #1:      pool.supportxmr.com:80
 * BIND #1:      0.0.0.0:80
 * COMMANDS:     hashrate, connections, verbose, workers
[2018-02-28 14:51:15] #000 use pool pool.supportxmr.com:80 104.140.201.62
[2018-02-28 14:52:15] 0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 1 (max 1) +1/-0
[2018-02-28 14:52:17] * speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2018-02-28 14:52:19] * speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s

```

**Comment by xmrig** [comment]
No connection to proxy, no messages `use pool...` and `new job...` on miner side, probably you need open port in your AWS firewall or something like that. If you want use xmr-stak (yep I see original message received via github email) you must add option `--use-nicehash`.

But primary reason of 0 hashrate is no connectivity. Also you can press 'c' or `w` in proxy terminal to see connection count.
Thank you.

**Comment by xmrig** [comment]
But strange, proxy show 1 miner connected.

**Comment by VakhoQ** [comment]
The interesting part is that I've tried connecting to AWS proxy server from **2** computer. They were on the **different** network. The one was working well (hash rate was more then 0) but the second does **not.** Generally, it proves that the application does **not have any issues**. It should be caused by network problem (**something blocks mining** even though port 80 is open - but I don't understand how it is possible?  Anyway, I don't think that it is an application issue.  

Thank you!

**Comment by lisergey** [comment]
@VakhoQ, this very well could be with http interception in second case.
On the gateway there is a firewall, which has a rule to divert all traffic from any host in lan to any host outside on port 80 to internal http proxy.
For details see https://wiki.squid-cache.org/SquidFaq/InterceptionProxy
