### ISSUE TITLE
Getting 0 accepted or rejected from minexmr.com

### ISSUE THREAD

**Issue by bittaurus** [xmrig/xmrig-proxy#122]
#./xmrig-proxy.bin --url=stratum+tcp://pool.minexmr.com:7777 --bind=0.0.0.0:3333 --user=[wallet] --pass=x --coin=xmr

 * VERSIONS:     xmrig-proxy/2.4.5 libuv/1.10.2 gcc/4.8.5
 * POOL #1:      pool.minexmr.com:7777
 * BIND #1:      0.0.0.0:3333
 * COMMANDS:     hashrate, connections, verbose, workers
[2018-03-04 06:31:33] #000 use pool pool.minexmr.com:7777 94.130.206.79
[2018-03-04 06:31:37] * speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
WORKER NAME             | LAST IP         | COUNT | ACCEPTED | REJ |  10 MINUTES |    24 HOURS |
00008                   | 73.96.113.1      |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00010                   | 73.96.113.2      |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00024                   | 73.96.113.3      |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00002                   | 73.96.113.4      |     2 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00118                   | 73.96.113.5      |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00012                   | 73.96.113.6      |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00026                   | 73.96.113.7      |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00028                   | 73.96.113.8      |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00112                   | 73.96.113.9      |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00114                   | 73.96.113.10    |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00116                   | 73.96.113.11    |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00120                   | 73.96.113.12    |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
00022                   | 73.96.113.13    |     1 |        0 |   0 |   0.00 kH/s |   0.00 kH/s |
[2018-03-04 06:31:46] * upstreams active: 1 sleep: 0 error: 0 total: 1
[2018-03-04 06:31:46] * miners    active: 14 max: 14 ratio: 1:14.0

As you can see, everything looks connected up, my miners are working on something, but nothing is getting upstream to be accepted or rejected?  I had to compile with -DWITH_HTTPD=OFF to get it to compile.  It's a centos 7.

Linux responsive 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Any ideas?

**Comment by xmrig** [comment]
Did you enable nicehash mode on miner side?
Thank you.
