### ISSUE TITLE
Hashrate fluctuate in a range.

### ISSUE THREAD

**Issue by Umiiii** [xmrig/xmrig-proxy#124]
I'm sure that it's neither pool nor difficulty problem because I have changed 2 pools (nanopool and f2pool) and use static difficulty and dynamic difficulty, so is that I set the wrong options or there is some bug with xmrig?

<img width="681" alt="1" src="https://user-images.githubusercontent.com/29030474/37028739-0bb12584-2170-11e8-8f12-37e29ab4cd10.png">

I use 1G 1U running xmrig-proxy on Ubuntu 16.04 x64 with 100MB bandwidth.
There is around 150 miner and the average hashrate is 150H/s.

**Comment by xmrig** [comment]
Hashrate fluctuation depends of diff, less diff => more shares => less fluctuation, higher diff => less shares => higher fluctuation. Pool and proxy don't know real hashrate and estimate it by submitted shares, so it pretty normal.
Thank you.

**Comment by Umiiii** [comment]
But  I've already tried a static diff, it still fluctuated in a small range.

**Comment by FranzDE** [comment]
the correct way is to set the static diff level on the miners, or on the proxy?
I think on the proxy, but I'm not sure.
thanks
