### ISSUE TITLE
Feature request: Fallback pools should be used immediately instead of idling. 

### ISSUE THREAD

**Issue by plavirudar** [xmrig/xmrig-proxy#127]
The current behaviour of the proxy during a pool becoming unreachable is to attempt reconnections to the original pool, and only until N retries fail will it even attempt to connect to the fallback pools. If the original pool is not responding, the proxy will idle until it times out, which appears random but can be in the timeframe of multiple minutes.

This results in the miners idling for that interval, and may significantly reduce profit for pools which are less stable than average. 

I propose that a connection to the second pool be constantly maintained (similar to the behaviour shown by xmr-stak) and upon the first pool failing, it should immediately start proxying the block template of the fallback pools, switching back when it receives a new valid block template from the original pool.

**Comment by xmrig** [comment]
You can reduce 2 options:
```
  -r, --retries=N          number of times to retry before switch to backup server (default: 5)
  -R, --retry-pause=N      time to pause between retries (default: 5)
```
But you are right, should reduce default values.
Thank you.

**Comment by plavirudar** [comment]
Thanks for the quick response! 

It seems that the minimum allowed values for these is 1, which would be fine but the timeout for the connection seems to be approx. 2 minutes or so. 

Is there a way to reduce the timeout and just switch pools right away?

**Comment by xmrig** [comment]
libuv use internal 30 seconds timeout for stuck connections, if pool refuses connection there will be no timeout, hard to avoid this timeout, but 2 minutes is not sound good, it can be 4 * 30 but if you already reduce retries to 1 I don't know where 2 minutes timeout come.
Thank you.
