### ISSUE TITLE
Can I use many miners with the same ip

### ISSUE THREAD

**Issue by developernew123** [xmrig/xmrig-proxy#129]
I don't understand properly hpw xmrig proxy differs from the usual xmrig 
But I heard that if I had many miners on different machines I can use proxy to give them one ip and make them look as one miner only , I am not sure about this but this what I understood , so is this right ? , and can I use xmrig proxy to make several miners look like one miner ? , and how ??

**Comment by xmrig** [comment]
Proxy works as middleman, you need point your miners to proxy and proxy to pool. How many miners will see pool it depends, proxy can reduce connection count only up to 256 times.
Thank you.

**Comment by developernew123** [comment]
Does this mean If I have 256 miner they will be as one miner ?

**Comment by developernew123** [comment]
and will the power be the sum of all miners power ?

**Comment by developernew123** [comment]
I think I wasn't clear enough as I didn't know how to express .
After some research on reddit I found that xmr-node-proxy merges the connections of miners to the pool into one connection so the pool will see one connection and xmrig-proxy will deliver to each miner the connection belongs to it then each miner starts to work, send connections to xmrig-proxy , to the pool .......

This is exactly what I want , I want the pool to see only one miner mining for the same address although I have multi miners 
If xmrig-proxy can do this then it's very good

**Comment by developernew123** [comment]
@xmrig

**Comment by xmrig** [comment]
This proxy works exactly same way as nicehash.com works. How many miners will see pool depends of how many miners you have. Check this comment https://github.com/xmrig/xmrig-proxy/issues/16#issuecomment-326478823 for some numbers.
Thank you.
