### ISSUE TITLE
clarifying the advantage of a proxy

### ISSUE THREAD

**Issue by lexphor** [xmrig/xmrig-proxy#13]
Pardon me if this isn't the most suitable place to ask this noob-like question, what exactly are the advantages of using this proxy program instead of just pointing multiple miners directly to the pool?

**Comment by xmrig** [comment]
Primary reason written in README
`This proxy designed and created for handle donation traffic from XMRig. No one other solution works fine with high connection/disconnection rate.`

Second, it centralized management of miners, need change pool? or your pool down need switch to backup? okay it can done in proxy, don't need change settings and restart your miners.

Third, really big count of miners it always issue, pools don't like it.

And last if you has few hundreds or less of miners, you probably don't need proxy.

**Comment by lexphor** [comment]
Thanks for the clarification.
