### ISSUE TITLE
question about low power miners

### ISSUE THREAD

**Issue by yangsystem** [xmrig/xmrig-proxy#130]
i want to know if it will combine my low power miners in a more powerfull one so i can mine some difficult blocks or it will just load less the network by sending bigger packets.

10q

**Comment by xmrig** [comment]
If think about miners as threads in one big multi-threaded miner (up to 256 threads) it will become more powerfull one. Network load will reduced too, less connections, less packets, but single packet size will never changed.
Thank you.

**Comment by yangsystem** [comment]
ok. so if i will connect to the proxy 5 small miners with 10 15 25 30 35 hash wi will have the power to mine with the combined power?
for solo it will process at difficulty 10*30 15*30 ...
for proxy it will work as a single miner at difficulty 115*30?  i know if you mine at bigger diff you get more coins.
at some pools you get nothong with 30hash. will the proxy combine the power to the small miners in one big miner and result in a 105hash miner?

**Comment by xmrig** [comment]
It not work like that, only cumulative hashrate maters, one 115 H/s miner or 5 smaller point directly to pool, will get same result. With same hashrate bigger diff only means less shares, you not get more coins.
Thank you.

**Comment by yangsystem** [comment]
so in conclusion i will not be abel to mine with 5 small miners combined via proxy on a pool where the individual miner will have co accepted share.

the proxy will only release the stress on network by making less conbections

**Comment by xmrig** [comment]
Any miner with any speed can found shares with any diff. No need to found shares every 2 minutes, it just for better estimate your hashrate by pool.
10 H/s miner can work with 100000 diff, with 100% effort share will be found every 1666 minutes. It useless but share will be found anyway.
Thank you.
