### ISSUE TITLE
No workers shown in pool

### ISSUE THREAD

**Issue by swordencao** [xmrig/xmrig-proxy#131]
My xmrig-proxy works and hashrate on pool is correct but no works shown. I used nanopool and try to add correct address format in config file but take no effort. Any ideas to solve?

Thank you

**Comment by xmrig** [comment]
If you mean no see accepted shares in proxy console, verbose output disabled by default press `v` or enable it permanently via `verbose` option.

If you mean no see workers on nanopool it's ok, proxy reduce connection count up to 256 times, so no way to see workers on pool side, you can do it only on proxy side.
Thank you.
