### ISSUE TITLE
Proxy crash on 2.5.0 dev

### ISSUE THREAD

**Issue by plavirudar** [xmrig/xmrig-proxy#133]
One of my proxies crashed after a network error to the pool resulted in a timeout. It returned the error

> ap: src/unix/getaddrinfo.c:91: uv__getaddrinfo_translate_error: Assertion `!"unknown EAI_* error code"' failed.

Crash occurred on Ubuntu 16.04 with gcc5 compiler. Happy to test reproducibility if necessary.

**Comment by xmrig** [comment]
What version of libuv you use? default 1.8.0? and what pool (if it not secret).
Thank you.

**Comment by plavirudar** [comment]
I was using the default libuv from apt-get in ubuntu 16.04, and was on the aeonminingpool.com pool. 

```
apt-get -s install libuv1-dev
NOTE: This is only a simulation!
      apt-get needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree
Reading state information... Done
libuv1-dev is already the newest version (1.8.0-1).
```

**Comment by plavirudar** [comment]
Did some more digging and this seems to be a problem with `proxychains` and not xmrig-proxy. Closing. https://stackoverflow.com/questions/39025118/proxychains-bower-fails-dns-lookup
