### ISSUE TITLE
XMRIG PROXY TELEGRAM

### ISSUE THREAD

**Issue by ghost** [xmrig/xmrig-proxy#134]
- Сompletely free bot for convenient monitoring of miners!
- Very simple and user-friendly interface.
- Complete statistics for workers.
- Round-the-clock customer support.
- Completely anonymous, your data is not stored on the server.

https://telegram.me/xpower_bot =)

**Comment by xmrig** [comment]
Im not familiar how telegram bots works, it hosted somewhere so it can't connected to local IPs, for example `127.0.0.1`? If it work only over Internet need add support for access token.

Is source available?
Thank you.

**Comment by etnpoolorg** [comment]
Now I'm finishing it encountered an error.

**Comment by etnpoolorg** [comment]
Tell me how does access-token
utr+access-token ?
utr/access-token ?

**Comment by xmrig** [comment]
Access token should passed via `Authorization` header, example: https://gist.github.com/xmrig/c75fdd1f8e0f3bac05500be2ab718f8e#file-api-html-L54
Thank you.

**Comment by etnpoolorg** [comment]
**UPDATE PROXY TELEGRAM** 

- Fixed all the bugs.
- Made the bot more comfortable.
- Also rewrote it from nodejs to python

Bot - https://telegram.me/xpower_bot

**Comment by ORGaniZMo** [comment]
Not working - no reactions

**Comment by etnpoolorg** [comment]
Try it now , as many of my friends work perfectly

**Comment by ORGaniZMo** [comment]
![screen](https://user-images.githubusercontent.com/25881599/37578093-4f2e24dc-2b58-11e8-9b43-a25a07418d67.png)
увы!

**Comment by etnpoolorg** [comment]
<img width="684" alt="2018-03-19 11 54 09" src="https://user-images.githubusercontent.com/36627349/37586077-48361414-2b6c-11e8-80ea-e47fd63fcff5.png">

**Comment by etnpoolorg** [comment]
<img width="690" alt="2018-03-19 11 58 15" src="https://user-images.githubusercontent.com/36627349/37586250-d801b17a-2b6c-11e8-97bf-2c0cbe709b0e.png">

**Comment by ORGaniZMo** [comment]
Мы так можем до опупения скринами перекидываться. Предположения есть?

**Comment by etnpoolorg** [comment]
У моих всех знакомых работает )

**Comment by ORGaniZMo** [comment]
Спасибо. В телеге всё решили.
