### ISSUE TITLE
nicehash

### ISSUE THREAD

**Issue by mikef147** [xmrig/xmrig-proxy#14]
The proxy doesn't work with nicehash? I have the --nicehash option going on miners to this proxy, but all shares still rejected from nicehash server.

**Comment by xmrig** [comment]
Yep you can't use this proxy with nicehash.com, but miners required be nicehash comparable. Proxy works like nicehash, use same method to reduce connection count.
Thank you.

**Comment by MultiMiner** [comment]
And nothing can be done? Nisehash is very convenient, like this proxy.

**Comment by xmrig** [comment]
Sorry it can't fixed by design, only one nicehash proxy possible in chain, nicehash.com itself or this proxy.

**Comment by MultiMiner** [comment]
Very sad ( The proxy about which Nicehash writes, the stratum-proxy, does not support cryptonight ((

**Comment by rinaldohack** [comment]
So, let me get this straight. You are emulating how nicehash.com work, don't you?

**Comment by xmrig** [comment]
Exactly right.

**Comment by rinaldohack** [comment]
any way we could turn this into nicehash.com proxy? I have many workers, but with wrong username :(

**Comment by madscientist159** [comment]
What is the exact technical reason this proxy can't connect to nicehash?

**Comment by jnicholls** [comment]
I'd like to know the technical reason as well.  Couldn't it simply pass off to nicehash the same as the `xmrig` miner would, but after the combining of the nonce work from client miners?

**Comment by ddebin** [comment]
#83
