### ISSUE TITLE
xmrig-proxy stop at pow change update?

### ISSUE THREAD

**Issue by solustore-h** [xmrig/xmrig-proxy#142]
xmrig-proxy stop at pow change update?

**Comment by solustore-h** [comment]
I'll need to update on the hosts?

**Comment by kimats** [comment]
please see this thread, it explain your question:
https://github.com/xmrig/xmrig/issues/434

**Comment by ProfDD** [comment]
For the algorithm updgrade, to update xmrig proxy is optional?  But must upgrade the mining software ?

**Comment by xmrig** [comment]
Exactly right.
