### ISSUE TITLE
optimize miners (xmrig) and xmrig-proxy config

### ISSUE THREAD

**Issue by FranzDE** [xmrig/xmrig-proxy#144]
Hi, I'm using xmrig miners (about 38 cpu miners) on different networks.
Previously I used for all the xmrig miners, the pool "pool.supportxmr.com:3333" (I know the pool set automatically the most suitable level of difficulty for the single miner)

The hash-power of my 38 miners goes from 60hs (the poorest) to 290hs (the best).
I see that if I don't set "custom-diff": 5000, on xmrig-proxy, all miners take a very high level of difficulty.
After I set "custom-diff": 5000, all miner receve from the xmrig-proxy the difficulty level of 5000.

With "nicehash" support set to "enable" on xmrig miner side, I don't see any difference. I read that it should be activated when mining through xmrig-proxy
Or I should use "nicehash" support only with "custom-diff": 0 ??

The actual xmrig-proxy level difficulty receved from pool is 53100.

Since I have miners with different hashpower, what are the optimal settings to adopt? I have noticed that since I have set "custom-diff": 5000 on xmrig-proxy, the "Invalid shares" have drastically decreased.

**Comment by xmrig** [comment]
1 `custom-diff` usable only for miners without keepalive support to prevent timeouts, until proxy submit shares in normal rate, few shares per minute, does't mater how high is diff on miner side.
2. Proxy works like nicehash.com, xmrig miner detects it in 255 cases of 256.
3. Address and port for incoming connections, 0.0.0.0 means any available IPv4 interface.

All above questions was answered multiple times, you can found more details if use search in issues.

About invalid shares, what exactly error do you see? and what side? proxy or miner, custom diff should not affect it.
Thank you.

**Comment by FranzDE** [comment]
thanks for the reply.
About the invalid shares, I saw them when I had no "custom-diff" set in xmrig-proxy.

The invalid shares was on the miners side.
stats from xmrig-proxy
![xmrig-proxy - copia](https://user-images.githubusercontent.com/37615468/37826400-998a4efa-2e93-11e8-85e8-d81f405dbbe9.PNG)

stats from xmrigCC miner
![xmrigccserver - copia](https://user-images.githubusercontent.com/37615468/37826430-b79d45d2-2e93-11e8-8809-44ddcd9c6164.PNG)

I have small hash miner 70hs and without "custom-diff" 1000 value, the miner shows, 20000 difficulty jobs. 
After enabling "custom-diff" 1000, the "invalid jobs" on miners logs, they disappeared.

**Comment by Robkof2002** [comment]
FranzDE
Send me a tutorial on how to use xmrig-proxy and xmrigCC
Pls
