### ISSUE TITLE
Rejected: Low difficulty share on any Graft pool

### ISSUE THREAD

**Issue by wanda7566** [xmrig/xmrig-proxy#145]
anyone having problems mining graft using xmrig-proxy?

proxy is working on any coin except for graft

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/issues/434#issuecomment-373184425 you must set variant 0 on each miner config or if you update proxy to v2.5 (dev branch in git) you can do it only in proxy config.
Thank you.

**Comment by p1vynodejs** [comment]
i tried using the dev branch, but same result. here's my proxy config:

```
{
    "access-log-file": null,
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null,
        "ipv6": true,
        "restricted": true
    },
    "background": false,
    "bind": [
        "0.0.0.0:3333",
        "[::]:3333"
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 1,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "url": "pool.graft.hashvault.pro:5555",
            "user": "<wallet address>",
            "pass": "x",
            "variant": 0
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "user-agent": null,
    "verbose": true,
    "watch": true,
    "workers": true
}
```

PS. I have changed the user and pass

**Comment by xmrig** [comment]
Are you sure proxy print version `xmrig-proxy/2.5.0-dev` on startup? I checked it, work as expected.
`variant` in proxy config works only with xmrig miners v2.5+ if you use other miners you need configure each miner individually.
Thank you.

**Comment by plavirudar** [comment]
@xmrig I can verify that this bug is an issue when using the config file reload feature. It appears that not all of the pools are successfully reloaded, especially if they have different variables set, or if multiple fallback pools are specified in the config. For example, if I set the `custom-diff` variable to different numbers in different config files, they are not reloaded correctly when the config file is auto-updated. I suspect this could be causing the issue.

**Comment by plavirudar** [comment]
Actually I just tried recompiling from latest branch, looks like I had an older version that didn't have `variant` support. Everything seems to be working now.

**Comment by kim0** [comment]
Hi @xmrig .. It's great to know that the proxy can set the `variant` remotely configured on the proxy side. My question, can the proxy also set the `algo` remotely ? i.e. for example, for mining Sumo, the proxy sets `algo=cryptonight-heavy` and this setting is sent to xmrig miner automatically without reconfiguring every miner?

Please let me know if this is possible. Thanks!

**Comment by xmrig** [comment]
It not possible at this moment, more details in https://github.com/xmrig/xmrig/issues/487 I thinking about this feature, but too busy right now.
Thank you.
