### ISSUE TITLE
static build without libmicrohttp, not find uuid/uuid.h

### ISSUE THREAD

**Issue by Wayho** [xmrig/xmrig-proxy#146]
Method from https://github.com/xmrig/xmrig/pull/442
apk add --no-cache alpine-sdk cmake libuv-dev
git clone --depth=1 https://github.com/xmrig/xmrig
mkdir xmrig/build && cd xmrig/build
cmake .. -DWITH_HTTPD=OFF -DBUILD_STATIC=ON
make
*****************************************
i have git and build libuv, not run first line
$git clone --depth=1 git clone --depth=1 https://github.com/xmrig/xmrig-proxy.git
$mkdir xmrig-proxy/build && cd xmrig-proxy/build
$cmake .. -DWITH_HTTPD=OFF -DBUILD_STATIC=ON
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_STATIC

-- Build files have been written to: /...../xmrig-proxy/build

$make
xmrig-proxy/src/proxy/Uuid_unix.cpp:24:23: fatal error: uuid/uuid.h: 没有那个文件或目录
compilation terminated.
CMakeFiles/xmrig-proxy.dir/build.make:1046: recipe for target 'CMakeFiles/xmrig-proxy.dir/src/proxy/Uuid_unix.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/proxy/Uuid_unix.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-proxy.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Wayho** [comment]
$sudo apt install uuid uuid-dev
$ make
[  2%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Uuid_unix.cpp.o
[  4%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/SysLog.cpp.o
[  6%] Linking CXX executable xmrig-proxy
[100%] Built target xmrig-proxy
OK!

**Comment by kpcyrd** [comment]
```
Manually-specified variables were not used by the project:
```
Can you run `git show`?
