### ISSUE TITLE
Build issue with HTTPD off

### ISSUE THREAD

**Issue by MrCowKing** [xmrig/xmrig-proxy#148]
As of commit dc42d4b862444ad7dd5a1b944d37fb1013f62dde, using the cmake option WITH_HTTPD=OFF results in linking error. An easily solved problem, but annoying. Everything seems to compile fine, but when the linking stage happens it errors out.

Here's the error I got: 

> [100%] Linking CXX executable xmrig-proxy
> CMakeFiles/xmrig-proxy.dir/src/api/ApiRouter.cpp.o: In function `ApiRouter::exec(xmrig::HttpRequest const&, xmrig::HttpReply&)':
> ApiRouter.cpp:(.text+0xfa): undefined reference to `xmrig::HttpRequest::match(char const*) const'
> ApiRouter.cpp:(.text+0x11c): undefined reference to `xmrig::HttpRequest::body() const'
> CMakeFiles/xmrig-proxy.dir/src/api/ApiRouter.cpp.o: In function `ApiRouter::get(xmrig::HttpRequest const&, xmrig::HttpReply&) const':
> ApiRouter.cpp:(.text+0x7e4a): undefined reference to `xmrig::HttpRequest::match(char const*) const'
> ApiRouter.cpp:(.text+0x7f19): undefined reference to `xmrig::HttpRequest::match(char const*) const'
> ApiRouter.cpp:(.text+0x7f2e): undefined reference to `xmrig::HttpRequest::match(char const*) const'
> ApiRouter.cpp:(.text+0x7f59): undefined reference to `xmrig::HttpRequest::match(char const*) const'
> ApiRouter.cpp:(.text+0x7fa0): undefined reference to `xmrig::HttpRequest::match(char const*) const'
> CMakeFiles/xmrig-proxy.dir/src/api/ApiRouter.cpp.o:ApiRouter.cpp:(.text+0x7fd5): more undefined references to `xmrig::HttpRequest::match(char const*) const' follow
> collect2: error: ld returned 1 exit status
> CMakeFiles/xmrig-proxy.dir/build.make:1370: recipe for target 'xmrig-proxy' failed
> make[2]: *** [xmrig-proxy] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-proxy.dir/all' failed
> make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by xmrig** [comment]
Fixed. Thank you.
