### ISSUE TITLE
Compile v2.5 on Centos

### ISSUE THREAD

**Issue by fix76** [xmrig/xmrig-proxy#149]
# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

# gcc -v
Используются внутренние спецификации.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Целевая архитектура: x86_64-redhat-linux
Параметры конфигурации: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Модель многопоточности: posix
gcc версия 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

my error:

# make
Scanning dependencies of target xmrig-proxy
[  1%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App.cpp.o
[  3%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/Console.cpp.o
[  5%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/Config.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/ConfigLoader.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/ConfigWatcher.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/Controller.cpp.o
[ 13%] Building C object CMakeFiles/xmrig-proxy.dir/src/crypto/c_keccak.c.o
[ 15%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/AccessLog.cpp.o
[ 17%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/ConsoleLog.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/FileLog.cpp.o
[ 21%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/Log.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/ShareLog.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/Client.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/Job.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/strategies/DonateStrategy.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 32%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/SubmitResult.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/Url.cpp.o
/home/xmrig-proxy/src/net/Url.cpp: In constructor «Url::Url()»:
/home/xmrig-proxy/src/net/Url.cpp:48:24: ошибка: несовместимые типы в присваивании «const char [1]» -> «char [5]»
     m_port(kDefaultPort)
                        ^
/home/xmrig-proxy/src/net/Url.cpp: In constructor «Url::Url(const char*)»:
/home/xmrig-proxy/src/net/Url.cpp:71:24: ошибка: несовместимые типы в присваивании «const char [1]» -> «char [5]»
     m_port(kDefaultPort)
                        ^
/home/xmrig-proxy/src/net/Url.cpp: In constructor «Url::Url(const char*, uint16_t, const char*, const char*)»:
/home/xmrig-proxy/src/net/Url.cpp:83:16: ошибка: несовместимые типы в присваивании «const char [1]» -> «char [5]»
     m_port(port)
                ^
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/net/Url.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Ошибка 2
make: *** [all] Ошибка 2

**Comment by xmrig** [comment]
Fixed.
