### ISSUE TITLE
Force define __STDC_FORMAT_MACROS on all platforms

### ISSUE THREAD

**Issue by lexphor** [xmrig/xmrig-proxy#15]
Could you please do the fix for 'Force define __STDC_FORMAT_MACROS on all platforms.' like you did for xmrig cpu. 

Thanks

**Comment by xmrig** [comment]
Done

**Comment by lexphor** [comment]
Thank you very much.
I really need your help in configuring a 4 socket/8 NUMA nodes CPU. I already posted the problem on the xmrig page.

Thanks again for your help and support. Highly appreciated.
