### ISSUE TITLE
why is there no worker offline log?

### ISSUE THREAD

**Issue by coolhty** [xmrig/xmrig-proxy#150]
unable to find offline worker?

**Comment by coolhty** [comment]
@0xc0d32 but no offline worker's name

**Comment by 0xc0d32** [comment]
worker name is 'password' field

**Comment by coolhty** [comment]
@0xc0d32  i can only see the number of offline workers through the API. i don't know which worker is offline.

**Comment by 0xc0d32** [comment]
@coolhty well the medium I use to know which miners I am on/off is to set a different name for each one and observe 'Connection count' in '/workers.json' to know who is on/off.

**Comment by coolhty** [comment]
@0xc0d32  thanks guy, if the log can be printed, it will be more convenient

**Comment by 0xc0d32** [comment]
@coolhty really! I hope to have help in some way!
