### ISSUE TITLE
xmr-stak and xmrig-proxy

### ISSUE THREAD

**Issue by marki555** [xmrig/xmrig-proxy#153]
Hi, how does it work when using xmr-stak in nicehash mode connected to xmrig-proxy with regards to monero v7? Is xmr-stak also able to auto-detect the algo based on the work it receives from proxy? I am using proxy to switch between the coins without modifying the miners.

**Comment by xmrig** [comment]
In simple case, you choice `monero7` in stak config and mine Monero and other coins (until they not update PoW too, except GRAFT, it will work. Future will be worse, some coins, like SUMO, will complete change PoW.
Thank you.
