### ISSUE TITLE
Compiling error v2.5.2 in Ubuntu 14.04

### ISSUE THREAD

**Issue by ikitaez** [xmrig/xmrig-proxy#154]
>$ cmake .
>
>-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/local/lib/libuv.a  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found MHD: /usr/local/lib/libmicrohttpd.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/x/xmrig-proxy-2.5.2

>$ make
Scanning dependencies of target xmrig-proxy
[  1%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App.cpp.o
[  3%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/Console.cpp.o
[  5%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/Config.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/ConfigLoader.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/ConfigWatcher.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/Controller.cpp.o
[ 13%] Building C object CMakeFiles/xmrig-proxy.dir/src/crypto/c_keccak.c.o
[ 15%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/AccessLog.cpp.o
[ 16%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/ConsoleLog.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/FileLog.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/Log.cpp.o
[ 22%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/ShareLog.cpp.o
[ 24%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/Client.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/Job.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/strategies/DonateStrategy.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 32%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 33%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/SubmitResult.cpp.o
[ 35%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/Url.cpp.o
/home/x/xmrig-proxy-2.5.2/src/net/Url.cpp: In constructor ‘Url::Url()’:
/home/x/xmrig-proxy-2.5.2/src/net/Url.cpp:48:24: error: incompatible types in assignment of ‘const char [1]’ to ‘char [5]’
     m_port(kDefaultPort)
                        ^
/home/x/xmrig-proxy-2.5.2/src/net/Url.cpp: In constructor ‘Url::Url(const char*)’:
/home/x/xmrig-proxy-2.5.2/src/net/Url.cpp:71:24: error: incompatible types in assignment of ‘const char [1]’ to ‘char [5]’
     m_port(kDefaultPort)
                        ^
/home/x/xmrig-proxy-2.5.2/src/net/Url.cpp: In constructor ‘Url::Url(const char*, uint16_t, const char*, const char*)’:
/home/x/xmrig-proxy-2.5.2/src/net/Url.cpp:83:16: error: incompatible types in assignment of ‘const char [1]’ to ‘char [5]’
     m_port(port)
                ^
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/net/Url.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
make: *** [all] Error 2

How to fix this? v2.4.5 is compiling fine

**Comment by xmrig** [comment]
Duplicate #152
Already fixed, pull recent changes from git.
Thank you.
