### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by TheDarknessz0rz** [xmrig/xmrig-proxy#157]
Scanning dependencies of target xmrig-proxy
[  1%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App.cpp.o
/root/xmrig-proxy/xmrig-proxy-2.5.2/src/App.cpp: In member function ‘int App::exec()’:
/root/xmrig-proxy/xmrig-proxy-2.5.2/src/App.cpp:115:36: error: ‘uv_loop_close’ was not declared in this scope
     uv_loop_close(uv_default_loop());
                                    ^
CMakeFiles/xmrig-proxy.dir/build.make:62: recipe for target 'CMakeFiles/xmrig-proxy.dir/src/App.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/App.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-proxy.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas why?

**Comment by xmrig** [comment]
libuv 0.10 not supported, use libuv 1+.
Thank you.

**Comment by TheDarknessz0rz** [comment]
Thanks, it works!
