### ISSUE TITLE
Wrong deps dir in Windows build wiki

### ISSUE THREAD

**Issue by vitorgatti** [xmrig/xmrig-proxy#159]
https://github.com/xmrig/xmrig-proxy/wiki/Windows-Build

deps dir is not correct, according to xmrig-deps-3.0 the folders **libuv** and **libmicrohttpd** don't exist anymore, all is included in the same x86 or x64 folders

sorry, can't make PRs on wiki, so posting the issue here

took me a while to realize that and understand why it wasn't compiling :P

**Comment by xmrig** [comment]
Fixed, now it much simpler, just need specify one path instead of 4.
Thank you.

**Comment by vitorgatti** [comment]
thank you!!
