### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by xc85** [xmrig/xmrig-proxy#16]
Hello. Now im use xmr-node-proxy for my workers, but it does not support dwarfpool :( so
1) xmrig-proxy support dwarfpool?
2) xmrig-proxy support other xmr miners like xmr-stak-cpu?
3) xmrig-proxy just proxy or my 100 workers is 1 for pool?

Thanks so much!

**Comment by xmrig** [comment]
1. Any pool except nicehash.com
2. Any miner with nicehash support, for xmr-stak-cpu `"nicehash_nonce" : true,` in config.txt
3. For 100 is just one connection to pool, up to 256 workers to one pool connection.
100 -> 1
256 -> 1
257 -> 2
512 -> 2
513 -> 3

**Comment by xc85** [comment]
Brilliant app, thanks!

**Comment by xc85** [comment]
and one more question...
I have some workers with 50h/s and 600h/s
if i choose pool port with fixed diff: 20000, all workers will work separately 20000 diff each or together with different diff? 

Thanks.

**Comment by xmrig** [comment]
All workers will get exactly same diff as upstream pool connection, so it will 20000 for every worker.

Some people want feature to reduce diff, but it not work as expected, it easy to tell workers more lower diff, workers will submit shares more often, can calculate more smooth and realistic hashrate for slow workers, but it not change count of 20000 shares at all, it works more like placebo.
Thank you.

**Comment by xc85** [comment]
It's true. but im using specific hardware and about 30% of my workers restart every 4 min. 
What diff do you recommend for them if the average speed is 70 h/s?

**Comment by xmrig** [comment]
keepalive option designed to prevent timeouts, but if you use xmr-stak-cpu there no such option.
Only few pools allow diff like 1000-5000 now, low diff increased pool load, about 10000 is reasonable balanced to worker/pool, but now many pools now not allow 10000 too.

I still thinking about diff reduction, but it will many questions about hashrate. Anyway if you get hundreds or thousands of workers, low diff not so much important.

**Comment by xc85** [comment]
Now I'm trying to compile libuv statically, when I get it I can use xmrig (I feel the pedant's hand, I respect it).

> I still thinking about diff reduction, but it will many questions about hashrate.
now I think it's unnecessary if it does not increase profits, "keepalive" fantastic option for that

>keepalive option designed to prevent timeouts
not quite clear how it will help if the worker restarts every 4-10 min and lost progress... hmm or there is a way to restore it...

Many thanks for the fact that you answer, % donation is guaranteed)

**Comment by xmrig** [comment]
Related issue about timeouts #7
Proxy will close connection if no jobs or keepalive received in 10 minutes, it compile time constant https://github.com/xmrig/xmrig-proxy/blob/master/src/proxy/Miner.h#L73

You can increase this value, but timeouts required to remove actually dead workers and some bad connections especially if you use ports like 80 or 443.

**Comment by xc85** [comment]
>but timeouts required to remove actually dead workers

```
server1
00:00 start worker (PID 1)
00:04 kill worker (PID 1)
00:04 start worker (PID 2)

server100500
00:00 start worker (PID 1)
00:04 kill worker (PID 1)
00:04 start worker (PID 2)
```

PID1 and PID2 on same server is different workers right, then keepalive 4m is the best choice in this case... and with diff 20000 losses will be ten times greater than diff 1000?

Sorry for my stupid questions and thanks for answers.
