### ISSUE TITLE
xmrig-proxy Ubuntu compile error

### ISSUE THREAD

**Issue by arabichousemix** [xmrig/xmrig-proxy#160]
[  2%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App.cpp.o
In file included from /root/xmrig-proxy/src/App.cpp:36:0:
/root/xmrig-proxy/src/log/Log.h:46:5: warning: identifier 'constexpr' is a keyword in C++11 [-Wc++0x-compat]
     constexpr static const char* kCL_N      = "\x1B[0m";
     ^
In file included from /usr/include/c++/5/array:35:0,
                 from /root/xmrig-proxy/src/proxy/StatsData.h:29,
                 from /root/xmrig-proxy/src/proxy/Stats.h:32,
                 from /root/xmrig-proxy/src/proxy/Proxy.h:34,
                 from /root/xmrig-proxy/src/App.cpp:38:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
/root/xmrig-proxy/src/App.cpp:48:5: warning: identifier 'nullptr' is a keyword in C++11 [-Wc++0x-compat]
     m_console(nullptr),
     ^
In file included from /root/xmrig-proxy/src/App.cpp:32:0:
/root/xmrig-proxy/src/App.h:55:37: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   void onConsoleCommand(char command) override;
                                     ^
In file included from /root/xmrig-proxy/src/App.cpp:35:0:
/root/xmrig-proxy/src/core/Controller.h:58:36: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
     void onNewConfig(Config *config) override;
                                    ^
In file included from /root/xmrig-proxy/src/App.cpp:36:0:
/root/xmrig-proxy/src/log/Log.h:46:5: error: 'constexpr' does not name a type
     constexpr static const char* kCL_N      = "\x1B[0m";
     ^
/root/xmrig-proxy/src/log/Log.h:46:5: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/root/xmrig-proxy/src/log/Log.h:47:5: error: 'constexpr' does not name a type
     constexpr static const char* kCL_RED    = "\x1B[31m";
     ^
/root/xmrig-proxy/src/log/Log.h:47:5: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/root/xmrig-proxy/src/log/Log.h:48:5: error: 'constexpr' does not name a type
     constexpr static const char* kCL_YELLOW = "\x1B[33m";
     ^
/root/xmrig-proxy/src/log/Log.h:48:5: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/root/xmrig-proxy/src/log/Log.h:49:5: error: 'constexpr' does not name a type
     constexpr static const char* kCL_WHITE  = "\x1B[01;37m";
     ^
/root/xmrig-proxy/src/log/Log.h:49:5: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/root/xmrig-proxy/src/log/Log.h:54:5: error: 'constexpr' does not name a type
     constexpr static const char* kCL_GRAY = "\x1B[90m";
     ^
/root/xmrig-proxy/src/log/Log.h:54:5: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
In file included from /root/xmrig-proxy/src/proxy/Proxy.h:33:0,
                 from /root/xmrig-proxy/src/App.cpp:38:
/root/xmrig-proxy/src/proxy/CustomDiff.h:46:31: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
     void onEvent(IEvent *event) override;
                               ^
/root/xmrig-proxy/src/proxy/CustomDiff.h:47:46: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
     inline void onRejectedEvent(IEvent *event) override {}
                                              ^
In file included from /root/xmrig-proxy/src/proxy/Stats.h:32:0,
                 from /root/xmrig-proxy/src/proxy/Proxy.h:34,
                 from /root/xmrig-proxy/src/App.cpp:38:
/root/xmrig-proxy/src/proxy/StatsData.h:89:30: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     double hashrate[6] { 0.0 };
                              ^
/root/xmrig-proxy/src/proxy/StatsData.h:90:10: error: 'array' in namespace 'std' does not name a template type
     std::array<uint64_t, 10> topDiff { { } };
          ^
/root/xmrig-proxy/src/proxy/StatsData.h:89:24: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
     double hashrate[6] { 0.0 };
                        ^
/root/xmrig-proxy/src/proxy/StatsData.h:89:30: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11
     double hashrate[6] { 0.0 };
                              ^
/root/xmrig-proxy/src/proxy/StatsData.h: In member function 'uint32_t StatsData::avgLatency() const':
/root/xmrig-proxy/src/proxy/StatsData.h:72:9: warning: 'auto' changes meaning in C++11; please remove it [-Wc++0x-compat]
         auto v = latency;
         ^
/root/xmrig-proxy/src/proxy/StatsData.h:72:14: error: 'v' does not name a type
         auto v = latency;
              ^
/root/xmrig-proxy/src/proxy/StatsData.h:73:26: error: 'v' was not declared in this scope
         std::nth_element(v.begin(), v.begin() + calls / 2, v.end());
                          ^
In file included from /root/xmrig-proxy/src/proxy/Proxy.h:34:0,
                 from /root/xmrig-proxy/src/App.cpp:38:
/root/xmrig-proxy/src/proxy/Stats.h: At global scope:
/root/xmrig-proxy/src/proxy/Stats.h:52:31: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
     void onEvent(IEvent *event) override;
                               ^
/root/xmrig-proxy/src/proxy/Stats.h:53:39: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
     void onRejectedEvent(IEvent *event) override;
                                       ^
In file included from /root/xmrig-proxy/src/App.cpp:38:0:
/root/xmrig-proxy/src/proxy/Proxy.h:75:78: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
 onConfigChanged(xmrig::Config *config, xmrig::Config *previousConfig) override;
                                                                     ^
/root/xmrig-proxy/src/proxy/Proxy.h:78:5: error: 'constexpr' does not name a type
     constexpr static int kPrintInterval = 60;
     ^
/root/xmrig-proxy/src/proxy/Proxy.h:78:5: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/root/xmrig-proxy/src/proxy/Proxy.h:79:5: error: 'constexpr' does not name a type
     constexpr static int kGCInterval    = 60;
     ^
/root/xmrig-proxy/src/proxy/Proxy.h:79:5: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/root/xmrig-proxy/src/App.cpp: In constructor 'App::App(int, char**)':
/root/xmrig-proxy/src/App.cpp:48:15: error: 'nullptr' was not declared in this scope
     m_console(nullptr),
               ^
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/App.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
make: *** [all] Error 2

Any help guys ?
Gcc version is 5.4.1

**Comment by imransheriff** [comment]
He means below like this

project(xmrig-proxy)
add_compile_options(-std=c++11)

**Comment by marcel1974** [comment]
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
elseif(COMPILER_SUPPORTS_CXX0X)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
else()
        message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()
