### ISSUE TITLE
Proxy is being Killed without any errors randomly.

### ISSUE THREAD

**Issue by SnShine** [xmrig/xmrig-proxy#162]
I'm using an Ubuntu server to run the proxy and have 4gb ram and 4gb swap. It gets 8-12 connections from miners but still gets Killed randomly. Sometimes, it gets killed every 2-3 days and sometimes it runs perfectly fine for weeks. Load is always constant between 8-12 miners. Any idea how to fix this?

Or any bash hack to start the Killed process?

**Comment by Jiablero** [comment]
Add it into the systemd with Restart=always and RestartSec=1 options

**Comment by SnShine** [comment]
Yeah, that was the issue. I have to increase the swap before getting a bigger instance.
