### ISSUE TITLE
Many results rejected pool:minexmr.com

### ISSUE THREAD

**Issue by steelrayx** [xmrig/xmrig-proxy#170]
I have many running xmrig with parameters like

```bash
xmrig.exe -o stratum+tcp://XMRIG-PROXY:1111 -u uniq_id -p x -o stratum+tcp://xmr.pool.minergate.com:45700 -u email@email.com -p x --nicehash -k --api-port 1122 --api-access-token API_TOKEN --donate-level=1
```

And proxy

```bash
/proxy/xmrig-proxy-2.5.2/build/xmrig-proxy --donate-level 1 --api-port 5559 -b 0.0.0.0:1111 -o pool.minexmr.com:5555 -u MY_XMR_WALLET -p x --variant 1
```

And i have many **REJECTED** results (50% from sended to pool)
```javascript
  "results": {
    "accepted": 133721,
    "rejected": 110332,
```

But with minergate about 0.5% rejected results

What i`m doing wrong with minexmr ?

xmrig.exe v2.5.2
xmrig-proxy v2.5.2

**Comment by xmrig** [comment]
Probably 50% of you miners not updated to v2.5. Minergate accept old algorithm for XMO or whatever.
Thank you.

**Comment by steelrayx** [comment]
> Probably 50% of you miners not updated to v2.5. Minergate accept old algorithm for XMO or whatever.
No, all miners updated, i check it.

**Comment by steelrayx** [comment]
when connected to proxy miner not updated to 2.5.2, i got a message like "YOU MUST UPGRADE YOUR MINER"

In this case i got "Invalid Share" in proxy console

**Comment by steelrayx** [comment]
```bash
[root@~]# cat fc.access.log | grep "XMRig/2.5" | wc -l
7777
[root@~]# cat fc.access.log | grep "XMRig/2.4" | wc -l
7
```

**Comment by xnbya** [comment]
For minexmr all hashes sent via a proxy must be v7. Otherwise the pool will apply v6 mitigations for the proxy connection.
