### ISSUE TITLE
How to get connected miners list through API?

### ISSUE THREAD

**Issue by SnShine** [xmrig/xmrig-proxy#172]
I'm able to get the overall hash rate and stuff at `http://local_ip:api_port`. But how to get the list of all the miners, ip address, and hash rate?

**Comment by steelrayx** [comment]
/workers.json

**Comment by ORGaniZMo** [comment]
http://local_ip:api_port/1/workers

**Comment by SnShine** [comment]
Thank you, guys. Checking both endpoints
