### ISSUE TITLE
SOCKET ERROR - [xxx.xxx.xxx.xx:3333] RECEIVE error: socket closed 

### ISSUE THREAD

**Issue by 798654350** [xmrig/xmrig-proxy#173]
cpu and network is good,but the miner client has issue often,the client vertion is xmr-stak 2.4.2

SOCKET ERROR - [xxx.xxx.xxx.xx:3333] RECEIVE error: socket closed 
All pools are dead. Idling...

**Comment by DrStein99** [comment]
I get this too.  Not sure why.  Just happens all the time and my miners have to reconnect.  I've just been ignoring it and rolling on.
