### ISSUE TITLE
Please explain Nicehash option

### ISSUE THREAD

**Issue by tarris034** [xmrig/xmrig-proxy#174]
"Nicehash support must be enabled on miner side, it mandatory."

I use xmrig-proxy to redirect traffic to supportxmr, I mine XMR using xmrig.

Why should I use Nicehash option in my xmrig miner config and/or xmrig-proxy and what does it do.

I was testing without Nicehash option and it worked.

**Comment by xmrig** [comment]
For recent versions don't need set this option by hand for xmrig miners, but if you use other miners you must set this option. Nicehash required because proxy works like nicehash.com to reduce connection count.
Thank you.
