### ISSUE TITLE
compile on CentOS 6 fails

### ISSUE THREAD

**Issue by moralrebuild** [xmrig/xmrig-proxy#176]
I get the following error when trying to compile on CentOS/RHEL 6. Anyone can give me a hand? 

/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/c++0x_warning.h:31:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.

Thanks in advance!

**Comment by moralrebuild** [comment]
After switching compiling environment to higher version (by command 'scl enable devtoolset-4 bash'), a similar issue was reported:

/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

**Comment by fix76** [comment]
https://github.com/xmrig/xmrig-proxy/issues/46

**Comment by moralrebuild** [comment]
@fix76 thanks. Actuall it's still old compiler issue and got fixed after upgrading to devtoolset-7

**Comment by moralrebuild** [comment]
Sorry, another roadblock is hitting. All compiling succeeded but linking fails:

[100%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/api/HttpRequest.cpp.o
Linking CXX executable xmrig-proxy
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/libuv.a(libuv_la-linux-core.o): undefined reference to symbol 'clock_getres@@GLIBC_2.2.5'
//lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xmrig-proxy.dir/build.make:1366: xmrig-proxy] Error 1
make[1]: *** [CMakeFiles/Makefile2:64: CMakeFiles/xmrig-proxy.dir/all] Error 2
make: *** [Makefile:76: all] Error 2

**Comment by moralrebuild** [comment]
I have it compiled successfully with dynamic link rather than the static link. Hopefully the guide in twiki can be updated, for e.g, on CentOS/RHEL 6

cmake .. -DUV_LIBRARY=/usr/local/lib/libuv.a  # failed
cmake .. -DUV_LIBRARY=/usr/local/lib/libuv.so # passed
