### ISSUE TITLE
Logging of connected/disconnected miners

### ISSUE THREAD

**Issue by RipZ** [xmrig/xmrig-proxy#18]
Add the ability to display information about connected / disconnected miners (IP addresses of miners) for a period of time. Thanks!

**Comment by xmrig** [comment]
I working on it now, information will be available via HTTP API.

**Comment by LiStopaD45** [comment]
Tell me please, how to use API. I want to monitor the mayner. @

**Comment by ORGaniZMo** [comment]
while you can use https://moneropedia.pro/%D0%92%D0%B5%D0%B1%D0%BC%D0%BE%D1%80%D0%B4%D0%B0_%D0%B4%D0%BB%D1%8F_xmrig-proxy

**Comment by LiStopaD45** [comment]
Thanks you!!!
