### ISSUE TITLE
Multi pools in bat / Несколько пулов в bat

### ISSUE THREAD

**Issue by exp10r** [xmrig/xmrig-proxy#183]
Как правильно указать несколько пулов в bat? 
Если первый не работает то на второй не переключается. так же и в xmrig.

How to specify multiple pools in bat? 
If the first does not work then the second will not be switched. the same problem in xmrig.

![2](https://user-images.githubusercontent.com/38540975/39015186-3f6e24e4-4425-11e8-8e92-e34a3e38cb4f.PNG)
![1](https://user-images.githubusercontent.com/38540975/39015187-3f96f018-4425-11e8-8976-e89c3100c76f.PNG)

**Comment by xmrig** [comment]
Use https://config.xmrig.com/proxy to generate proper command line.
Thank you.

**Comment by exp10r** [comment]
Работает, но продолжает соединяться с первым пулом.  так и должно быть ?

Works, but continues to connect to the first pool. is that right ?

![3](https://user-images.githubusercontent.com/38540975/39034682-f8f656de-447f-11e8-8105-286c1ce764dd.PNG)

**Comment by ORGaniZMo** [comment]
@exp10r yep, failover.
Да, фэйловер же.
