### ISSUE TITLE
Cannot Compile. On Ubuntu 14. 

### ISSUE THREAD

**Issue by cminatti** [xmrig/xmrig-proxy#187]
I installed the missing libuv1-dev adding this source:
add-apt-repository ppa:acooks/libwebsockets6
apt-get update
apt-get install libuv1-dev

Then, I don't even understand what the error is...

>make
[  1%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App.cpp.o
In file included from /root/xmrig-proxy/src/core/CommonConfig.h:31:0,
                 from /root/xmrig-proxy/src/core/Config.h:32,
                 from /root/xmrig-proxy/src/App.cpp:34:
/root/xmrig-proxy/src/core/utils/c_str.h:46:5: warning: identifier 'nullptr' is a keyword in C++11 [-Wc++0x-compat]
     inline c_str() : m_data(nullptr)                   {}
     ^
In file included from /root/xmrig-proxy/src/core/CommonConfig.h:33:0,
                 from /root/xmrig-proxy/src/core/Config.h:32,
                 from /root/xmrig-proxy/src/App.cpp:34:
/root/xmrig-proxy/src/net/Pool.h:38:5: warning: identifier 'constexpr' is a keyword in C++11 [-Wc++0x-compat]
     constexpr static const char *kDefaultPassword = "x";
     ^
In file included from /usr/include/c++/4.8/array:35:0,
                 from /root/xmrig-proxy/src/proxy/StatsData.h:29,
                 from /root/xmrig-proxy/src/proxy/Stats.h:32,
                 from /root/xmrig-proxy/src/proxy/Proxy.h:34,
                 from /root/xmrig-proxy/src/App.cpp:38:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
...
...
...
/root/xmrig-proxy/src/api/Httpd.h:53:5: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/root/xmrig-proxy/src/App.cpp: In constructor 'App::App(int, char**)':
/root/xmrig-proxy/src/App.cpp:48:15: error: 'nullptr' was not declared in this scope
     m_console(nullptr),
               ^
In file included from /root/xmrig-proxy/src/core/CommonConfig.h:31:0,
                 from /root/xmrig-proxy/src/core/Config.h:32,
                 from /root/xmrig-proxy/src/App.cpp:34:
/root/xmrig-proxy/src/core/utils/c_str.h: In member function 'bool xmrig::c_str::isNull() const':
/root/xmrig-proxy/src/core/utils/c_str.h:75:70: warning: control reaches end of non-void function [-Wreturn-type]
     inline bool isNull() const           { return m_data == nullptr; }
                                                                      ^
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/App.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
make: *** [all] Error 2

**Comment by pcca-matrix** [comment]
try edit your CMakeLists.txt and add -std=c++11
ex:  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wno-overloaded-virtual -std=c++11")
try compile without httpd cause ubuntu 14 don't have the last libmicrohhtpd needed

**Comment by cminatti** [comment]
Worked! Thank you. 
So, I added what you said on CMakeLists.txt line 194.
Then  did #cmake .. -DWITH_HTTPD=OFF
