### ISSUE TITLE
Reason for low efficiency

### ISSUE THREAD

**Issue by lexphor** [xmrig/xmrig-proxy#19]
When I press 'c' to get connection info, I see that I have a 10% efficiency in 'red'. why is it low? and how do I improve it.
Thanks in advance for your support.

**Comment by xmrig** [comment]
Yep, I know better rename it to ratio and don't use percents. It just numbers how pool connection utilized, 256 workers = 100%, you have about 25-26 workers so it 10% it's ok, nothing worry about.
Thank you.
