### ISSUE TITLE
"Invalid nonce; is miner not compatible with NiceHash?"

### ISSUE THREAD

**Issue by hexter2018** [xmrig/xmrig-proxy#190]
![proxy](https://user-images.githubusercontent.com/38841538/39409998-afbb8b40-4c1a-11e8-8986-29449544145b.png)

plase help me.

i set config

{
    "access-log-file": null,
    "algo": "cryptonight",
    "api": {
        "port": 9999,
        "access-token": null,
        "worker-id": null,
        "ipv6": true,
        "restricted": true
    },
    "background": false,
    "bind": [
        "172.19.100.200:8888",
        "[::]:3333"
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 1,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "url": "cryptonightv7.jp.nicehash.com:3363",
            "user": "my_wellet",
            "pass": "x",
            "variant": -1
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "user-agent": null,
    "verbose": false,
    "watch": true,
    "workers": true
}

**Comment by xmrig** [comment]
In `nicehash` mode (default) proxy can't work with nicehash.com, it possible only in `simple` mode, but in that mode proxy not reduce connection count.
Thank you.

**Comment by f0r34chb3t4** [comment]
Funciona lindo ;)
