### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by Meyer01** [xmrig/xmrig-proxy#191]
Hello
Explain please how the donation works. 
If number of miners are <=265 then there is no donation at all. But when there is 257 miners what happens? Donations are running from all miners?
I cant found what to change in the code to start donations if the miners number is less than 256.
Thank you

**Comment by xmrig** [comment]
> If number of miners are <=265 then there is no donation at all.
> Donations are running from all miners?

In recent dev version exactly right, code is https://github.com/xmrig/xmrig-proxy/blob/dev/src/net/strategies/DonateStrategy.cpp#L120

For current versions, donation may start with lower miners count, if proxy create more that one upstream. Anyway if you use xmrig miners, better enable it on miner side and disable on proxy.

In next versions donation may complete removed, but added ability to use proxy connection for donations directly from miners, without extra connections.
Thank you.

**Comment by Meyer01** [comment]
I have changed statsData().upstreams.active == 1 to ==0, set donation level for test to 99 in config file but nothing happens. 2 miners connected to proxy, but i didn't see connectoins from proxy to proxy.fee.xmrig.com. Only to pool in config.

if (m_ticks == m_target) {
        if (m_id == 0 && m_controller->statsData().upstreams.active == 0) {
            m_target += 600;
            return;

**Comment by Meyer01** [comment]
Another problem... Donation starts only once and not resheduled. Sometimes donation starts and never ends. Sometimes starts working needed time then stops and never starts again.

**Comment by akhmad112** [comment]
apa yang terjadi jika saya merubah donate level menjadi 99% di xmrig wizard?
