### ISSUE TITLE
Proxy to proxy connection

### ISSUE THREAD

**Issue by Meyer01** [xmrig/xmrig-proxy#193]
Hello
I'm planning to use 2 proxy configuration. 1 proxy is in internet, second in local network.
All proxies are last version without modifications.
Client is also last version without modifications.
Mining pool is supportxmr.com
If i'm connecting client to outside proxy and proxy connected to pool everything is ok
If im connecting client to local proxy and proxy connected to pool everything is ok
But when i'm connecting client to local proxy and local proxy connected to outside proxy and outside proxy is connected to pool there is a problem:
all shares are rejected by local proxy and connection to outside proxy drops.
Messages are on client and on local proxy. On outside proxy there are no errors.
In config file of local proxy i'm changing only pool address.
Screen from local proxy^
![proxy2](https://user-images.githubusercontent.com/36437117/39620551-3b873288-4f94-11e8-85d3-0048d8b56cf3.JPG)

Screen from client:
![miner](https://user-images.githubusercontent.com/36437117/39620574-548c7e00-4f94-11e8-9c2f-c14f91dff8d8.JPG)

**Comment by xmrig** [comment]
Please check https://github.com/xmrig/xmrig-proxy/issues/118#issuecomment-375172833 in short one proxy should run in `nicehash` mode, one in `simple` mode.
Thank you.

**Comment by Meyer01** [comment]
Thank you! you are the best!
