### ISSUE TITLE
Cannot Compile. On centos 6

### ISSUE THREAD

**Issue by MouseWhite** [xmrig/xmrig-proxy#196]
Scanning dependencies of target xmrig-proxy
[  1%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App.cpp.o
[  3%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/config/CommonConfig.cpp.o
[  5%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/config/ConfigLoader.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/config/ConfigWatcher.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/Console.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/crypto/Algorithm.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/crypto/keccak.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/ConsoleLog.cpp.o
[ 16%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/FileLog.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/Log.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/Client.cpp.o
[ 22%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/Job.cpp.o
[ 24%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/Pool.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/strategies/FailoverStrategy.cpp.o
[ 27%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/strategies/SinglePoolStrategy.cpp.o
[ 29%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/SubmitResult.cpp.o
[ 31%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/Platform.cpp.o
[ 33%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/Config.cpp.o
[ 35%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/Controller.cpp.o
[ 37%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/AccessLog.cpp.o
[ 38%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/ShareLog.cpp.o
[ 40%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/JobResult.cpp.o
[ 42%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/strategies/DonateStrategy.cpp.o
[ 44%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Counters.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/CustomDiff.cpp.o
[ 48%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Error.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Events.cpp.o
[ 51%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/events/Event.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/events/MinerEvent.cpp.o
[ 55%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Login.cpp.o
[ 57%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Miner.cpp.o
[ 59%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Miners.cpp.o
[ 61%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Proxy.cpp.o
[ 62%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/ProxyDebug.cpp.o
[ 64%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Server.cpp.o
[ 66%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/nicehash/NonceMapper.cpp.o
[ 68%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/nicehash/NonceSplitter.cpp.o
[ 70%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/nicehash/NonceStorage.cpp.o
[ 72%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/simple/SimpleMapper.cpp.o
[ 74%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/simple/SimpleSplitter.cpp.o
[ 75%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/Splitter.cpp.o
[ 77%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Stats.cpp.o
[ 79%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/workers/Worker.cpp.o
[ 81%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/workers/Workers.cpp.o
[ 83%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/Summary.cpp.o
[ 85%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/xmrig.cpp.o
[ 87%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App_unix.cpp.o
[ 88%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/Platform_unix.cpp.o
[ 90%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Uuid_unix.cpp.o
[ 92%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/SysLog.cpp.o
[ 94%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/api/Api.cpp.o
[ 96%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/api/ApiRouter.cpp.o
[ 98%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/api/Httpd.cpp.o
[100%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/api/HttpRequest.cpp.o
Linking CXX executable xmrig-proxy
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /share/udata3/hujh/Programs/libuv/lib/libuv.a(libuv_la-linux-core.o): undefined reference to symbol 'clock_getres@@GLIBC_2.2.5'
//lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [xmrig-proxy] Error 1
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
make: *** [all] Error 2

**Comment by Ronnier33** [comment]
add cmake options -DCMAKE_EXE_LINKER_FLAGS=-lrt
