### ISSUE TITLE
2.6 workers list not correct

### ISSUE THREAD

**Issue by pcca-matrix** [xmrig/xmrig-proxy#197]
on  2.6 is this normal all workers is grouped into single users in worker list and no adress is displayed ?? 

all seem to be grouped with IP of router gateway.

Sometime 2 users is displayed with another ip but with many connection to  it too.

ex: "workers":[["","10.10.0.155",68,325,0,0,9857117,1525600723719,0,1.1,2.35,8.22,6.11]],

if i go back to 2.5.x all workers is displayed as expected.

**Comment by xmrig** [comment]
What miners do you use? please show configs.
Thank you.

**Comment by pcca-matrix** [comment]
All miners have  xmr-stak 2.4.2

xmr-stak config

{"pool_address" : "xxxxx", "wallet_address" : "xxxxxx.rig1", 
	 "rig_id" : "","pool_password" : "x", "use_nicehash" : true, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 3 },

xmrig-proxy config

{
    "access-log-file": "",
    "algo": "cryptonight",
    "api": {
        "port": 8000,
        "access-token": "xxxx",
        "worker-id": "Main",
        "ipv6": false,
        "restricted": false
    },
    "background": false,
    "bind": [
        "0.0.0.0:8555",
        "[::]:8555"
    ],
    "colors": true,
    "custom-diff": 95000,
    "donate-level": 2,
    "log-file": "",
    "mode": "nicehash",
    "pools": [
        {
            "url": "de.minexmr.com:7777",
            "user": "xxxxx",
            "pass": "x",
	    "rig-id": null,
            "keepalive": true,
            "variant": -1
        },
        {
            "url": "grft.easyhash.io:3831",
            "user": "xxxxxx",
            "pass": "x",
	    "rig-id": null,
            "keepalive": true,
            "variant": -1
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "user-agent": "",
    "verbose": true,
    "watch": true,
    "workers": true
}

Thanks

**Comment by pcca-matrix** [comment]
After some try  it only have rig-id in place of address  if it is defined in xmr-stak pool config.
 if not defined , address is empty  so all miner is grouped as one with many connections.

**Comment by xmrig** [comment]
Fix released in [v2.6.2](https://github.com/xmrig/xmrig-proxy/releases/tag/v2.6.2).
Thank you.

**Comment by kim0** [comment]
@xmrig .. Thanks for the fix. I just want to be clear I understand how it should work.

* If rig_id is specified, it is used in the API to identify workers. Wallet (username) is never used
* If not specified, wallet address is used like the old mode.

My problem is, if rig_id is specified, is there a way to identify that multiple rigs are related to a single wallet ? or no
