### ISSUE TITLE
Donation 2.6.0

### ISSUE THREAD

**Issue by Meyer01** [xmrig/xmrig-proxy#199]
Hello
Version 2.6.0
I have changed line 119 in donation.cpp to  if (Counters::miners() < 1) {
But donation didn't start after m_target time.
What else do i need to change to start donations if miners >0
Thank you

**Comment by Meyer01** [comment]
![proxy2 6 0](https://user-images.githubusercontent.com/36437117/39703184-e1346386-520f-11e8-9681-7aed0918adb6.JPG)

Something strange happens when donation starts

**Comment by xmrig** [comment]
I hope now all bugs fixed. Also now don't need edit `DonateStrategy.cpp`, all you need now in `donate.h` https://github.com/xmrig/xmrig-proxy/blob/master/src/donate.h#L46
Thank you.

**Comment by Meyer01** [comment]
Yes, now it works. But donation starts only once. I think that reschedule() doesnt work.

**Comment by Meyer01** [comment]
Everything works fine! Thank you!

**Comment by xmrig** [comment]
Fix released in [v2.6.2](https://github.com/xmrig/xmrig-proxy/releases/tag/v2.6.2).
Thank you.
