### ISSUE TITLE
Dev version works?

### ISSUE THREAD

**Issue by Omnividente** [xmrig/xmrig-proxy#20]
Can i try dev version? If yes, where i can see instruction?

**Comment by Omnividente** [comment]
i try compiled 
`cmake .. -G "Visual Studio 14 2015 Win64" -T v140_xp -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR=C:\libuv64\include -DUV_LIBRARY=C:\libuv64\libuv.lib -DMHD_INCLUDE_DIR=c:\x86_64\VS2015\Release-static\ -DMHD_LIBRARY=C:\x86_64\VS2015\Release-static\libmicrohttpd-dll.lib`
`msbuild xmrig-proxy.sln /p:Configuration=Release`
but i get error

```
"c:\xmrig-proxy-dev\build\xmrig-proxy.sln" (целевой объект по умолчанию) (1) ->
"c:\xmrig-proxy-dev\build\xmrig-proxy.vcxproj.metaproj" (целевой объект по умолчанию) (5) ->
"c:\xmrig-proxy-dev\build\xmrig-proxy.vcxproj" (целевой объект по умолчанию) (6) ->
(Link конечный объект) ->
  LINK : fatal error LNK1181: эх єфрхЄё  юЄъЁ√Є№ тїюфэющ Їрщы "C:\x86_64\VS2017\Release-static\libmicrohttpd-dll.lib" [
c:\xmrig-proxy-dev\build\xmrig-proxy.vcxproj]
```

**Comment by djfinch** [comment]
Try to compile with this static libmicrohttpd...
https://github.com/xmrig/xmrig-deps/releases/tag/v2
Last time I tried it I got this error too. See this... (but with nvidia)
https://github.com/xmrig/xmrig-nvidia/issues/10
Seems DEV WITH_HTTPD is broken...

**Comment by xmrig** [comment]
`-DWITH_HTTPD=OFF` should be fixed now.

**Comment by kent9876** [comment]
Anyone have a solution?
