### ISSUE TITLE
Error compiling in windows

### ISSUE THREAD

**Issue by Omnividente** [xmrig/xmrig-proxy#205]
`App.obj : ?????? .netmodule MSIL ??? ??????, ???????????????√? ? ?????????? /GL; ??????????????  ?????????? ? ???????
  ??? /LTCG; ???????? /LTCG ? ????????■ ?????? ?????????? ??  ???√°???  ?????????????????? ????????∙???
LINK : fatal error C1007: ?????????√? ???? "-Ot" ? "p2" [c:\xmrig-proxy-2.6.2\build\xmrig-proxy.vcxproj]
LINK : fatal error LNK1257: ?? ??????? ??????? ??? [c:\xmrig-proxy-2.6.2\build\xmrig-proxy.vcxproj]
Done Building Project "c:\xmrig-proxy-2.6.2\build\xmrig-proxy.vcxproj" (default targets) -- FAILED.

Done Building Project "c:\xmrig-proxy-2.6.2\build\xmrig-proxy.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "c:\xmrig-proxy-2.6.2\build\xmrig-proxy.sln" (default targets) -- FAILED.

Build FAILED.

"c:\xmrig-proxy-2.6.2\build\xmrig-proxy.sln" (default target) (1) ->
"c:\xmrig-proxy-2.6.2\build\xmrig-proxy.vcxproj.metaproj" (default target) (3) ->
"c:\xmrig-proxy-2.6.2\build\xmrig-proxy.vcxproj" (default target) (4) ->
(Link target) ->
  LINK : fatal error C1007: ?????????√? ???? "-Ot" ? "p2" [c:\xmrig-proxy-2.6.2\build\xmrig-proxy.vcxproj]
  LINK : fatal error LNK1257: ?? ??????? ??????? ??? [c:\xmrig-proxy-2.6.2\build\xmrig-proxy.vcxproj]

    0 Warning(s)
    2 Error(s)`

**Comment by eeeeLeeee** [comment]
how did you fix it?
