### ISSUE TITLE
support for haven new fork 

### ISSUE THREAD

**Issue by adiangga** [xmrig/xmrig-proxy#208]
haven has forked to v2, it seems that xmrig-proxy not yet support that. i tried using "--variant 1" or "--variant -1" the shares are rejected. please support for haven new fork

**Comment by xmrig** [comment]
For Haven use ` "algo": "cryptonight-heavy",` on both proxy and miner side.
Thank you.

**Comment by adiangga** [comment]
i have wrote that on both miner and proxy, but still rejected. what --variant i should use?

**Comment by xmrig** [comment]
Make sure you use v2.6+, only `algo` option is enough, `variant` not used for `cryptonight-heavy`, this algorithm has no variants. More information about algorithms and variants https://github.com/xmrig/xmrig/blob/master/doc/ALGORITHMS.md
Thank you.
