### ISSUE TITLE
SOCKET ERROR - CALL error: Timeout while waiting for a reply

### ISSUE THREAD

**Issue by seawalk24** [xmrig/xmrig-proxy#210]
I have 3 miners at home and 3 miners at the office. The miners at home never have any problems. The miners at the office occasionally have the error "SOCKET ERROR - CALL error: Timeout while waiting for a reply." It will connect to another pool for a few minutes before returning to the proxy.  

All of the miners have the same hash rate and are configured the same way. The only thing different is that half of the miners are in a different physical location. I have this error with all 3 miners at the office but never with any of the miners at home. 

I am using XMRig Proxy 2.6.2 with XMR-Stak 2.4.3. The proxy is hosted on Amazon AWS.

**Comment by xmrig** [comment]
Amazon AWS or ports you use may blocked in your office also Amazon has firewall but if half of the miners works ok, looks like all fine with this part.
Thank you.
