### ISSUE TITLE
A way to disable the new algo negotiation

### ISSUE THREAD

**Issue by MigzuASD** [xmrig/xmrig-proxy#214]
Is there a way to disable the new algorithm negotiation protocol? I have a different solution to the same problem, and it works fine with versions older than v2.6.0. Now the proxy seems to reject my shares as it thinks the algo is wrong.

The algo however is right for the pool, but the proxy does not even send it upstream. I've tried to remove the algo and variant options from the confs to disable the checking, but this did not help. My old solution changes the proxy port based on the algo, and the miners know what algo means what port. This works fine, so I really dont want to have to reconfigure the proxy algo everytime I switch.

**Comment by xmrig** [comment]
Please show your configs or provide more details, also please note if you want mine algorithms with different memory requirements you must restart miners too.
Thank you.

**Comment by MigzuASD** [comment]
So I have this script to follow the profitabilities of different CN-coins. When the script decides that we should switch coin, It rewrites the xmrig-proxy conf with different pool infomation and sets it to a specific port and then restarts the proxy.

The miners are are running a bash script with a loop to try the known ports one by one until it finds the one proxy is answering. Every port is tried with a different algorithm for the miner software. If the software does not get connection, It dies and the loop moves to the next line. (The miner software is conffed for 0 retry and no backup pool).

So the situation is that the proxy does not have to know the algorithm. The miners know the right one and the proxy upstream pool is the right one. With version 2.5.3 I have "algo": "cryptonight" and "variant": -1, and everything works fine. cnh, cn7, cnl, aeon7, ipbc. The proxy does not seem to care what I throw at it, everything gets sent to the upstream pool just fine.

Now with the latest version miners report rejected shares, but the proxy log does not show anything. When the pool rejects the shares, the proxy shows that. Hence, I presume the proxy rejects those shares because they are on the "wrong algo"

**Comment by xmrig** [comment]
You are right proxy don't really care what algorithm used, but for example if you use xmrig 2.5 as miner you can't mine `cn-heavy` or `cn-lite/ipbc` because it not supported by miner. 6 mounts ago situation was much simpler, please check https://github.com/xmrig/xmrig/issues/482 (it not full list for now).

**Comment by MigzuASD** [comment]
I am aware of all the different algos and coins. I just need a way to make
the proxy accept everything and leave the validation up for the pool (the
algo management is my problem, not the proxy's). It did accept everything
on 2.5.3.



pe 25. toukokuuta 2018 klo 17.26 xmrig <notifications@github.com> kirjoitti:

**Comment by xmrig** [comment]
Remove 2 checks https://github.com/xmrig/xmrig-proxy/blob/master/src/proxy/Login.cpp#L88 and https://github.com/xmrig/xmrig-proxy/blob/master/src/proxy/splitters/nicehash/NonceMapper.cpp#L139
