### ISSUE TITLE
simple mode worker id <> pool

### ISSUE THREAD

**Issue by abenhamo** [xmrig/xmrig-proxy#215]
Hello, 
currently in simple mode he pool will send a total diff corresponding to all rigs to each rig.
for example if you have 10 rigs, with 6000hash/s each, each rig will receive a diff of 1millions instead of 100k. This is because there is no rigid/login is sent from the proxy to pool.
What is needed is to send the name of worker to the pool in simple mode so:
10 rigs> proxy > 10 Clients in pool side with different names so the pool can assign different diff to each rig.
Thanks

**Comment by DrStein99** [comment]
I use nicehash mode.  For each rig in the USER field, is the workerName+difficulty;

`            "user": 		"workerName+20000",`

each rig (or worker) attach to the proxy and defines it's own difficulty level.  The proxy attach to pool at it's own difficulty level, merged with all my workers.

**Comment by abenhamo** [comment]
Hello  DrStein99, Thank you very much for this reply.
I mine mainly on fairpool which doesn't support static diff.
the only solution for me is simple mode + the feature I have suggested above.
Thanks
