### ISSUE TITLE
sighup make xmrig-proxy stop

### ISSUE THREAD

**Issue by zhezh** [xmrig/xmrig-proxy#217]
Hi,

I am using xmrig-proxy/2.6.2 libuv/1.20.3 gcc/5.4.0

I run xmrig-proxy with `nohup ./xmrig-proxy &` through ssh,

However, after a few minutes I exit ssh, the proxy stop to work, the information is as below:

[2018-05-29 15:06:34] SIGHUP received, exiting

How can I make sure this proxy run in background without being stopped?

Thanks!

**Comment by zhezh** [comment]
I write a sh file and put commands in it, it works now without being affected by sighup

**Comment by snipeTR** [comment]
hi;
please sheare .sh file
