### ISSUE TITLE
QUESTION: Regarding AEON hard fork.

### ISSUE THREAD

**Issue by TheDarknessz0rz** [xmrig/xmrig-proxy#218]
Will xmrig-proxy still work with the upcoming AEON hard fork?

**Comment by browolf** [comment]
Yes. I'm using it currently with AEON.

**Comment by TheDarknessz0rz** [comment]
Confirmed does work after the rebase, with the latest version of xmrig-proxy, make sure you set the variant to 1 under the pool configuration, and you'll be all minty.
