### ISSUE TITLE
Setup and info afte

### ISSUE THREAD

**Issue by joksa** [xmrig/xmrig-proxy#219]
Hi.
I am running 40 PCs with 50% of CPU and 20 XEON Servers with about 70% of CPU through one of 3 xmrig-proxy.
So far hashrate is bouncing between 3KH au to 4.5KH (and I can live with that)

Proxy config is setup to run in background, if I want to see I change parameter but it still no log on screen. Question is how to change config (background  true/false) and pop up proxy info. I connect 4-5 times a day to server to check this.
Also there is no easy way to restart proxy on Linux, I have to kill pors 3333, 3334 (I know for config reload), but I want to completely stop and start so I can see it in foreground
I run all proxy-s on Ubuntu 16 x64 version is latest 2.6.2 on all miners are at latest version for Windows..

Currently proxy server config is:

**{
    "access-log-file": null,
    "algo": "cryptonight",
    "api": {
        "port": 3334,
        "access-token": "token121",
        "worker-id": null,
        "ipv6": false,
        "restricted": false
    },
    "background": true,
    "bind": [
        "0.0.0.0:3333"
    ],
    "colors": true,
    "donate-level": 1,
    "log-file": "xmrig-log.txt",
    "debug": true,
    "pools": [
        {
            "url": "pool.supportxmr.com:5555",
            "user": "345SACzATRGthQAgzRuig4eGpDNZQwJsdHGWiFFLBS1ps2AF6Jomh8rd1Xh3msbfY8yDCk1FmfMAUJK77ivvVfBWFAACVFDFM+10000",
            "pass": "SRV123:email@gmail.com",
            "keepalive": true,
            "variant": -1
        }    ],
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "verbose": true
}**

**Comment by snipeTR** [comment]
install for ubuntu htop.
run htop and press f4 and write xmrig push f9 and enter. kill al proxy process to fast.

**Comment by joksa** [comment]
Confirm. Works like a charm :+1: 
It's a bit of work to stop and start but it's ok,
sometimes I like to watch how 53 workers "attack" proxu :-)

**Comment by marki555** [comment]
Why not run it in foreground mode in a `screen` or `tmux` session?

**Comment by snipeTR** [comment]
I use export proxy.log and use lnav.
Im looking realtime wach miner.
