### ISSUE TITLE
which, proxy mode, nicehash or simple

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig-proxy#221]
Can someone give detailed information for these three modes?
1) What are the differences between each other?
2) Which is the most advantageous in terms of pool?
3) Which is the most advantageous in terms of miner?
4) spending the least amount of system resources?

**Comment by xmrig** [comment]
1. https://github.com/xmrig/xmrig-proxy/issues/118#issuecomment-375172833
2. nicehash better for pool, less connections.
3. No difference for modern miners, but for nicehash it should be enabled on miner side too (for xmrig it enables automatically), if your miner not support nicehash you can use only simple mode.
4. Same as 2.

Actually modes only 2, `nicehash` and `simple`. simple mode only added for special edge cases.
Thank you.

**Comment by snipeTR** [comment]
Thank you for your reply.
I understood very well what they said. I read the link you wrote.

but there is a part I do not understand.
"mode positive values" i dont understant [json ["mode": 1,]]
exactly how this mode works.
