### ISSUE TITLE
Proxy to Multi pool  :question

### ISSUE THREAD

**Issue by julvir** [xmrig/xmrig-proxy#222]
Hi, can i put in my config more then 1 pool ? if some problem come to this pool to connect to next one ? 

Br

**Comment by xmrig** [comment]
Sure, `pools` option in config it a JSON array, you can add multiple pools if JSON format complicated for you you can use https://config.xmrig.com/proxy.
Thank you.

**Comment by julvir** [comment]
Thank you !
