### ISSUE TITLE
Management panel

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig-proxy#223]
I'm using proxy under Linux. Running in background mode. It's hard to manage this way. You have to turn it on and off every time.

Other web-based front side interfaces are useless.

That's why; It must be in its own  "web-based "  "administration panel ".
This interface will be managed on the Xmrig-proxy.

These are the qualities I expect.
1-Log output should appear in real time.
2-xmrig-proxy settings config. json file should be edited.
3-Xmrig-proxy statistics should be seen in real time.
4-System load and hardware resource information should be seen.
5-(optional) Nice graphics would be good.

**Comment by joksa** [comment]
I agree.
I think it even enough to have full supported API and someone will make web interface and share with the rest of us.

**Comment by lisergey** [comment]
I'm thinking of making such webface to xmrig-proxy using requests via API.
Any ideas and suggestions would be very helpfull.
