### ISSUE TITLE
Question : Custom diff or +xxxx in pool address 

### ISSUE THREAD

**Issue by julvir** [xmrig/xmrig-proxy#227]
Hello 

i run Xmrig proxy and i have users with low end CPU , ( mobile phones ) and before i use supportXMR as pool , the difficulty was 5000 , and many users disconnect before manage make it, so , i want try one pool with 1000 as difficulty , 

so , i have connect now to XMRpool.net ... 

and in my config file i try put  : "custom-diff": "1000",

but .. some users not make share with 1000 , but now is even worth like 45000 or even 70 000 ... 
it's very strange 

i have a question , if i use "custom-diff": "1000",  i can connect to pool with diff 5000 ? and proxy will manage with users to make share of 1000 ? 

thank you

**Comment by joksa** [comment]
I have the samo question.
Servers with XEON cpus can handle much more then regular celeron/i3 Cpus,
so diff is metter

**Comment by marki555** [comment]
`custom-diff` in config file is for clients. Clients (miners) will submit shares to the proxy with this diff.
Diff from pool to proxy is different thing (on some pools can be also made custom by suffixing it in username/address).

When `custom-diff` is for example 1000 and diff from pool is 15000, miners will send >1000 diff shares to proxy so their connection won't timeout. However proxy will forward to pool only those shares which have >15000 diff.
