### ISSUE TITLE
Error with latest 2.4.0

### ISSUE THREAD

**Issue by seblucas** [xmrig/xmrig-proxy#23]
I use your proxy to mine Aeon with [this pool](https://aeon.sumominer.com) and after 2 or 3 minutes I got this error : 

```
xmrig-proxy: /root/src/xmrig-proxy/src/3rdparty/rapidjson/document.h:1053: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>; Encoding = rapidjson::UTF8<char>; Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>]: Assertion `false' failed.
Aborted
```

I just build the sources from your latest version (2.4.0) : this commit precisely 1e30256dc24f90f35ca8c901634b26040102e7bc

Thanks in advance for any help ;)

**Comment by seblucas** [comment]
I forgot to precise but there was no error with 2.3.0 so it's should be a regression.

**Comment by xmrig** [comment]
In version 2.4 I replaced libjansson to rapidjson, so it definitely a regression.
Now should be ok, but I can't reproduce it what miner did you use?
Thank you.

**Comment by seblucas** [comment]
I use xmrig ;)

**Comment by xmrig** [comment]
Okay, anyway now anything should work fine.
Thank you.
