### ISSUE TITLE
Algorithm Conflict in Proxy Chaining

### ISSUE THREAD

**Issue by varunj** [xmrig/xmrig-proxy#232]
I am trying to connect a number of machines to proxy p1 which is connected to proxy p2 which is connected to the internet/pool.

The configuration file at p1 is
![p1](https://user-images.githubusercontent.com/8525075/41657161-19d3cd40-74b0-11e8-960f-a5a77b3c9b80.PNG)

and the command to run proxy at p2 is 
![p2](https://user-images.githubusercontent.com/8525075/41657287-80cec432-74b0-11e8-9fbe-cbd7c5e60aaa.PNG)

However I am greeted by this error at p1
![capture](https://user-images.githubusercontent.com/8525075/41657188-2e3738b2-74b0-11e8-8613-76bbc4df375d.PNG)

There are no errors at p2. Could you please guide me as to why the default algorithm (cryptonight) is causing problems?

Cheers!

**Comment by xmrig** [comment]
On p2 add option `--variant 1`, after that chain should work.
If you update p1 proxy to v2.6.3 you can also use variant `-1` (automatic).
Thank you.

**Comment by varunj** [comment]
Yup, it works now.
Thanks for the prompt reply.

Cheers!
