### ISSUE TITLE
Can't get xmrig-proxy to work

### ISSUE THREAD

**Issue by Abbas12345678** [xmrig/xmrig-proxy#233]
It simply gives the following error:
[pool name]DNS Error: Unknown node or service

Kindly suggest any solutions as I want to use my PC for mining which connected to the internet through proxy server. I've the DNS address and the IP assigned to my PC by the proxy server. What should I do?

**Comment by omurad** [comment]
The DNS server listed on the proxy might be bad. Try using 8.8.8.8 & 8.8.4.4 (Google's DNS) instead.

On Windows this can be done by going to `Control Panel -> Network and Internet -> Network and Sharing Center -> Change adapter settings -> double click your interface -> Properties -> IPv4 -> Enter the 2 addresses in the "use the following DNS server addresses"`
