### ISSUE TITLE
Does support BitTube (ipbc) now PoW algorithm

### ISSUE THREAD

**Issue by eddiewang927** [xmrig/xmrig-proxy#238]
Hi

BitTube (ipbc) will hard fork on block 110,000 and switch to unique CN Saber algorithm
Does xmrig-proxy support CN Saber?

Thanks

**Comment by xmrig** [comment]
`cn-heavy/tube` added to v2.6.4.
@Bendr0id `cn/xao` and `cn/rto` should work fine with your miner.

**Comment by Bendr0id** [comment]
@xmrig  yes works. Thanks.

Feel free to to integrate my cn-heavy/tube code. It's basically cn-heavy+monerov7+ipbc+softaes
