### ISSUE TITLE
what happens if miner doesn't support nicehash?

### ISSUE THREAD

**Issue by rinaldohack** [xmrig/xmrig-proxy#24]

**Comment by dorimanx** [comment]
Then you cant use this proxy.

**Comment by rinaldohack** [comment]
But the miner still connect and mine! 
Hmm ... 

You have plan to compile xmrig for 32 bit system?

**Comment by xmrig** [comment]
1. Miner successfully connect to proxy.
2. First submitted share will be rejected with message **Invalid nonce; is miner not compatible with NiceHash?**
3. Proxy close connection.

xmrig automatically detects nicehash is most cases (255 of 256), so explicitly specify nicehash option still required.
Thank you.

**Comment by agisubagio** [comment]
i have 13 miners and i want to connect to nicehash using xmrig and xmrig-proxy? is that posible? 
is this setting is right? xmrig miners pointing to -> xmrig-proxy pointing to -> nicehash

**Comment by SwInGeR** [comment]
Hello, i have some problem
In xmrig-proxy ver 2.4.2 use xmrig and xmrig-amd (up to day), but all share show in miner and proxy:
[2017-11-09 22:18:39] #000 rejected (0/1+3) diff 100001 "Invalid nonce; is miner not compa
tible with NiceHash?" (133 ms)

config "nicehash=true" enable in the miner.
in the proxy:    "bind": [       "127.0.0.1:3333" ]
 
What wrong?

**Comment by PhatWheZ** [comment]
Hi guys,

I have tried the same thing.
Sadly NiceHash itself is a proxy onto the Cryptonight stratum and the
protocol only allows for one proxy to be allowed.
The best that you can do is to use xmrig > xmrig-proxy > (nanopool,
xmrpool, electroneum, etc)

This was closed in a previous note
