### ISSUE TITLE
xmr-stak (monero7) + xmrig-proxy, rejected results

### ISSUE THREAD

**Issue by newUser1234567890** [xmrig/xmrig-proxy#244]
Hi,

I am trying to use xmr-stak with xmrig-proxy in a pool which does not use nicehash (can I add the pool? I wasn't sure if it is spam)

This is my config file for xmr-stak (pool.txt):

> "pool_list" :
> [
>         {"pool_address" : "127.0.0.1:3333", "wallet_address" : "<my_wallet_addr>.user1", "rig_id" : "", "pool_password" : "", "use_nicehash" : true, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
> ],
> "currency" : "monero7",
> 

This is my config for xmrig-proxy:

> {
>     "access-log-file": "access_log.txt",
>     "algo": "cryptonight",
>     "api": {
>         "port": 0,
>         "access-token": null,
>         "worker-id": null,
>         "ipv6": false,
>         "restricted": true
>     },
>     "background": false,
>     "bind": [
>         "0.0.0.0:3333"
>     ],
>     "colors": true,
>     "donate-level": 0,
>     "log-file": "log.txt",
>     "pools": [
>         {
>             "url": "<my_pool>:7777",
>             "user": "<my_wallet_addr>.pool",
>             "pass": "x",
>             "keepalive": true,
>             "variant": -1
>         }
>     ],
>     "retries": 2,
>     "retry-pause": 1,
>     "syslog": false,
>     "verbose": true
> }
> 

With this configuration the client connects correctly to xmrig-proxy, but it outputs:
> [2018-07-04 11:34:33] : Result rejected by the pool. 

Any help to fix this? Thank you

**Comment by xmrig** [comment]
Try set `"variant": 1`. If it not help please feel free add pool address too.
Thank you.

**Comment by newUser1234567890** [comment]
That fixed it, thank you!
