### ISSUE TITLE
Program cannot run

### ISSUE THREAD

**Issue by rabbit168** [xmrig/xmrig-proxy#246]
![image](https://user-images.githubusercontent.com/9463581/43695429-3f3bac9e-996b-11e8-9f2f-2c5a4d30da91.png)
My operating system is Windows x64 architecture
When I compile with good vs2017 compiled after the project, I copy the other three  files. The config.json, ibuv. dll, start. cmd to build folder.
 When I click on xmrig. exe or start. cmd, program cannot run, What reason is this excuse me?

**Comment by xmrig** [comment]
1. Wrong place to this issue, it's xmrig-proxy repository.
2. If you follow build instructions https://github.com/xmrig/xmrig/wiki/Windows-Build#microsoft-visual-studio-2017 xmrig.exe don't require additional dll files.
3. What is can't run, any error message? etc.
