### ISSUE TITLE
What's the best pool for xmrig cpu mining (monero)?

### ISSUE THREAD

**Issue by lukacci** [xmrig/xmrig-proxy#249]
Hi, i personally like nanopool for mining monero.
I want to know it makes a difference or not, selecting large or small pools with xmrig cpu mining ?

**Comment by ofranx** [comment]
lukacci havuz olayı değilde senin sistemi kurdum gayet güzel çalışıyor usbler sanırım güncelleme için gerekli 
usb olmadan da çalışıyor sistem sormak istediğim hiçbir cpu gpu hdd değerlerinde hiçbir kasma yok cok iyi bir yazılım yapmışsın bunu google cloud sunucuna da yapabilirmiyiz nerdeyse izi takip edilemeyen birşey yapmışsın buradan yazmamın sebebi sana ulaşak bir yol yok 

birde binance pump bot hakkında biraz daha bilgi verirmisin çalıştırdım ama her hangi birşey yakalamadı

**Comment by lukacci** [comment]
@ofranx olumlu görüşlerin için teşekkürler. 
- Google Could'lara eklenebilir. 
- Binance pump botu Binance üzerinde yapılan pumplarda hızlı alış ve satış işlemleri için kullanılıyor. Haberleri yakalamak için listing botu kullanılabilir. 
Projelerin kendi github sayfaları var issues sayfalarına (örneğin https://github.com/lukacci/cpuhunter/issues) yazabilirsin ordan yanıtmalaya çalışırız.
