### ISSUE TITLE
Please 2 decimal places in API hashrate

### ISSUE THREAD

**Issue by MarioPeh** [xmrig/xmrig-proxy#25]
Thank you.

**Comment by xmrig** [comment]
You mean something like `1.23` instead of `1.2`?
Thank you.

**Comment by MarioPeh** [comment]
Yes

[
            "X",
            "X",
            1,
            4,
            0,
            0,
            125550,
            1507190054916,
            **0.05,
            0.05,
            0.05,
            0.05,**
            **0.05**
        ]

**Comment by xmrig** [comment]
Done.

**Comment by MarioPeh** [comment]
Thank you
very fast :)
