### ISSUE TITLE
Bad performance: Invalid nonce; is miner not comp

### ISSUE THREAD

**Issue by MoneroCrusher** [xmrig/xmrig-proxy#250]
I ran xmrig-proxy with Version: xmr-stak 2.4.7 c5f0505 and got terrible performance

```
Difficulty       : 1000225
Good results     : 214 / 343 (62.4 %)
Avg result time  : 133.0 sec
Pool-side hashes : 43009675

Top 10 best results found:
|  0 |        531569035 |  1 |        209536942 |
|  2 |         69814151 |  3 |         60622539 |
|  4 |         33396954 |  5 |         32134430 |
|  6 |         31835530 |  7 |         21256526 |
|  8 |         20633188 |  9 |         19364217 |

Error details:
| Count | Error text                       | Last seen           |
|     4 | [NETWORK ERROR]                  | 2018-08-22 01:21:25 |
|   123 | Invalid nonce; is miner not comp | 2018-08-22 00:12:45 |
|     2 | Low difficulty share             | 2018-08-22 00:13:05 |

```
This is for a 12 GPU rig of RX 550 mining CN7.
What's the cause for the bad performance?

Here's my miner config file:
```
        {"pool_address" : "192.168.1.100:3333", "wallet_address" : "", "rig_id" : "RX550_1", "pool_password" : "", "use_nicehash" : true,
 "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
```
Here's my xmrig-proxy config file:
```
{
    "access-log-file": null,
    "algo": "cryptonight",
    "api": {
        "port": 81,
        "access-token": null,
        "id": "xmr-proxy",
        "worker-id": false,
        "ipv6": false,
        "restricted": false
    },
    "background": false,
    "bind": [
        "0.0.0.0:3333",
        ":3333"
    ],
    "colors": false,
    "custom-diff":0,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "url": "xmr.minercountry.com:7777",
            "user": "address.1000000",
            "pass": "xdn_address",
            "rig-id": null,
            "keepalive": true,
            "variant": 1
        }
    ],
    "retries": 65565,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "user-agent": null,
    "verbose": true,
    "watch": true,
    "workers": true
}
```

**Comment by MoneroCrusher** [comment]
I should note: I just tried it again and the first 15 or so shares always get 100% good result across all my rack (108 cards). It then starts to reject all of them after about 20-30min without exception.
Pool banning me maybe?

**Comment by tarris034** [comment]
> I should note: I just tried it again and the first 15 or so shares always get 100% good result across all my rack (108 cards). It then starts to reject all of them after about 20-30min without exception.

I think it is related to my issue:
https://github.com/xmrig/xmrig-proxy/issues/248

**Comment by MoneroCrusher** [comment]
I think my problem could be solved with "keepalive" but it seems to not work with xmr-stak 2.4.7

**Comment by tarris034** [comment]
I use the keepalive on both sides (proxy / miner) - it doesn't help, but today when I got the error "YOU MUST UPGRADE YOUR MINER" it didn't "ban" all the workers on that particular upstream so maybe something got done on the pool side ? IDK, will report later if it continues or does it stopped.

**Comment by MoneroCrusher** [comment]
I re-built XMRig and it magically works now. Keepalive still doesnt work for xmr-stak and now I just lowered difficulty so each miner can find one in approx 2 minutes. Not an ideal solution but it works for now. Gotta see that the pool doesnt ban me.

**Comment by tarris034** [comment]
the problem is back lol, but i just have it in restart loop.
