### ISSUE TITLE
Extended workers support

### ISSUE THREAD

**Issue by xmrig** [xmrig/xmrig-proxy#251]
In version 2.7 option `workers` extended to allow specify what field or miner ip address should used to build workers list, all changes backward compatible with previous versions.

Possible values for `workers` option:
* `false` or `"none"`, workers support disabled.
* `true` or `"rig_id"`
* `"user"` 
* `"password"`
* `"agent"`, miner identification, for example `XMRig/2.6.4 (Windows NT 10.0; Win64; x64) libuv/1.22.0 gcc/7.3.0`
* `"ip"`

Also option `workers` now can changed on fly via config reload feature, statistics will be reset.
If `rig_id` mode selected, but miner don't send this field, will be used field `user` as failback.

**Comment by xmrig** [comment]
Implemented in v2.8.

**Comment by Valenzuelafer** [comment]
Reopen
