### ISSUE TITLE
How to Use XMRig Proxy 

### ISSUE THREAD

**Issue by Achilles29** [xmrig/xmrig-proxy#252]
I'm new, and i still got confuse of using xmrig proxy. can i get step by step of using it?
what should i do first? should i run it on my vps or just in mw pc worker? is there any setup i must do in my vps? for information, i using windows in my vps.
thats all and thank you so much

**Comment by rocke** [comment]
me too

**Comment by TheBoroer** [comment]
I'd recommend you guys use docker (easy setup). There's ton's of tutorials on how to install docker and get started with it.

Here's an easy to use docker image I made: https://hub.docker.com/r/boro/xmrig-proxy/
