### ISSUE TITLE
XMRig-Proxy stops when closing script and/or terminal?

### ISSUE THREAD

**Issue by iCraziTeddy** [xmrig/xmrig-proxy#253]
Hello there!
Currently started using XMRig Proxy without any issues.
Now i use the webpanel aswell. And i noticed that when i either do CTRL C, to close the script. Or just close my terminal via putty it stops mining and wont connect to the API anymore to view my stats.

Now my question is: 
Is there a way to let it mine all the time?
As i am using a VPS to make sure it is 24/7 online for me without having my own PC online.
But it seems i have to be connected with Putty and runned the script to have it mining.

I have no idea if this is in the VPS or the Proxy itself. But i hope there is an answer for this issue.
Thank you!

**Comment by lidongran128** [comment]
Use screen tools.You will solve the problem.（ps：My system is CentOS）
