### ISSUE TITLE
Error starting xmrig-proxy 2.8.0-rc on CentOS 6

### ISSUE THREAD

**Issue by msarig** [xmrig/xmrig-proxy#258]
Hi.

I compiled xmrig-proxy version 2.8.0-rc successfully on CentOS 6 (x86_64) host. But when I execute the compiled binary, it aborts with the following message:

```
/usr/bin/xmrig-proxy-280-rc-httpd-c6 --version
xmrig-proxy 2.8.0-rc
 built on Oct  4 2018 with GCC 7.3.1
 features: 64-bit

libuv/1.20.4-dev
microhttpd/0.9.59
OpenSSL/1.0.1e
xmrig-proxy-280-rc-httpd-c6: /usr/src/xmrig-proxy-2.8.0-rc/src/common/log/Log.h:42: static void Log::release(): Assertion `m_self != nullptr' failed.
Aborted

```
The same happens with all xmrig-proxy versions since 2.6.0. The only working version is 2.5.3.

What is the correct way to compile version 2.8.0-rc on CentOS 6?
Thanks.

**Comment by xmrig** [comment]
Looks strange, all assertions should removed from release builds, it's only for debug builds, this fix https://github.com/xmrig/xmrig-proxy/commit/0a8a59945cb9acf7d907c914e33501ec435b213a probably helps with your issue.
Thank you.

**Comment by msarig** [comment]
Excellent. That patch fixed the reported issue.
Thanks for your quick help.
