### ISSUE TITLE
config.json:648: Invalid value.No pool URL supplied. Exiting. ?

### ISSUE THREAD

**Issue by klobymoby** [xmrig/xmrig-proxy#26]
what did I write wrong in conf?

"pools": [
        {
            "url": "pool.supportxmr.com:7777",
            "user": "46J1KruAU9RLxwSq9eKTHcajvMywiCCCMV1hwQWbasrxBYkJkCXn2aYbLUfJ43yGe5XW9bSkaMb4Q5pVCECB6eN5P9tcCX1",
            "pass": "x"
        }
    ],

**Comment by xmrig** [comment]
Please paste full config, this part looks good. Error on offset 648.
Thank you.

**Comment by klobymoby** [comment]
{
    "background": false,
    "log-file": null,
    "access-log-file": null,
    "retries": 5,
    "retry-pause": 5,
    "donate-level": 1,
    "coin": "xmr",
    "custom-diff": 0,
    "syslog": false,
    "verbose": true,
    "workers": true,
    "pools": [
        {
            "url": "pool.supportxmr.com:7777",
            "user": "46J1KruAU9RLxwSq9eKTHcajvMywiCCCMV1hwQWbasrxBYkJkCXn2aYbLUfJ43yGe5XW9bSkaMb4Q5pVCECB6eN5P9tcCX1",
            "pass": "x"
        }
    ],
    "bind": [
        "192.168.140.1:3333"
    ],
    "api": {
        "port": 8080,
        "access-token": null,
        "worker-id": work
    }
}

**Comment by klobymoby** [comment]
{
"background": false,
"log-file": null,
"access-log-file": null,
"retries": 5,
"retry-pause": 5,
"donate-level": 1,
"coin": "xmr",
"custom-diff": 0,
"syslog": false,
"verbose": true,
"workers": true,
"pools": [
{
"url": "pool.supportxmr.com:7777",
"user": "46J1KruAU9RLxwSq9eKTHcajvMywiCCCMV1hwQWbasrxBYkJkCXn2aYbLUfJ43yGe5XW9bSkaMb4Q5pVCECB6eN5P9tcCX1",
"pass": "x"
}
],
"bind": [
"192.168.140.1:3333"
],
"api": {
"port": 8080,
"access-token": null,
"worker-id": work
}
}

**Comment by xmrig** [comment]
```json
"worker-id": "work"
```
String values in JSON must be placed inside `"`.

**Comment by klobymoby** [comment]
thnx its working!
