### ISSUE TITLE
What are the current Variant options ?

### ISSUE THREAD

**Issue by tarris034** [xmrig/xmrig-proxy#261]
I know -1 is auto but what if I want manually set it to use current PoW or the upcoming PoW ? 

Thank you in advance, couldn't find it anywhere.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#14-algorithm-names-and-variants
For Monero, current algorithm variant is `1` and upcoming is `2`.
Thank you.
