### ISSUE TITLE
End of File Error in Proxy Chaining

### ISSUE THREAD

**Issue by varunj** [xmrig/xmrig-proxy#263]
I am trying to connect a number of machines to proxy p1 which is connected to proxy p2 which is connected to the internet/pool.

I have been getting the following error at p1:
[<IP address p2>:5555] read error: "end of file"

What could be the reason? I tried finding it in the source code but couldn't exactly understand.

**Comment by xmrig** [comment]
Network issue, remote party close connection, in previous versions this error was hidden https://github.com/xmrig/xmrig/issues/777
