### ISSUE TITLE
Agency calculation and ore pool calculation do not match.

### ISSUE THREAD

**Issue by rocke** [xmrig/xmrig-proxy#265]
Agency calculation and ore pool calculation do not match.

https://s1.ax1x.com/2018/10/18/iwEqds.jpg

http://wx1.sinaimg.cn/mw690/0060lm7Tly1fwce7137ovj30l803lt8l.jpg

**Comment by xmrig** [comment]
Press `h` to see hashrate in others intervals, nodejs-pool based pools use 10 minutes interval (it's supportxmr.com on your screenshot?) and 24 hours as well. On your first screenshot proxy show hashrate per minute.

**Comment by rocke** [comment]
http://wx3.sinaimg.cn/mw690/0060lm7Tly1fwchb1o5fjj30ep089wfm.jpg
