### ISSUE TITLE
Workers reconnecting

### ISSUE THREAD

**Issue by W33v3ly** [xmrig/xmrig-proxy#266]
Yesterday everything be OK but after FORK it show that look:

[Screenshot](https://i.imgur.com/JTxbcF5.png)

I use latest xmrig and latest xmrig proxy where is problem can someone help me please? I have 200+ connection on port 80 i use it as listen port.But xmrig proxy show me 2k connection an also 14 usptreams but real connections is only 200+

**Comment by xmrig** [comment]
2300 new connections and disconnects per minute, some your miners not updated to v2.8, enable `"access-log-file"` to find out outdated miners.
Thank you.

**Comment by W33v3ly** [comment]
Ok i enabled it and i see quantum users how to disable it all ? but i dont know which it show thousands when i have 200+ connection on port i must check all ports thanks for reply me

**Comment by xmrig** [comment]
Merge with #177
