### ISSUE TITLE
Proxy accept low shares.

### ISSUE THREAD

**Issue by Vazum** [xmrig/xmrig-proxy#267]
Let me explain you whats the issue.

1. Example i run a miners and use proxy, i recive lower ACCEPTED SHARES and LOWER H/S and not stabble H/S example one miner give 1.4kh i get per hour total 3kh while all miners give 10kh.

2. Example i run miners without proxy, i recive stable ACCEPTED SHARES and HIGHER HS, example stable of 10kh per 24hours.

Whats the problem to XMRIG-Proxy?

**Comment by xmrig** [comment]
If this is still actual, please provide all possible information, including configs
Thank you.
