### ISSUE TITLE
Running on win server 2003 x64

### ISSUE THREAD

**Issue by madstas-ua** [xmrig/xmrig-proxy#27]
Hi!
Trying 2 run on server 2003 x64 but get error " .exe is not a valid win 32 application"
Installed .NET frameworks 4.0 and C++ Runtime 2015.
Tried x64 and x32 versions of program - same issue

**Comment by xmrig** [comment]
It because I use MSVC 2017 to build exe files, but it not compatible with Windows XP and 2003 as well.
Can you build proxy from source using MSYS2 https://github.com/xmrig/xmrig-proxy/wiki/Windows-Build ?
Thank you.

**Comment by madstas-ua** [comment]
Well sorry, im not really programmer etc, so i installed MSYS2, copied source code of proxy to c:\1 folder and runes this command:   
cmake .. -G "Unix Makefiles" -DUV_INCLUDE_DIR="c:\1\gcc\libuv\x64\include" -DUV_LIBRARY="c:\1\gcc\libuv\x64\lib\libuv.a" -DMHD_INCLUDE_DIR="c:\1\gcc\libmicrohttpd\x64\include" -DMHD_LIBRARY="c:\1\gcc\libmicrohttpd\x64\lib\libmicrohttpd.a" make

And got error: cmake command not found
What i do wrong?
Thanks for your help and patience )

**Comment by xmrig** [comment]
You need run `mingw64.exe` or `mingw32.exe` also download dependencies https://github.com/xmrig/xmrig-deps/releases/tag/v2

I can build binaries later today, so you can just wait.

**Comment by xmrig** [comment]
[xmrig-proxy-2.4.1.zip](https://github.com/xmrig/xmrig-proxy/files/1369247/xmrig-proxy-2.4.1.zip)

I make two exe files 32/64 bit, both should work. I can't verify it by myself, I currently have no access to win 2003.
Thank you.

**Comment by madstas-ua** [comment]
thank you!
x32 version work just fine!
x64 get this error (sorry google translate): The entry point to the GetTickCunt64 procedure was not found in the Kernel32.dll library

**Comment by xmrig** [comment]
Ok thank you, I will also make 32 bit builds for old systems for next releases.

**Comment by madstas-ua** [comment]
Thanks!!!
