### ISSUE TITLE
seg fault when -c used with --pass/--userpass/--user

### ISSUE THREAD

**Issue by aleqx** [xmrig/xmrig-proxy#271]
Compiled latest master on Ubuntu 16.04. If I try:

```
./xmrig-proxy -c cn-heavy.json --pass=foobar:x
```

It exits with a segmentation fault.

The above would be useful so that I can use the same .json file but only change the password for various pools (usually the worker name).

**Comment by xmrig** [comment]
Fixed, but it works as you expected only if `cn-heavy.json` contains only one pool, otherwise only last pool in list will be changed and hard to change this behavior without add additional options.
Thank you.

**Comment by aleqx** [comment]
Thank you. It's a shame it only affects the last defined pool - is it that difficult to change it for all defined pools?

**Comment by xmrig** [comment]
It's not so hard to implement, but required to add new option with new name, maybe `--pass-override` etc.

**Comment by aleqx** [comment]
I was saying that if I use `xmrig-proxy -c cn.json --pass foo` (specifically, I use `--pass foo` **after** `-c cn.json`) then that should override all passwords in the pools ... I don't see why there should be a new option.

Generally, my suggestion was that **any** command line option used after (or before) `-c cn.json` should override the value of the same option inside cn.json. For example, `xmrig-proxy -c cn.json --verbosity 0` would set verbosity to 1, overriding whatever is in cn.json.

**Comment by xmrig** [comment]
Internally config parser don't know it JSON value or command line or second config.

**Comment by xmrig** [comment]
Fixed in v2.9.1 release.
Thank you.
