### ISSUE TITLE
error "end of file" cryptonightv8

### ISSUE THREAD

**Issue by exp10r** [xmrig/xmrig-proxy#272]
Hi.
![end of file](https://user-images.githubusercontent.com/38540975/47346470-f4d7ad00-d6b5-11e8-94cc-ee708a38fb09.PNG)

After the update here is the problem with nicehash.com . How to fix?
Xmrig Proxy 2.8.1
Xmrig CPU 2.8.3

**Comment by GestARLite** [comment]
I have been having the same error.

I even raised an issue long back [here](https://github.com/xmrig/xmrig-proxy/issues/263) but no one has responded yet :(

**Comment by xmrig** [comment]
Network issue, remote party close connection, in previous versions this error was hidden https://github.com/xmrig/xmrig/issues/777
