### ISSUE TITLE
Probably a bug - assertion failed in src/unix/getaddrinfo.c:122: uv__getaddrinfo_done

### ISSUE THREAD

**Issue by Roboto12** [xmrig/xmrig-proxy#273]
Hi.
Today I got an fatal error:

`xmrig-proxy-notls: src/unix/getaddrinfo.c:122: uv__getaddrinfo_done: Assertion `0' failed`

Before today, the proxy worked just fine. The only difference is today I switched more clients to my proxy, but the CPU and memory usage is still less than 1%.

**Comment by xmrig** [comment]
Duplicate #236
