### ISSUE TITLE
Result rejected by the pool

### ISSUE THREAD

**Issue by sigmaraye** [xmrig/xmrig-proxy#274]
i have updated my xmr-stak to 2.52 and xmrig proxy to 2.81.
 xmr-stak print result rejecjted 

and the proxy print
  * ABOUT        xmrig-proxy/2.8.1 MSVC/2017
 * LIBS         libuv/1.23.1 OpenSSL/1.1.1 microhttpd/0.9.59
 * MODE         nicehash
 * ALGO         cryptonight
 * POOL #1      stratum+tcp://xmr.f2pool.com:13531 variant 1
 * BIND #1      10.40.1.3:5555
 * BIND #2      [::]:3333
 * COMMANDS     hashrate, connections, verbose, workers
[2018-10-27 02:02:54] * speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2018-10-27 02:03:04] #000 rejected (0/1+1) diff 16384 ip 192.168.3.200 "high-hash" (135 ms)
[2018-10-27 02:03:15] 0.00 kH/s, shares: 0/1 +0, upstreams: 1, miners: 6 (max 6) +7/-1
[2018-10-27 02:03:24] * speed (1m) 0.00, (10m) 0.00, (1h) 0.00, (12h) 0.00, (24h) 0.00 kH/s
[2018-10-27 02:03:25] #000 rejected (0/2+1) diff 16384 ip 192.168.3.200 "high-hash" (113 ms)
[2018-10-27 02:04:16] 0.00 kH/s, shares: 0/2 +0, upstreams: 1, miners: 4 (max 6) +0/-2
[2018-10-27 02:05:17] 0.00 kH/s, shares: 0/2 +0, upstreams: 1, miners: 4 (max 6) +4/-4
[2018-10-27 02:06:18] 0.00 kH/s, shares: 0/2 +0, upstreams: 1, miners: 5 (max 6) +5/-4
[2018-10-27 02:07:20] 0.00 kH/s, shares: 0/2 +0, upstreams: 1, miners: 4 (max 6) +4/-5

when i use xmr-stak directly without proxy,it'll worked and the pool recieved my hashrate.

 this is proxy set (without wallet addres,i delete.)

"{
    "access-log-file": null,
    "algo": "cryptonight",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "background": false,
    "bind": [
        "10.40.1.3:5555",
        "[::]:3333"
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "url": "stratum+tcp://xmr.f2pool.com:13531",
            "user": " xxxxxx ",
            "pass": "x",
            "rig-id": null,
            "keepalive": false,
            "variant": 1,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "user-agent": null,
    "verbose": false,
    "watch": true,
    "workers": true
}

and this is xmr-stak 

// generated by xmr-stak/2.5.2/752fd1e7e/master/win/nvidia-amd-cpu/20

/*
 * pool_address    - Pool address should be in the form "pool.supportxmr.com:3333". Only stratum pools are supported.
 * wallet_address  - Your wallet, or pool login.
 * rig_id          - Rig identifier for pool-side statistics (needs pool support).
 * pool_password   - Can be empty in most cases or "x".
 * use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
 * use_tls         - This option will make us connect using Transport Layer Security.
 * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
 * pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool
 *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
 *
 * We feature pools up to 1MH/s. For a more complete list see M5M400's pool list at www.moneropools.com
 */

"pool_list" :
[
	{"pool_address" : "10.40.1.3:5555", "wallet_address" : "xx", "rig_id" : "1", "pool_password" : "", "use_nicehash" : true, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
],

/*
 * Currency to mine. Supported values:
 *
 *    aeon7 (use this for Aeon's new PoW)
 *    bbscoin (automatic switch with block version 3 to cryptonight_v7)
 *    bittube (uses cryptonight_bittube2 algorithm)
 *    graft
 *    haven (automatic switch with block version 3 to cryptonight_haven)
 *    intense
 *    masari
 *    monero (use this to support Monero's Oct 2018 fork)
 *    qrl - Quantum Resistant Ledger
 *    ryo
 *    turtlecoin
 *
 * Native algorithms which not depends on any block versions:
 *
 *    # 1MiB scratchpad memory
 *    cryptonight_lite
 *    cryptonight_lite_v7
 *    cryptonight_lite_v7_xor (algorithm used by ipbc)
 *    # 2MiB scratchpad memory
 *    cryptonight
 *    cryptonight_v7
 *    cryptonight_v8
 *    # 4MiB scratchpad memory
 *    cryptonight_bittube2
 *    cryptonight_haven
 *    cryptonight_heavy
 */

"currency" : "monero",

**Comment by xmrig** [comment]
This issue is still actual?
Thank you.

**Comment by sigmaraye** [comment]
> This issue is still actual?
> Thank you.

i fix it already.
i change variant 1 to -1 and it worked,
