### ISSUE TITLE
Add support for Italocoin(CryptoNightItalo)

### ISSUE THREAD

**Issue by KL0nLutiy** [xmrig/xmrig-proxy#276]
Please add support for Italocoin(CryptoNightItalo)
https://bitcointalk.org/index.php?topic=3122277.0

**Comment by browolf** [comment]
Can we get a page on the wiki showing all the coins/variants supported with their config file strings?

**Comment by xmrig** [comment]
@browolf done https://xmrig.com/docs/supported-currencies also https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#14-algorithm-names-and-variants
