### ISSUE TITLE
the proxy shows zero kh

### ISSUE THREAD

**Issue by adevelopcr** [xmrig/xmrig-proxy#277]
the problem is that the proxy prints 0 kh
but the miner (xmr-stak cpu only) mines will and submits shares to the pool
the pool shows the shares and the hashrate

**Comment by xmrig** [comment]
If this is still actual, please provide all possible information, including configs
Thank you.

**Comment by adevelopcr** [comment]
No this wasn't an issue , the proxy was measuring the hash in kh not hashes so it didn't give a rate for a small miner which made nearly 16 h/s only . But once I connected with some other miners it showed the result correctly
