### ISSUE TITLE
xmr-stak-nvidia

### ISSUE THREAD

**Issue by dgiero** [xmrig/xmrig-proxy#28]
Can I use xmr-stak-nvidia with xmrig-proxy?

I'm using already xmr-stak-cpu with no problem.
The xmr-stak-nvidia miner is recognized by the proxy as connected but the hashrate is zero

WORKER NAME | LAST IP | COUNT | ACCEPTED | REJ | 10 MIN |
47d3xw...Wy47ikbNRJ.GC1 | 192.168.85.207 | 1 | 20 | 0 | 0.2 KH/s |
47d3xw...Wy47ikbNRJ.GG1 | 192.168.85.207 | 1 | 0 | 0 | 0.0 KH/s |
47d3xw...Wy47ikbNRJ.GG2 | 192.168.85.205 | 1 | 0 | 0 | 0.0 KH/s |

The GC1 worker is a xmr-stak-cpu miner, the other two are nvidia miners.

Both nvidia miners have an hashrate of 620H/s .

Moreover, does xmrig-proxy send the worker id to the pool? I'm using  minexmr.com as poll and in the "Per Worker Stats" I can't find the worker IDs but only my address wallet. With another xmr proxy I could see every single worker IDs.

**Comment by xmrig** [comment]
xmr-stak-nvidia does not support nicehash, so it incomparable with proxy.
But next all in one xmr-stak https://github.com/fireice-uk/xmr-stak should support it.
Thank you.

**Comment by dgiero** [comment]
Thanks, it seems to work.
Can you tell me why I can't see the worker IDs on the pool stats?

In the miners' config files I put WALLETADDR.WORKERIDN as wallet, the proxy recognize them but the pool doesn't. With another proxy this worked fine.

XMR-PROXY
47d3xw...y47ikbNRJ.GPU1 | 192.168.85.207  |     1 |        5 |   0 |   1.3 KH/s |
47d3xw...y47ikbNRJ.GPU2 | 192.168.85.205  |     1 |        1 |   0 |   0.5 KH/s |

MINEXMR POOL
Hash Rate | Shares Accepted | Expired Shares | Invalid Shares | Last Share Submitted | Worker ID
1.82 KH/s | 7234564              | 0                       | 0                     | about a minute ago    | 47d...NRJ

**Comment by xmrig** [comment]
For pool it one big miner, one pool connection can be used up to 256 worker connections, there no way to bypass worker id to pool. In miners don't need put wallet address, just GPU1 is fine.
