### ISSUE TITLE
Feature Request: Possibility of Merged Mining via xmrig-proxy?

### ISSUE THREAD

**Issue by nutsnax** [xmrig/xmrig-proxy#281]
Just thought I'd throw this out there, but there seems to be an increase of merged mining pools coming out (minercountry.com etc). Some of these pools are dominating certain coins. Would it be possible to implement a form of merged mining at the proxy level? From what I've looked at, it looks like it could be possible.....

**The main reason I'm even broaching this is because of the rash of attacks against smaller coins that I'm seeing and that this could significantly help spread hash to newer coins. This could allow new coins to "piggyback" on to bigger coins** 

edit: tried to cut the verbiage down to hopefully make it clearer what I'm asking

**Comment by nutsnax** [comment]
Oh, the other benefit of a setup like this is that it wouldn't require pools to change anything.... so no per-coin pool config muckery.... just modification at the proxy level and it works with existing pool infrastructure.

**Comment by xmrig** [comment]
Merged mining can be done only on pool side, but it will works with proxy if pool support it, because proxy know nothing about what happened inside pool.
