### ISSUE TITLE
./xmrig-proxy: 1: ./xmrig-proxy: :: variable not found

### ISSUE THREAD

**Issue by abrakadab** [xmrig/xmrig-proxy#284]
Hello guys,

I have problem when trying to execute:

sudo ./xmrig-proxy

i have errors in console 

 ./xmrig-proxy: 1: ./xmrig-proxy: :: variable1 not found
 ./xmrig-proxy: 2: ./xmrig-proxy: :: variable2 not found
 ./xmrig-proxy: 3: ./xmrig-proxy: :: variable3 not found

Those are variables from config.json

I couldn't find the answer what to do to fix it. I am newbie to linux so appreciate some help. 

Regards!

**Comment by abrakadab** [comment]
I forgot to add that those are variables from config.json

**Comment by DeadManWalkingTO** [comment]
1. Check quotes at variables!
2. Reply here.

Thank you!
