### ISSUE TITLE
whats is ratio?

### ISSUE THREAD

**Issue by snipeTR** [xmrig/xmrig-proxy#285]
whats is mean
![image](https://user-images.githubusercontent.com/31975916/49309589-c2a73f80-f4ec-11e8-97ec-66261af76e16.png)
![image](https://user-images.githubusercontent.com/31975916/49309598-caff7a80-f4ec-11e8-8e15-d7c9a10c01f7.png)

**Comment by tarris034** [comment]
it means that on average there's 211 workers per upstream if I'm correct.

btw, cool paint skillz xD
