### ISSUE TITLE
Can i mine Webchain coin using the proxy ?

### ISSUE THREAD

**Issue by Drshell909** [xmrig/xmrig-proxy#293]
Can i mine Webchain coin using the proxy ?

since i try to change the config but not work

**Comment by xmrig** [comment]
Webchain use custom/non standard stratum protocol, so it not possible.
Thank you.

**Comment by xmrig** [comment]
xhv supported as `cn-heavy/xhv` https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#14-algorithm-names-and-variants
