### ISSUE TITLE
Feature request: Stacking workers in active streams

### ISSUE THREAD

**Issue by tarris034** [xmrig/xmrig-proxy#298]
It would be cool if xmr-proxy did actively move the workers from the last upstream to the upstreams that were created earlier but ain't full due to disconnection of workers so all upstreams are full except maybe the last one.

I'm currently restarting proxy every 2h to reassign the workers so each upstream operates at it's maximal capacity, otherwise some upstreams that lost majority of workers are useless/not as effective when using nicehash and high diff.

I hope you will understand my problem.

PS. If you are willing to add this feature, please do it only as an option you can turn on only if you want it.

**Comment by 2010phenix** [comment]
if I undestand correct, you ask about split hashrate for worker -  work correct with this panel: https://github.com/JerryWm/Stratum-Proxy-XMR
@xmrig don't know who is JerryWm, if have time look on, thay do good job and is help for big step(and close few issues) with xmrig-proxy web panel stat

**Comment by tarris034** [comment]
no, I was referring to the more internal functioning of the proxy.
