### ISSUE TITLE
multiple --url on command line fails to connect.

### ISSUE THREAD

**Issue by bittaurus** [xmrig/xmrig-proxy#299]
I believe it used to work to have multiple pool url's on the command line.  If I only have 1 --url on the command line it connects fine. With more than one, it will enumerate them, but not connect, giving this error:

 * ABOUT        xmrig-proxy/2.10.0 gcc/4.8.5
 * LIBS         libuv/1.24.1 OpenSSL/1.0.2k microhttpd/0.9.33 
 * MODE         nicehash
 * ALGO         cryptonight
 * POOL #1      stratum+tcp://sg.minexmr.com:7777 variant auto
 * POOL #2      stratum+tcp://ca.minexmr.com:7777 variant auto
 * POOL #3      stratum+tcp://de.minexmr.com:7777 variant auto
 * POOL #4      stratum+tcp://fr.minexmr.com:7777 variant auto
 * BIND #1      0.0.0.0:3335
 * COMMANDS     hashrate, connections, verbose, workers
[2019-02-07 14:31:41] [stratum+tcp://sg.minexmr.com:7777] error: "invalid address used for login", code: -1

I'm compiled on centos 7.  Any ideas?  Did someone fix fallover and break something else?

**Comment by xmrig** [comment]
You need duplicate all pool related options, example: `--url pool1 --user wallet1 --url pool2 --user wallet1`, try https://config.xmrig.com/proxy to generate proper command line.
Thank you.
