### ISSUE TITLE
lower share recived

### ISSUE THREAD

**Issue by damoon223** [xmrig/xmrig-proxy#3]
i use Atrides - xmr-proxy and i am new on xmrig-proxy
---
mining software is xmrig 
mining pool dwarf
---
when i get about 1.7 kh -  42 peers by atrides proxy , same time i get 0.6 - low share and  32 connection with xmrig proxy.
second thing is i try use nicehash but i got red warn about incompatible nonce with nicehash
third please consider change diff for future feature its very handy
best wishes

**Comment by xmrig** [comment]
Proxy required miner with nicehash support, for xmrig it `--nicehash` option. Proxy by self cannot used with nicehash.com by self.
Thank you.

**Comment by damoon223** [comment]
dear bro i just want report trace for your job 
about nicehash same issue yet
clientside:
xmrig 2.2.0
xmrig.exe -o 	stratum+tcp://myvpsip:9090 -u m1 -p x -k --nicehash
diff 40000
server side:
xmrig-proxy.exe -o cryptonight.eu.nicehash.com:3355 -u nicehashwallet -p x --bind 0.0.0.0:9090

client warn on submit share:
rejected;invalid nonce;is miner not compatible with nicehash?
server side warn:
rejected;invalid nonce;is miner not compatible with nicehash?
------------
test 2 :
i use xmrig 2.2.0 direct to nicehash
xmrig.exe -o 	stratum+tcp://cryptonight.eu.nicehash.com:3355 -u mynicehashwallet -p x -k  --nicehash
work fine and accept share
----
about lower connection than Atrides - xmr-proxy is not solved
i try use fix diff this time and longer time to monitor about 14 hours
change client xmrig version from 2 to 2.2.0 got better result and better share accept but lower connection yet
i will wait to 24 hours to better report result
----
 is need client to define wallet and how to define client worker id to submit in pool?
with xmrig-proxy i got miner name "o" on pool side and with direct use xmrig to pool i got normal worker id
my command line client for xmrig-proxy side:
xmrig.exe -o 	stratum+tcp://myvpsip:9090 -u workerid -p x -k 
is it right or i miss something?

best wishes

**Comment by xmrig** [comment]
Proxy can't work with nicehash.com it works only with normal pools.
Thank you.

**Comment by damoon223** [comment]
i think i find why i get lower hashrate, but i am not sure for now
sometimes in report for 5 min  i get "reject ,low dif share" and after that every thing ok, and this moment effect avg hashrate, this problem show every 90-120 minutes and cause 5% loss share
also i set fix dif 20000 to pool. and working with dwarf pool

**Comment by xmrig** [comment]
You see rejected messages in proxy console or one of miners console?
If in proxy console pool reject shares.
If in miner console, proxy reject.

**Comment by damoon223** [comment]
sorry about a lot message,actually its not very big deal 5% loss for me but i like give you a good report for next develop if you like, you can access my vps for trace if you need

its on proxy console side
but how ?
its a fix dif port, console get fix 20000 dif , miner get fix dif too
i get reject , low dif share on console but for awhile , there are many deference miner i have 
all of them share wrong diff and suddenly all of them share back to normal?
i think something go wrong depended on time variable on proxy side

**Comment by damoon223** [comment]
in version 2.3 this issue solved as i seen
