### ISSUE TITLE
unable to mine cn/wow 

### ISSUE THREAD

**Issue by theksk** [xmrig/xmrig-proxy#300]
Hola,
built 2.12.0 form source, and since the wownero fork I am unable to make xmrig-proxy connect to a wownero poo with '"algo": "cn/wow"' in config:

> xmrig@xmrig-proxy:~/xmrig-proxy/build$ ./xmrig-proxy-notls -V
> xmrig-proxy 2.12.0
>  built on Feb 18 2019 with GCC 6.3.0
> features: 64-bit
> libuv/1.9.1
> microhttpd/0.9.51

> [2019-02-20 11:42:02] Incompatible algorithm "cryptonight/wow" detected, reconnect
> [2019-02-20 11:42:02] [wownero.luckypool.io:4466] login error code: 6

I suspect miner-side the correct algo is choosen (as I could mine pre-fork with this version) - but now its like the token to exchange with pool has changed?

Mining with xmrig 2.12.0 directly to pool works fine btw.

**Comment by 2010phenix** [comment]
are you have one miner or some more?

**Comment by theksk** [comment]
Does that really matter if connecting the xmrig-proxy without any miners throws an error?

**Comment by theksk** [comment]
updated to 2.13.1 and everything works fine, case closed. thanks!
