### ISSUE TITLE
/usr/bin/ld: cannot find -luuid on Fedora 27

### ISSUE THREAD

**Issue by OthmanB** [xmrig/xmrig-proxy#301]
Tried to compile xmrig v2.13.0 on a Fedora 27 system and got the error below. Note that I have compiled earlier versions in the past without any issues on that same system. And xmrig v2.13.0 and xmrig-nvidia v2.13.0 compile without any issue.

> cmake ..
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib64/libuv.a  
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.1.0i") 
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found MHD: /usr/lib64/libmicrohttpd.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/obenomar/Mine/Fork-Mars2019/xmrig-proxy/build

> make
Scanning dependencies of target xmrig-proxy
[  1%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App.cpp.o
[  3%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/base/tools/String.cpp.o
[  4%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/config/CommonConfig.cpp.o
[  6%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/config/ConfigLoader.cpp.o
[  8%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/config/ConfigWatcher.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/Console.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/crypto/Algorithm.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/crypto/keccak.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/BasicLog.cpp.o
[ 16%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/ConsoleLog.cpp.o
[ 17%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/FileLog.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/Log.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/Client.cpp.o
[ 22%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/Job.cpp.o
[ 24%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/Pool.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/strategies/FailoverStrategy.cpp.o
[ 27%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/strategies/SinglePoolStrategy.cpp.o
[ 29%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/SubmitResult.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/Platform.cpp.o
[ 32%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/Config.cpp.o
[ 33%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/core/Controller.cpp.o
[ 35%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/AccessLog.cpp.o
[ 37%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/log/ShareLog.cpp.o
[ 38%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/JobResult.cpp.o
[ 40%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/net/strategies/DonateStrategy.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/BindHost.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Counters.cpp.o
[ 45%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/CustomDiff.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Error.cpp.o
[ 48%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Events.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/events/Event.cpp.o
[ 51%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/events/MinerEvent.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Login.cpp.o
[ 54%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Miner.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Miners.cpp.o
[ 58%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Proxy.cpp.o
[ 59%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/ProxyDebug.cpp.o
[ 61%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Server.cpp.o
[ 62%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/nicehash/NonceMapper.cpp.o
[ 64%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/nicehash/NonceSplitter.cpp.o
[ 66%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/nicehash/NonceStorage.cpp.o
[ 67%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/simple/SimpleMapper.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/simple/SimpleSplitter.cpp.o
[ 70%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/splitters/Splitter.cpp.o
[ 72%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Stats.cpp.o
[ 74%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/workers/Worker.cpp.o
[ 75%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/workers/Workers.cpp.o
[ 77%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/Summary.cpp.o
[ 79%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/xmrig.cpp.o
[ 80%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/App_unix.cpp.o
[ 82%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/Platform_unix.cpp.o
[ 83%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Uuid_unix.cpp.o
[ 85%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/log/SysLog.cpp.o
[ 87%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/api/Api.cpp.o
[ 88%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/api/ApiRouter.cpp.o
[ 90%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/api/Httpd.cpp.o
[ 91%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/api/HttpRequest.cpp.o
[ 93%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/common/net/Tls.cpp.o
[ 95%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/tls/Tls.cpp.o
[ 96%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/tls/TlsConfig.cpp.o
[ 98%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/tls/TlsContext.cpp.o
[100%] Linking CXX executable xmrig-proxy
/usr/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xmrig-proxy.dir/build.make:988: xmrig-proxy] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/xmrig-proxy.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

If I do:
> locate libuuid

/usr/lib64/libuuid.so
/usr/lib64/libuuid.so.1
/usr/lib64/libuuid.so.1.3.0
/usr/share/licenses/libuuid
/usr/share/licenses/libuuid/COPYING
/usr/share/licenses/libuuid/COPYING.BSD-3
/usr/x86_64-w64-mingw32/sys-root/mingw/lib/libuuid.a
/var/cache/PackageKit/27/metadata/updates/packages/libuuid-2.30.2-2.fc27.x86_64.rpm
/var/cache/PackageKit/27/metadata/updates/packages/libuuid-2.30.2-3.fc27.x86_64.rpm
/var/cache/PackageKit/27/metadata/updates/packages/libuuid-devel-2.30.2-2.fc27.x86_64.rpm
/var/cache/PackageKit/27/metadata/updates/packages/libuuid-devel-2.30.2-3.fc27.x86_64.rpm

So that library is there...

Any help appreciated...

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-proxy/blob/master/CMakeLists.txt#L173 please replace `uuid.a` to `uuid`.
Thank you.

**Comment by OthmanB** [comment]
Indeed. Problem Fixed. Thanks.
