### ISSUE TITLE
[SOLVED] Centos 7 compile problem -luuid

### ISSUE THREAD

**Issue by Adi-Arad-Ro** [xmrig/xmrig-proxy#303]
On Centos 7 
make gaves:

`
Linking CXX executable xmrig-proxy
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xmrig-proxy.dir/build.make:1593: xmrig-proxy] Error 1
make[1]: *** [CMakeFiles/Makefile2:64: CMakeFiles/xmrig-proxy.dir/all] Error 2
make: *** [Makefile:76: all] Error 2
`

No uuid.a or libuuid.a available on Centos 7

Solution:
After running cmake .. -DUV_LIB..., 
DO NOT RUN make!

First go to build/CMakeFiles/xmrig-proxy.dir 
and edit link.txt at the end
and change it 
from 
`-Wl,-Bstatic -luuid -Wl,-Bdynamic -lrt -ldl`
to 
`-luuid -lrt -ldl`

As previously on the line is another -Wl,-Bdynamic, that will use libuuid.so instead of inexistent libuuid.a, and left -lrt and -ldl dynamic

Now you can run make -j #

If you find my (very short) solution helpful, send some centi-monero :) at 
42ctyCDTo2uUXzonAMgGxXNrtX56CZ3ajMrrz1ubDeMNBuQo4NECciL4GPyEpbviUjYNLyHJGH59Hf2gZjVX2UPx9DRzo3Z

**Comment by kl1059** [comment]
I see this on Fedora 24.  Apparently RedHat doesn't distribute a package with libuuid.a because reasons.
link.txt last few characters:
-o xmrig-proxy -lssl -lcrypto -Wl,-Bstatic -luv -Wl,-Bdynamic -lmicrohttpd -lpthread -Wl,-Bstatic -luuid -Wl,-Bdynamic -lrt -ldl
becomes:
-o xmrig-proxy -lssl -lcrypto -luv -lmicrohttpd -lpthread -luuid -lrt -ldl
this gives a good link with the only difference being we dynamicly link libuv and libuuid

**Comment by Adi-Arad-Ro** [comment]
Very good finding.
On Centos 7 there is a libuv-static from epel, 
but generally RHEL seems to have a policy to drop out static libraries altogether on long term, 
so probably we will link everything dynamically.
Maybe the author of xmrig/xmrig-proxy will consider this when building the Makefile and/or link.txt for this Linux flavor.
Otherwise, there is this thread ;)

**Comment by srwx666** [comment]
https://github.com/xmrig/xmrig-proxy/issues/295#issuecomment-457719944

already discussed....

**Comment by Adi-Arad-Ro** [comment]
Great info, thank you.
I have to learn to use search...
Closing as duplicate.
