### ISSUE TITLE
Add FreeBSD build instructions

### ISSUE THREAD

**Issue by russoj88** [xmrig/xmrig-proxy#305]
I compiled and tested on FreeBSD 11.2 using the following
```
pkg install -y git cmake libuv openssl libmicrohttpd
git clone https://github.com/xmrig/xmrig-proxy.git
mkdir xmrig-proxy/build
cd xmrig-proxy/build
cmake ..
make
```

**Comment by DeadManWalkingTO** [comment]
> I compiled and tested on FreeBSD 11.2 

Thank you!

**Comment by russoj88** [comment]
I think this can be closed.  11.2 is past End of Life.

https://www.freebsd.org/releases/
