### ISSUE TITLE
Invalid nonce

### ISSUE THREAD

**Issue by PhatWheZ** [xmrig/xmrig-proxy#31]
Hi there,

Im trying to rely on using xmrig-proxy on a single host and have many miners connect through that machine to NiceHash. I have only set the following in the config.json on the proxy:
"url": "cryptonight.eu.nicehash.com:3355",
"user": "***My Wallet***.ID",
"pass": "x"

On a different PC with xmrig is have only changed the following in config.json:
"url": "192.168.1.1:3333",
"user": "Miner1",
"pass": "x",
"keepalive": true,
"nicehash": true

The miner connects to the proxy and begins to mine. Every hash that is found is rejected saying "Invalid nonce; is miner not compatible with NiceHash?"

Any help would be greatly appreciated

**Comment by xmrig** [comment]
Related #14 you can't use this proxy with nicehash.com
Thank you.
