### ISSUE TITLE
Xmrig-proxy v2.14.1 (Ubuntu) does not work with Xmrig-cpuminer v2.14.1

### ISSUE THREAD

**Issue by nickangel** [xmrig/xmrig-proxy#311]
After Monero’s fork I update all clients (xmrig cpuminer) to connect to the new Xmrig-Proxy.
It said that invalid shares are rejected, but when I connect the new clients to the old proxy , everything works fine.

**Comment by fakeptolemei** [comment]
same problem, it said Invalid shares are rejected after 10min of normal work

**Comment by xmrig** [comment]
Please show configs and proxy/miner output.
Thank you.

**Comment by nickangel** [comment]
![xmrig-proxy](https://user-images.githubusercontent.com/48511604/54336656-5254a200-4635-11e9-8e78-cffd48c3817d.jpg)
![xmrig-config](https://user-images.githubusercontent.com/48511604/54336657-5254a200-4635-11e9-86e7-c98171dd2d53.jpg)
![xmrig-proxy-config](https://user-images.githubusercontent.com/48511604/54336658-52ed3880-4635-11e9-852f-c6612d0fd1b5.jpg)
![xmrig](https://user-images.githubusercontent.com/48511604/54336659-52ed3880-4635-11e9-9ee3-ca86b8e84910.jpg)

**Comment by xmrig** [comment]
What is `10.0.200.251:7003`? It not provide required field `height`, `cn/r` algorithm now required to know blockchain height.
Thank you.

**Comment by nickangel** [comment]
This is my own pool. I finally figure it out. After your comments I found that the problem was with the pool. Now it's working.
Thank you for your support
