### ISSUE TITLE
cannot static compile

### ISSUE THREAD

**Issue by dotoremo** [xmrig/xmrig-proxy#315]
i've done it for xmrig but when im trying the proxy it fails ... under alpine 3.7

git clone https://github.com/xmrig/xmrig-proxy.git
Cloning into 'xmrig-proxy'...
remote: Enumerating objects: 217, done.
remote: Counting objects: 100% (217/217), done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 4129 (delta 124), reused 122 (delta 65), pack-reused 3912
Receiving objects: 100% (4129/4129), 1.27 MiB | 1.31 MiB/s, done.
Resolving deltas: 100% (3009/3009), done.
foo:/home# cd xmrig-proxy/
foo:/home/xmrig-proxy# mkdir build
foo:/home/xmrig-proxy# cd build
foo:/home/xmrig-proxy/build# cmake .. -DWITH_HTTPD=OFF -DWITH_TLS=OFF -DBUILD_ST
ATIC=ON -DUV_LIBRARY=/usr/lib/libuv.so
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/libuv.so  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_STATIC

-- Build files have been written to: /home/xmrig-proxy/build
foo:/home/xmrig-proxy/build# make
Scanning dependencies of target xmrig-proxy-notls
[  1%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/App.cpp.o
[  3%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/io/Json.cpp.o
[  4%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/io/Watcher.cpp.o
[  6%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/kernel/Entry.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/kernel/Process.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/kernel/Signals.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/net/Pool.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/net/Pools.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/tools/Arguments.cpp.o
[ 15%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/tools/Handle.cpp.o
[ 17%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/tools/String.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/config/CommonConfig.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/config/ConfigLoader.cpp.o
[ 22%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/config/ConfigWatcher.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/Console.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/crypto/Algorithm.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/crypto/keccak.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/log/BasicLog.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/log/ConsoleLog.cpp.o
[ 31%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/log/FileLog.cpp.o
[ 33%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/log/Log.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/net/Client.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/net/Job.cpp.o
[ 38%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/net/strategies/FailoverStrategy.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/net/strategies/SinglePoolStrategy.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/net/SubmitResult.cpp.o
[ 42%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/Platform.cpp.o
[ 44%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/core/Config.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/core/Controller.cpp.o
[ 47%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/log/AccessLog.cpp.o
[ 49%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/log/ShareLog.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/net/JobResult.cpp.o
[ 52%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/net/strategies/DonateStrategy.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/BindHost.cpp.o
[ 55%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Counters.cpp.o
[ 57%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/CustomDiff.cpp.o
[ 58%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Error.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Events.cpp.o
[ 61%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/events/Event.cpp.o
[ 63%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/events/MinerEvent.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Login.cpp.o
[ 66%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Miner.cpp.o
[ 68%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Miners.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Proxy.cpp.o
[ 71%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/ProxyDebug.cpp.o
[ 73%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Server.cpp.o
[ 74%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/splitters/nicehash/NonceMapper.cpp.o
[ 76%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/splitters/nicehash/NonceSplitter.cpp.o
[ 77%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/splitters/nicehash/NonceStorage.cpp.o
[ 79%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/splitters/simple/SimpleMapper.cpp.o
[ 80%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/splitters/simple/SimpleSplitter.cpp.o
[ 82%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/splitters/Splitter.cpp.o
[ 84%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Stats.cpp.o
[ 85%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/workers/Worker.cpp.o
[ 87%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/workers/Workers.cpp.o
[ 88%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/Summary.cpp.o
[ 90%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/xmrig.cpp.o
[ 92%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/App_unix.cpp.o
[ 93%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/base/io/Json_unix.cpp.o
[ 95%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/Platform_unix.cpp.o
[ 96%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/proxy/Uuid_unix.cpp.o
[ 98%] Building CXX object CMakeFiles/xmrig-proxy-notls.dir/src/common/log/SysLog.cpp.o
[100%] Linking CXX executable xmrig-proxy-notls
[100%] Built target xmrig-proxy-notls
foo:/home/xmrig-proxy/build# ./xmrig-proxy-notls 
unable to open "/home/xmrig-proxy/build/config.json".
No valid configuration found. Exiting.
foo:/home/xmrig-proxy/build# ldd xmrig-proxy-notls 
	/lib/ld-musl-x86_64.so.1 (0x70abaa573000)
	libuv.so.1 => /usr/lib/libuv.so.1 (0x70aba9fe9000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x70abaa573000)
./xmrig-proxy-notls --version
xmrig-proxy 2.14.1
 built on Mar 23 2019 with GCC 6.4.0
 features: 64-bit

libuv/1.17.0
i also have tryed to add in CMakeLists.txt 
if (BUILD_STATIC)
    set(CMAKE_EXE_LINKER_FLAGS " -static")
endif()
but it doesnt work , it 100% compiles but when i try to run , is ( Killed )

**Comment by djfinch** [comment]
You are trying to link with dynamic lib (*.so) but you have to link against static lib (*.a)...
-DBUILD_STATIC=ON is not valid variable. This can be omitted though.

**Comment by 0xman** [comment]
I don't see the point of statically compiling xmrig-proxy unless your throwing it on other servers to use witch makes no sense

**Comment by djfinch** [comment]
@0xman Inject it into Docker container later? ...for example...

**Comment by marcel1974** [comment]
All of xmrig suite compile with no error..... Just xmrig-proxy.
I am using Slackware 14.2 for all off xmrig and are much happier with it than with UB (any version). Have to find the issue every  time that solves the problem by tweaking the build file. Please

[100%] Linking CXX executable xmrig-proxy
/usr/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
CMakeFiles/xmrig-proxy.dir/build.make:2177: recipe for target 'xmrig-proxy' fail                                                                              ed
make[2]: *** [xmrig-proxy] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-proxy.dir/all' fail                                                                              ed
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by daemon2k** [comment]
> All of xmrig suite compile with no error..... Just xmrig-proxy.
> I am using Slackware 14.2 for all off xmrig and are much happier with it than with UB (any version). Have to find the issue every time that solves the problem by tweaking the build file. Please
> 
> [100%] Linking CXX executable xmrig-proxy
> /usr/bin/ld: cannot find -luuid
> collect2: error: ld returned 1 exit status
> CMakeFiles/xmrig-proxy.dir/build.make:2177: recipe for target 'xmrig-proxy' fail ed
> make[2]: *** [xmrig-proxy] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-proxy.dir/all' fail ed
> make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

Hi! Have you resolved this error? I have same problem.

**Comment by djfinch** [comment]
Missing libuuid?

**Comment by marcel1974** [comment]
Missing libuuid? Did not solve the problem. I have installed it from github and from slackbuild website.
CMakeFiles/xmrig-proxy.dir/link.txt
last line to
-Wl,-Bdynamic -luuid
rather than
-Wl,-Bstatic -luuid

Why I have to change the line before make to resolves the problem I left for the developers. It was not needed by the other xmrig products.

**Comment by djfinch** [comment]
This is not an issue dev overlooked here. As per your fix....you have to disable linker to include static libuuid (.a) and force to use dynamic one (.so). So I suppose static library for uuid is not present there. Have you tried to install libuuid-dev? I don't have any Slackware to test it on...

**Comment by marcel1974** [comment]
I am not working on ubuntu. I compile from source. I am running Slackware 14.2 32-bit on my proxy's servers. The libuv I was using works fine for xmrig-amd xmrig-nv xmrig-cpu. I have compiles from source and that will include all dev files for libuv

**Comment by marcel1974** [comment]
Still have compile errors!

**Comment by marcel1974** [comment]
I still have the same problem. I have updated libtools I have installed patches for gcc 5.50. Libuv installed. Libuuid installed. All files from libuuid-dev installed on the system. I need more information on the file locations of libuuid.a libuuid.so Dont know why all other xmrig products compile without an error. Please give more information how to compile on Linux Slackware 14.2 32-Bit and Linux Slackware 14.2 64-Bit

File locations of libuuid-dev
/usr/include/uuid/uuid.h
/usr/lib/i386-linux-gnu/libuuid.a
/usr/lib/i386-linux-gnu/libuuid.so
/usr/lib/i386-linux-gnu/pkgconfig/uuid.pc

lrwxrwxrwx 1 root root 6 Oct 10 05:27 ld -> ld.bfd
whereis ld 
ld: /usr/bin/ld.bfd /usr/bin/ld /usr/bin/ld.gold /usr/man/man1/ld.1.gz /usr/info/ld.info.gz
wheris uuid
uuid: /usr/bin/uuid /usr/include/uuid /usr/include/uuid.h /usr/man/man3/uuid.3.gz /usr/man/man1/uuid.1.gz
locate libuuid.a
/usr/lib/i386-linux-gnu/libuuid.a

locate libuuid.so
/usr/lib/libuuid.so
/usr/lib/i386-linux-gnu/libuuid.so
/lib/libuuid.so.1.3.0
/lib/libuuid.so.1

I need more info how to resolve the problem.
