### ISSUE TITLE
cryptonight-pico doesn't work ... config parse error

### ISSUE THREAD

**Issue by aleqx** [xmrig/xmrig-proxy#318]
If I use `cryptonight-pico` in the json config (as per Algorithm.cpp and STRATUM_EXT.md) then xmrig-proxy exists with an error saying

```
No valid configuration found. Exiting.
```

If I change `cryptonight-pico` to `cryptonight-lite` in the json then it starts, but it starts with "cn-lite/auto" instead of "cn-pico/trtl".

I see `#ifndef XMRIG_NO_CN_PICO` in https://github.com/xmrig/xmrig-proxy/blob/master/src/common/crypto/Algorithm.cpp#L87 ... and I didn't define that constant, so I'd expect cn-pico to be enabled.

Full config:

```
{
    "access-log-file": "/var/log/cn-turtle-access.log",
    "algo": "cryptonight-pico",
    "api": {
        "port": 0,
        "access-token": null,
        "id": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "background": false,
    "bind": [
        "0.0.0.0:5562",
        "[::]:5562"
    ],
    "colors": true,
    "custom-diff": 1000000,
    "donate-level": 0,
    "log-file": "/var/log/cn-turtle.log",
    "mode": "nicehash",
    "pools": [
        {
            "url": "pool.domain.com:1234",
            "user": "wallet_address",
            "pass": "x",
            "rig-id": null,
            "keepalive": true,
            "variant": "trtl",
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "retries": 100,
    "retry-pause": 3,
    "reuse-timeout": 0,
    "user-agent": null,
    "verbose": false,
    "debug": false,
    "watch": true,
    "workers": true
}
```

**Comment by aleqx** [comment]
If I keep "crytptonight-lite" and variant "trtl" then xmrig-proxy starts using cn-lite/auto ... but if I want to mine thorugh it using xmrig (the miner) then xmrig says:

```
[2019-04-02 04:14:42] [proxy:5562] error: "No compatible algorithm found, change algo option in your miner.", code: -1
[2019-04-02 04:14:42] [proxy:5562] read error: "end of file"
```

Looking at https://github.com/xmrig/xmrig-proxy/blob/master/src/common/crypto/Algorithm.cpp#L148 I don't see why it should fail with "cryptonight-lite"

Any clues?

**Comment by xmrig** [comment]
I can't reproduce this issue, config you provided is fully correct (format little outdated, but it just cosmetic) and works with latest release. cn-pico enabled by default, it controlled by cmake option `-DWITH_CN_PICO=ON` or `OFF`.
Thank you.

**Comment by aleqx** [comment]
The above error is from 2.14.2 pulled from less than 24h ago. I didn't use `-DWITH_CN_PICO=ON` because the code has `#ifndef`. Are you saying I need to manually enable pico by adding `-DWITH_CN_PICO=ON`? It should work fine if I just do cmake + make, right?

**Comment by xmrig** [comment]
`-DWITH_CN_PICO=ON` is default value, and cn-pico should be enabled, but in your cause something wrong, `OFF` value adds `XMRIG_NO_CN_PICO` definition.
Thank you.

**Comment by aleqx** [comment]
I did search for CN_PICO in all generated files, and nothing is generated. I'll wipe and try again (it was pulled over 2.8.2, though that shouldn't matter). Weird ...

**Comment by aleqx** [comment]
Wiped, cloned, recompiled ... now it works with the same config file. Can't explain it, but don't have the time to be curious. Closing.
