### ISSUE TITLE
XMRig-Proxy crash when accessing API when having near 1000 miners

### ISSUE THREAD

**Issue by johndoebt** [xmrig/xmrig-proxy#319]
Hi,
My XMRig-Proxy having around 990 miners mining on it and it crashed when I'm using http://proxy.xmrig.info to viewing it with the following error:

`Fatal error in GNU libmicrohttpd daemon.c:2656: Failed to remove listen FD from epoll set`

The Proxy is protected with `access-token`, compiled with GCC 6.3.0 on Debian 9 x86_64 without allowing to modify config remotely.

Thank you.

**Comment by xmrig** [comment]
Did you increase limit to open files? https://github.com/xmrig/xmrig-proxy/wiki/Ubuntu-setup
Thank you.

**Comment by johndoebt** [comment]
Yes I did, in fact, my open files and limits.conf numbers are even higher than in that wiki

```
*         hard    nofile      5000000
*         soft    nofile      5000000

cat /proc/sys/fs/file-max
20971520
```

and I'm running the proxy as root.

**Comment by xmrig** [comment]
Run `ulimit -n` likely it show 1024, because very high values ignored.
Thank you.

**Comment by johndoebt** [comment]
Oh yes, it did, I'll put the value in your wiki to see if it crash again.

Thank you.

**Comment by johndoebt** [comment]
Yes, the issue still exist, when I try to add it into http://proxy.xmrig.info the proxy crash immediately and the web panel show "Failed to fetch"

**Comment by xmrig** [comment]
If crash still happen around 1000 connections it means, ulimit not applied, who it happen depends of how you start proxy, better option restart whole system.

**Comment by johndoebt** [comment]
I did rebooted my system after editing `/etc/security/limits.conf` and I've put the `file-max` to `sysctl.conf`, I did check and the ulimit value is as expected, if I remove all the "increase limit" then it would resulted in tons of DNS error of proxy.
