### ISSUE TITLE
config.json:1205: Invalid value.No pool URL supplied. Exiting. ?

### ISSUE THREAD

**Issue by BlkHoleGit** [xmrig/xmrig-proxy#32]
Whenever I edit the pool URL in the config file I get the above error...  I can edit any other aspect of the file, but whenever I touch this vector it breaks; even if I put the original URL back in the file it will error...  What am I doing wrong??  ;)

{
    "algo": "cryptonight",  // cryptonight (default) or cryptonight-lite
    "av": 0,                // algorithm variation, 0 auto select
    "background": false,    // true to run the miner in the background
    "colors": true,         // false to disable colored output    
    "cpu-affinity": null,   // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
    "cpu-priority": null,   // set process priority (0 idle, 2 normal to 5 highest)
    "donate-level": 5,      // donate level, mininum 1%
    "log-file": null,       // log all output to a file, example: "c:/some/path/xmrig.log"
    "max-cpu-usage": 100,    // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.  
    "print-time": 60,       // print hashrate report every N seconds
    "retries": 5,           // number of times to retry before switch to backup server
    "retry-pause": 5,       // time to pause between retries
    "safe": false,          // true to safe adjust threads and av settings for current CPU
    "syslog": false,        // use system log for output messages
    "threads": null,        // number of miner threads
    "pools": [
        {
            "url": “monerohash.com:3333”,   // URL of mining server
            "user": "thisiswhereIputmywallet",                        // username for mining server
            "pass": "x",                       // password for mining server
            "keepalive": true,                 // send keepalived for prevent timeout (need pool support)
            "nicehash": false                  // enable nicehash/xmrig-proxy support
        }
    ],
    "api": {
        "port": 0,                             // port for the miner API https://github.com/xmrig/xmrig/wiki/API
        "access-token": null,                  // access token for API
        "worker-id": null                      // custom worker-id for API
    }
}

**Comment by xmrig** [comment]
You use different quotation mark, you use `“` instead of `"`, that cause error.
Also it config from CPU miner not the proxy.
Thank you.
