### ISSUE TITLE
diffuculty adjustement : please eplain logic?

### ISSUE THREAD

**Issue by bluemelatonin** [xmrig/xmrig-proxy#33]
hello,
the new version of xmrig-proxy permit adjust dificulty per worker . 

But i'm not sure understand perfectly this possibility . 

for exemple, my pool requiere a minimal difficulty 1063. 

if i have 9 worker, with aproximatilvy 320h/s capability per worker, what it's the best configuration for this? 

what is the logic for adjust the dificulty?

I hope my text is comprehensible, my english is very bad and i haven't use traduction tools ...

**Comment by xmrig** [comment]
You can simple set fixed diff 10000 to prevent pull increase diff to very high values.
Custom diff only can be lower than proxy->pool diff and only useful to prevent timeouts (10 min) if miner does't support keepalvie.
