### ISSUE TITLE
 xmrig-proxy doesn't work with algo rx/wow

### ISSUE THREAD

**Issue by GjBrutello** [xmrig/xmrig-proxy#330]
Miner xmrig-2.15.4-beta2-randomwow work good only if connected to wownero pools but don't work with a xmrig-proxy/2.15.3-beta.

Log of xmrig-proxy:
 * ABOUT        xmrig-proxy/2.15.3-beta MSVC/2017
 * LIBS         libuv/1.29.1 OpenSSL/1.1.1b
 * MODE         nicehash
 * ALGO         cryptonight
 * POOL #1      pool.wowne.ro:3333 variant auto
 * BIND #1      0.0.0.0:10888
 * BIND #2      [::]:10888
 * COMMANDS     hashrate, connections, verbose, workers
[2019-06-22 05:11:32.593] verbose: 1
[2019-06-22 05:12:30.423] 0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 1) +9/-9
[2019-06-22 05:12:55.795] #000 new job from pool.wowne.ro:3333 diff 2586 algo invalid height 117281
[2019-06-22 05:13:17.195] #000 new job from pool.wowne.ro:3333 diff 2586 algo invalid height 117282
Log of miners from the xmrig-proxy:
[2019-06-22 05:21:47.769] Unknown/unsupported algorithm detected, reconnect
[2019-06-22 05:21:47.772] [127.0.0.1:10888] login error code: 6
--------------------
Log of the miner to wownero pool with ssl connection:
 * COMMANDS     hashrate, pause, resume
[2019-06-22 05:48:57.111] use pool pool.wowne.ro:5556 TLSv1.2 127.128.0.1
[2019-06-22 05:48:57.111] fingerprint (SHA-256): "a137ccfe9a4d6f8bd140cd6c58cf8e
0a866a2c196abe8d16540a605b8fe5fef0"
[2019-06-22 05:48:57.111] new job from pool.wowne.ro:5556 diff 10000 algo rx/wow
 height 117289
[2019-06-22 05:48:58.875] Thread 0 started updating RandomX dataset
[2019-06-22 05:48:58.890] Thread 1 started updating RandomX dataset
[2019-06-22 05:48:58.906] READY (CPU) threads 3(3) huge pages 0/3 0% memory 3072
 KB
[2019-06-22 05:48:58.906] Thread 2 started updating RandomX dataset
[2019-06-22 05:49:00.169] new job from pool.wowne.ro:5556 diff 18182 algo rx/wow
 height 117289

**Comment by xmrig** [comment]
Please wait for next release, on network level `rx/wow` required new additional field, current proxy versions know nothing about it.
Thank you.

**Comment by poppy7921** [comment]
xmrig-proxy-2.16.0-beta doesn't work with algo rx/wow
display No valid configuration found. Exiting

**Comment by xmrig** [comment]
@poppy7921 please show your config.
Thank you.

**Comment by poppy7921** [comment]
{
    "access-log-file": null,
    "access-password": null,
    "algo": "rx/wow",
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": true,
        "host": "127.0.0.1",
        "port": 8880,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 443,
            "tls": false
        },
        {
            "host": "0.0.0.0",
            "port": 444,
            "tls": false
        }
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "url": "mine.wow.fairpool.xyz:6090",
            "user": "Wo3sd3PnNy6NhXbAdAXEP8FpJ5xgHH3mPQM5NupifyoJB4QAgfA62WhgxezgaZ6kFKBqLzVxrqmFDWPCtsPXrVqc2H7F9KHXR",
            "pass": "x",
            "rig-id": null,
            "keepalive": true,
            "variant": -1,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "daemon-poll-interval": 1000
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}

**Comment by xmrig** [comment]
@poppy7921 please use `"variant": "rx/wow",`

**Comment by poppy7921** [comment]
Thank you.It‘s OK!

**Comment by poppy7921** [comment]
But API does not work properly. 
Visit Web pages http://127.0.0.1:8880 or http://127.0.0.1:8880/workers.json
--------Show the following-------
{
    "status": 404,
    "error": "Not Found"
}
---------------------------------

**Comment by xmrig** [comment]
@poppy7921 https://github.com/xmrig/xmrig/issues/1007
use http://127.0.0.1:8880/1/summary and http://127.0.0.1:8880/1/workers

**Comment by poppy7921** [comment]
So,how to join it to http://proxy.xmrig.info/ ?
