### ISSUE TITLE
error: "Unauthenticated", code: -1

### ISSUE THREAD

**Issue by seanwhe** [xmrig/xmrig-proxy#336]
Not sure if this is because of some change in config.json that I am not setting or setting incorrectly but I just noticed it comes up when running proxy without any miners connecting. It repeats on a steady basis.

========================
~$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               60
Model name:          Intel Core Processor (Haswell, no TSX, IBRS)
Stepping:            1
CPU MHz:             3292.374
BogoMIPS:            6584.74
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ibrs ibpb fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat

========================
~$ uname -a
Linux ops-mng-vmx-xmrigpxy 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

========================

~$ xmrig-proxy -V
xmrig-proxy 2.99.0-beta
 built on Aug  5 2019 with GCC 7.4.0
 features: 64-bit

libuv/1.18.0
OpenSSL/1.1.1

===================
{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 8080,
        "access-token": "null",
        "restricted": false
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 3333,
            "tls": false
        }
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 2,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": "cn/r",
            "url": "pool.supportxmr.com:3333",
            "user": "854sqm2Cm4TB2XgPHWqSPSbnFAe3SMzdEDzZHpukQ8NHBPFropbnkFmEKiZPgwjMFC9PTjaFscR2UU6ZwFCqJzGMUiZVbTM",
            "pass": "xmrig-proxy:miners@somedomain.com",
            "rig-id": "xmrig-proxy",
            "keepalive": true,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "daemon-poll-interval": 1000
        },
        {
            "algo": "cn/r",
            "url": "pool.minexmr.com:4444",
            "user": "854sqm2Cm4TB2XgPHWqSPSbnFAe3SMzdEDzZHpukQ8NHBPFropbnkFmEKiZPgwjMFC9PTjaFscR2UU6ZwFCqJzGMUiZVbTM",
            "pass": "xmrig-proxy:miners@somedomain.com",
            "rig-id": "xmrig-proxy",
            "keepalive": true,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "daemon-poll-interval": 1000
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": true,
    "watch": true,
    "workers": true
}

====================
 * ABOUT        xmrig-proxy/2.99.0-beta gcc/7.4.0
 * LIBS         libuv/1.18.0 OpenSSL/1.1.1 
 * MODE         nicehash
 * POOL #1      pool.supportxmr.com:3333 algo cn/r
 * POOL #2      pool.minexmr.com:4444 algo cn/r
 * BIND #1      0.0.0.0:3333
 * COMMANDS     hashrate, connections, verbose, workers
 * HTTP API     0.0.0.0:8080
 * ABOUT        xmrig-proxy/2.99.0-beta gcc/7.4.0
 * LIBS         libuv/1.18.0 OpenSSL/1.1.1 
 * MODE         nicehash
 * POOL #1      pool.supportxmr.com:3333 algo cn/r
 * POOL #2      pool.minexmr.com:4444 algo cn/r
 * BIND #1      0.0.0.0:3333
 * COMMANDS     hashrate, connections, verbose, workers
 * HTTP API     0.0.0.0:8080
[2019-08-05 17:56:05.420] #000 use pool pool.supportxmr.com:3333  94.130.12.30 
[2019-08-05 17:56:05.420] #000 new job from pool.supportxmr.com:3333 diff 10000 algo cn/r height 1894241
...
[2019-08-05 18:11:05.667] 0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0
[2019-08-05 18:12:05.733] 0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0
>>>
[2019-08-05 18:12:18.927] [pool.supportxmr.com:3333] error: "Unauthenticated", code: -1
[2019-08-05 18:12:18.927] #000 no active pools, stop
<<<
[2019-08-05 18:12:21.559] #000 use pool pool.supportxmr.com:3333  94.130.12.27 
[2019-08-05 18:12:21.559] #000 new job from pool.supportxmr.com:3333 diff 10000 algo cn/r height 1894246
[2019-08-05 18:13:05.796] 0.00 kH/s, shares: 0/0 +0, upstreams: 1, miners: 0 (max 0) +0/-0

**Comment by seanwhe** [comment]
I have not yet noticed the same error while the proxy has miners connected.

**Comment by xmrig** [comment]
It pool issue, connection expired, but pool don't close it.
Thank you.
