### ISSUE TITLE
[2.99.1-beta] Incorrect Bind

### ISSUE THREAD

**Issue by seanwhe** [xmrig/xmrig-proxy#338]
Despite asking to bind to specific IP-address, proxy reports bind to all ip-addresses [0.0.0.0]

============
$ hostnamectl
   Static hostname: ops-mng-vmx-xmrigpxy
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 61ed16c43a3b47339f42f9a693f2315f
           Boot ID: edf55e99239945bba04ffe4ac893b539
    Virtualization: kvm
  Operating System: Ubuntu 18.04.3 LTS
            Kernel: Linux 4.15.0-55-generic
      Architecture: x86-64

============
$ uname -a
Linux ops-mng-vmx-xmrigpxy 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

===========
$ xmrig-proxy -V
xmrig-proxy 2.99.1-beta
 built on Aug 12 2019 with GCC 7.4.0
 features: 64-bit

libuv/1.18.0
OpenSSL/1.1.1

===============

 * ABOUT        xmrig-proxy/2.99.1-beta gcc/7.4.0
 * LIBS         libuv/1.18.0 OpenSSL/1.1.1 
 * MODE         nicehash
 * POOL #1      pool.supportxmr.com:3333 algo cn/r
 * BIND #1      0.0.0.0:3333
 * BIND #2      [::]:3333
 * COMMANDS     hashrate, connections, verbose, workers
 * HTTP API     192.168.4.5:8080
[2019-08-12 20:52:14.999] #000 use pool pool.supportxmr.com:3333  94.130.12.27 
[2019-08-12 20:52:14.999] #000 new job from pool.supportxmr.com:3333 diff 10000 algo cn/r height 1899388
[2019-08-12 20:52:19.613] #000 accepted (1/0+0) diff 10000 ip 192.168.1.254 (197 ms)
...

========

...
   "background": false,
   "bind": {
      "host": "192.168.4.5",
      "port": 3333,
      "tls": false
   },
   "colors": true,
...

**Comment by xmrig** [comment]
`bind` is a JSON array, not a object, proper bind option should looks like:
```json
"bind": [
    {
        "host": "192.168.4.5",
        "port": 3333,
        "tls": false
    }
],
```

**Comment by seanwhe** [comment]
You are correct. Thanks
