### ISSUE TITLE
Critical error!!! MAX WORKERS 999

### ISSUE THREAD

**Issue by romankosoj** [xmrig/xmrig-proxy#34]
Программа не выдерживает более 1000 майнеров, дальше майнеры не подключаются, программа отвергает их. В логах максимальный COUNT 999

Как исправить данную проблему?

The program does not stand more than 1000 miners, then the miners do not connect, the program rejects them. In logs max COUNT 999

How can I fix this problem?

**Comment by serafim61** [comment]
Для вас же написано в описании If you use Linux and want handle more than 1000 connections, you need increase limits of open files. https://github.com/xmrig/xmrig-proxy/wiki/Ubuntu-setup

**Comment by romankosoj** [comment]
Спасибо!
