### ISSUE TITLE
Can't access http api remotely

### ISSUE THREAD

**Issue by SnShine** [xmrig/xmrig-proxy#344]
Hello team,

I've set `--http-enabled --http-port=9000 --http-access-token=my_token_example --http-no-restricted` flags while starting the proxy in latest version of proxy. I can access the proxy api locally `http://127.0.0.1:9000/1/workers` but when given ip address instead of 127.0.0.1 can't access it in local machine or from a remote machine. 

This is using the latest version only. Older versions worked fine I guess.

**Comment by xmrig** [comment]
`--http-host=0.0.0.0` (IPv4) or `--http-host=::` (IPv4 + IPv6) or specific address.
Thank you.

**Comment by SnShine** [comment]
It worked, thanks. Can you add these new flags in README? It'd be easier for others too.
