### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by aconn21** [xmrig/xmrig-proxy#345]
xmrig-proxy version: 3.2.0
linux version: Debian 10 "buster"

example API config:
"api": {
        "port": 8080,
        "access-token": "test",
        "worker-id": "blah",
        "ipv6": false,
        "restricted": false
    },

Nothing is listening on that port or any other port I try.

**Comment by xmrig** [comment]
API format changed in v3, please check config example https://github.com/xmrig/xmrig-proxy/blob/master/src/config.json#L5
Thank you.

**Comment by aconn21** [comment]
Thanks yep that is working, this should be updated: https://github.com/xmrig/xmrig-proxy/wiki/API
