### ISSUE TITLE
adding coins to proxy ARQ & SCALA

### ISSUE THREAD

**Issue by OIEIEIO** [xmrig/xmrig-proxy#348]
Could add ArQma and Scala coins to be able to use your proxy?

**Comment by xmrig** [comment]
ArQmA added in evo branch as `rx/arq` (forgot add it earlier), but Scala no, I don't support this coin.
Thank you.

**Comment by OIEIEIO** [comment]
ok ...I have added both arq and scala in my fork if there is interest down the road.

**Comment by tuananh19961** [comment]
Scala Proxy
[Uploading xmrig-nevo-proxy.tar.gz…]()

**Comment by tuananh19961** [comment]
Scala Proxy 
[xmrig-nevo-proxy.tar.gz](https://github.com/xmrig/xmrig-proxy/files/13628268/xmrig-nevo-proxy.tar.gz)
