### ISSUE TITLE
Question: command line configuration for --coin=monero

### ISSUE THREAD

**Issue by kl1059** [xmrig/xmrig-proxy#349]
xmrig allows --coin=monero so that we can auto switch when the fork happens

is there a way to configure xmrig-proxy from the command line in a similar way?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-proxy/releases/tag/v3.2.0 it should works exactly same way.
Thank you.

**Comment by kl1059** [comment]
using config.json it seems to work but from command line i am trying to guess a permutation that will let me log on to the pool.

if i specify --algo cn/r i can log on to the pool

if i specify --coin=monero it fails whereas with config.json it works

 * ABOUT        xmrig-proxy/3.2.0 gcc/6.3.1
 * LIBS         libuv/1.7.5 OpenSSL/1.0.2k 
 * MODE         nicehash

./xmrig-proxy: unrecognized option '--coin=monero'
or
./xmrig-proxy: unrecognized option '--coin'

this is on a fedora 24 build in case there is a command parse dependency

**Comment by xmrig** [comment]
You are right, I confirm the bug. Thank you.

**Comment by kl1059** [comment]
*** src/core/config/Config_platform.h.1	2019-10-30 19:21:33.826041191 -0500
--- src/core/config/Config_platform.h	2019-10-30 19:22:33.819736074 -0500
***************
*** 48,49 ****
--- 48,50 ----
      { "algo",              1, nullptr, IConfig::AlgorithmKey      },
+     { "coin",              1, nullptr, IConfig::CoinKey           },
      { "api-worker-id",     1, nullptr, IConfig::ApiWorkerIdKey    },

**Comment by kl1059** [comment]
adding a line after line 48 in src/core/config/Config_platform.h
"coin",              1, nullptr, IConfig::CoinKey
seems to clear this up for me

**Comment by xmrig** [comment]
Fixed in v3.2.1 and v4.5.0-beta.
