### ISSUE TITLE
Miner not Re-connecting after connection loss

### ISSUE THREAD

**Issue by BKdilse** [xmrig/xmrig-proxy#359]
Hi,

Using v5 of XMRig, and when an internet connection to pool is lost, the miner doesn't get any shares accepted.  I can see it hashing away, but nothing is accepted.

A restart of the miner fixes the issue.

Is there a fix for this, or a config change?

**Comment by xmrig** [comment]
Please provide all possible details, miner log, config file (without wallets), information about your internet connection and how it lost exactly.
Thank you.

**Comment by BKdilse** [comment]
I haven't enable logging, but I'll do so and update here.

All configs are using the default template, with pool details, wallet etc being the only changes.

Pools are hosted internally, and the miners are on the same network.  When I restart pool for updates, the problem occurs.

I'll upload a config shortly.

**Comment by xmrig** [comment]
> Pools are hosted internally, and the miners are on the same network.

It means miners use pool IP address without DNS name?
Thank you.

**Comment by BKdilse** [comment]
Sorry, logged this in the wrong place, just realized it's this is xmrig-proxy.  Let me raise it in xmrig.
