### ISSUE TITLE
what's the different between one upstream and ten upstream?

### ISSUE THREAD

**Issue by bitcoin-hub** [xmrig/xmrig-proxy#361]
Before, i used xmrig-proxy 3.2 and xmrig 3.2 for mining. The proxy showed one upstream and ten miners. After, i use xmrig-proxy 5.0 and xmrig 5.0 for mining and the proxy shows ten upstream and ten miners. My system is ubuntu16. I would like to know what causes the difference and what's the different between one upstream and ten upstream? Thank you.

**Comment by xmrig** [comment]
Looks like you changed `mode` option to `simple` https://github.com/xmrig/xmrig-proxy/blob/master/src/config.json#L33
Thank you.
