### ISSUE TITLE
i got invalid job id and low share difficulty

### ISSUE THREAD

**Issue by bitcoin-hub** [xmrig/xmrig-proxy#363]
{
    "access-log-file": null,
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null,
        "ipv6": false,
        "restricted": true
    },
    "background": false,
    "bind": [
        "0.0.0.0:80"
    ],
    "colors": true,
    "donate-level": 0,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {"algo":"rx/0",
            "coin": "monero",
            "url": "pool.supportxmr.com:8080",
            "user": "437...+5555",
            "pass": "@gmail.com",
            "keepalive": true,
            "variant": 0,
            "tls": false,
            "tls-fingerprint": null
        }
    ],
    "retries": 5,
    "retry-pause": 3,
    "syslog": false,
    "verbose": false,
    "workers": true
}

**Comment by xmrig** [comment]
What proxy version do you use? config looks very outdated. If recent version please show log.
Thank you.

**Comment by bitcoin-hub** [comment]
> What proxy version do you use? config looks very outdated. If recent version please show log.
> Thank you.

I got config.json from xmrig.com. But when i use config.json from source and chang the pool port from 8080 to 5555, it seems work fine.

**Comment by bitcoin-hub** [comment]
> What proxy version do you use? config looks very outdated. If recent version please show log.
> Thank you.

the version is 5.0.1
