### ISSUE TITLE
For ARM (Raspberry PI 3)

### ISSUE THREAD

**Issue by ZloyZinger** [xmrig/xmrig-proxy#37]
Hi!
I have this error...  Please, help!

armuser@Raspberry:~/xmrig-proxy/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib/arm-linux-gnueabihf/libuv.a -DWITH_HTTPD=OFF
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/arm-linux-gnueabihf/libuv.a  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/armuser/xmrig-proxy/build

armuser@Raspberry:~/xmrig-proxy/build$ make
Scanning dependencies of target xmrig-proxy
[  2%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/api/Api.cpp.o
[  4%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/api/ApiState.cpp.o
In file included from /home/armuser/xmrig-proxy/src/3rdparty/rapidjson/document.h:20:0,
                 from /home/armuser/xmrig-proxy/src/api/ApiState.cpp:39:
/home/armuser/xmrig-proxy/src/3rdparty/rapidjson/reader.h:35:23: fatal error: emmintrin.h: No such file or directory
compilation terminated.
CMakeFiles/xmrig-proxy.dir/build.make:86: recipe for target 'CMakeFiles/xmrig-proxy.dir/src/api/ApiState.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/api/ApiState.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-proxy.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xmrig** [comment]
Fixed. For curiosity, does Raspberry PI 3 CPU support hardware aes?
`cat /proc/cpuinfo` aes flag.
Thank you.

**Comment by ZloyZinger** [comment]
Thank you.

I think not. But I could not find the exact information on this processor and AES (Cortex-A53, bcm2837).
https://en.wikipedia.org/wiki/ARM_Cortex-A53. In www.broadcom.com no information.

**Comment by ZloyZinger** [comment]
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 76.80
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

**Comment by ZloyZinger** [comment]
New error...

armuser@Raspberry:~$ cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib/arm-linux-gnueabihf/libuv.a -DWITH_HTTPD=OFF
CMake Error: The source directory "/home" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by xmrig** [comment]
`mkdir build` in source directory first, then `cd build`

Thanks for cpuinfo, it strange, it should be ARMv8, not ARMv7.

**Comment by ZloyZinger** [comment]
I'm surprised myself

**Comment by ZloyZinger** [comment]
Working! Thank you!

**Comment by ZloyZinger** [comment]
you can add the user guide for ubuntu arm on the wiki


sudo apt install git build-essential cmake libuv1-dev uuid-dev libmicrohttpd-dev
git clone https://github.com/xmrig/xmrig-proxy.git
cd xmrig-proxy
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib/arm-linux-gnueabihf/libuv.a -DWITH_HTTPD=OFF
make

**Comment by PhatWheZ** [comment]
I am unable to get the libuv1 using Raspbian Jessie. I can only get libuv0,10-dev which wont compile when running 'make'

**Comment by StifflersMoM69** [comment]
I am unable to get the libuv1 using Raspbian Jessie.

**Comment by xmrig** [comment]
You can compile recent libuv from source.
Probably you can use [jessie-backports](https://packages.debian.org/jessie-backports/libuv1) or download and install deb file directly, not check it but should work.
Thank you.
