### ISSUE TITLE
error code 6: unknown algorithm, make sure you set "algo" or "coin" option".

### ISSUE THREAD

**Issue by antibomb007** [xmrig/xmrig-proxy#378]
![Screenshot_21](https://user-images.githubusercontent.com/11909222/71668808-ee09f700-2d9c-11ea-818e-0782e5b0f9c9.png)
![Screenshot_22](https://user-images.githubusercontent.com/11909222/71668827-ffeb9a00-2d9c-11ea-9a8b-50e2de142796.png)
I got error when using xmrig-proxy 5.5.0 on minexmr's pool. Any idea how to solve this?
Thank you.

**Comment by xmrig** [comment]
Use `"algo": "rx/0",` or `"coin": "monero",` https://github.com/xmrig/xmrig-proxy/blob/master/src/config.json#L37 per pool.
Right now you use outdated config, `algo` option is no longer a global option.
Thank you.

**Comment by antibomb007** [comment]
> Use `"algo": "rx/0",` or `"coin": "monero",` https://github.com/xmrig/xmrig-proxy/blob/master/src/config.json#L37 per pool.
> Right now you use outdated config, `algo` option is no longer a global option.
> Thank you.

i already tried with only "coin": "monero", or "algo": "rx/0", but still getting same response.
