### ISSUE TITLE
Daemon mining hash rate

### ISSUE THREAD

**Issue by manianac** [xmrig/xmrig-proxy#381]
When mining to a daemon, I noticed the hashrate is 0.  I assume this is because it is handing out the network difficulty to each individual miner.  Is it possible to decrease the difficulty so that the miners show they are there, but only forward found blocks?  Or is this not feasible since it is not a pool?

**Comment by xmrig** [comment]
#376

1. Update to recent version.
2. Use `"custom-diff-stats": true,` and `"custom-diff"` with some value (or set up diff individually).

Thank you.
