### ISSUE TITLE
Looking for cryptonight proxy

### ISSUE THREAD

**Issue by codewatafak** [xmrig/xmrig-proxy#39]
I trying to use xmrig-proxy with electroneum coin (base on Monero and cryptonight), then failed all results is invalid.

I like XMRig very much, lightweight and easy to install.

Any suggestion to me?

Thanks

**Comment by PhatWheZ** [comment]
What is your config?
after the boom of interest i switched my miner from Nanopool to Electroneum
without issues.

My changes only required me creating and adding my ETN wallet ID

**Comment by codewatafak** [comment]
My config: https://pastebin.com/eb2Q85Ak

I'm using xmr-stak-cpu and just change url in xmr-stak-cpu config file with proxy server, connection ok but always "Results reject by the pool" and Proxy can't detect hashrate

**Comment by PhatWheZ** [comment]
Use the xmrig miner along with the xmrig-proxy, you have not included a
flag:
    "pools": [
        {
            "url": "<Internal IP Address>:3333",   // URL of mining server
            "user": "<My Device that Mines>",                        //
username for mining server
            "pass": "x",                       // password for mining server
            "keepalive": true,                 // send keepalived for
prevent timeout (need pool support)
            "nicehash": true                  // enable
nicehash/xmrig-proxy support
        }
    ],

Otherwise try adding the nicehash flag to xmr-stak-cpu, but i dont know if
that will work or not. I have not tested it since moving to XMRIG

**Comment by codewatafak** [comment]
Thanks you, its working now. Added "nicehash": true in xmrig-proxy and nicehash flag on xmr-stak-cpu working well

But i dont use nicehash for sure.

Thanks you so much.

**Comment by xmrig** [comment]
nicehash support required on miner side, so change nicehash flag is required for xmr-stak.
Thank you.
