### ISSUE TITLE
read error: "end of file", debian 16.04

### ISSUE THREAD

**Issue by CompileMeSoflty** [xmrig/xmrig-proxy#393]
Hi,

no matter what settings I use, both on the miner side and proxy side, I keep getting "end of file" error every 2 minutes. Both connections are working good and I've also tested the connection from the proxy server to the mining pool. There are no lost packets. 

./xmrig-proxy -V
xmrig-proxy 5.9.0
 built on Mar 25 2020 with GCC 7.5.0
 features: 64-bit

libuv/1.18.0
OpenSSL/1.1.1
===========================================
XMRig 5.9.0
 built on Mar 25 2020 with GCC 8.3.0
 features: 64-bit AES

libuv/1.24.1
hwloc/1

=========================================
miner config

{
    "autosave": true,
    "cpu": true,
    "opencl": true,
    "cuda": true,
    "donate-level": 0,
    "donate-over-proxy": 0,
    "background": false,
    "pools": [
	{
            "coin": "monero",
            "algo": null,
            "url": "proxy_ip:5555",
            "user": "MYUSER",
            "pass": "MYPASS",
            "tls": false,
            "keepalive": true,
            "nicehash": true
        }
    ],
    "print-time": 60,
    "health-print-time": 60,
    "retries": 5,
    "retry-pause": 5,
}

==================================
on the proxy side I have the config.json, 
{
    "custom-diff": 55000,
    "custom-diff-stats": true,
    "donate-level": 5,
    "log-file": null,
    "mode": "nicehash",

"pools": [
        {
            "algo": null,
            "coin": "monero",
            "url": "pool.minexmr.com:80",
            "user": "MYUSER",
            "pass": "MYPASS",
            "rig-id": null,
            "keepalive": true,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
],
    "retries": 2,
    "retry-pause": 3,
    "reuse-timeout": 1,

....
}
=============================================

both configs have worked good before and I'm not sure why I have this problem. I keep getting the read error: "end of file" ~ every 2 minutes.

I used debug on and it says

read error: "end of file"
[2020-03-25 12:50:59.706] [ ] state: "connected" -> "closing"
[2020-03-25 12:50:59.706] [ ] state: "closing" -> "unconnected"
[2020-03-25 12:50:59.707] [ ] state: "unconnected" -> "reconnecting"
[2020-03-25 12:50:59.707]  net  no active pools, stop mining

How can I fix this problem?

Thank you!

**Comment by CompileMeSoflty** [comment]
I tried using SIMPLE mode, PROXY mode, NICEHASH mode, 0 custom difficulty, 1000000 custom difficulty and still keep getting that error. Tried again with a fresh config, switched the pool server, pool site, ip vs domainname, but I keep getting "end of file". I have no idea what else I should try.

**Comment by ilgabbibo** [comment]
@CompileMeSoflty since you closed the issue did you find a fix to this?
