### ISSUE TITLE
Questions about proxy

### ISSUE THREAD

**Issue by mik2141797** [xmrig/xmrig-proxy#4]
In the XMR-STAK, is there a nicehash_nonce option that is compatible with your proxy?

Is there a performance gain when using a proxy? Now all my miners work through Kerio firewall (port mapping) should I switch to your proxy? (pool xmr.crypto-pool.fr)

**Comment by xmrig** [comment]
Yep if set nicehash_nonce to true it will be compatible.

It hard question, proxy designed to work with large count of miners (thousands) with centralized management with reasonable fixed diff to all connected miners. It primary reduce pool load and sometimes only possible way to connect to pool, most of pools don't like many connections from single ip.

Simple case: fixed diff 10000 before use proxy and same diff after, there no any difference with miner performance.
