### ISSUE TITLE
Get the current pool through the API / Change the priority of the pool if there are more than two.

### ISSUE THREAD

**Issue by ORGaniZMo** [xmrig/xmrig-proxy#40]
Can you add the ability to get the current pool through the API and also to change the priority of the pool if there are more than two?

**Comment by xmrig** [comment]
Good idea, in TODO now https://github.com/xmrig/xmrig/issues/106
Thank you.

**Comment by mbog1202** [comment]
May be added the ability to split hash into different pools and coins. For examples, after 100 shares move from pool A (xmr) to pool B (another cryptonight coin)?

**Comment by andyval** [comment]
I was thinking the ability to use split mining between two different wallets.

**Comment by sleever** [comment]
Bump, I would like this as well!

**Comment by xmrig** [comment]
In dev branch added graceful reload support, also config file with pools now available via API and config change via API is planed, more details: #119

**Comment by xmrig** [comment]
Now config can be changed via HTTP API too, via `PUT /1/config` endpoint. Please note to get or update config via API you must set access token and set `"restricted": false`.

Example:
```json
    "api": {
        "port": 4466,
        "access-token": "SECRET",
        "worker-id": null,
        "ipv6": true,
        "restricted": false
    }
```

Curl example:
```
curl -v --data-binary @config.json -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer SECRET" http://127.0.0.1:4466/1/config
```

**Comment by RCTORONTO** [comment]
old thread I know but is there any examples for how to curl our way to switching pools via php and the api?  lets say the objective is simply to set the first pool in the pools array to enabled: false
