### ISSUE TITLE
The document root must not be followed by other values

### ISSUE THREAD

**Issue by serafim61** [xmrig/xmrig-proxy#42]
every 5 seconds
![image](https://user-images.githubusercontent.com/19187364/33264773-0342f6cc-d380-11e7-9824-afe6d15291f8.png)

**Comment by xmrig** [comment]
Something wrong with one worker with ip address 177.85... (on screenshot). This worker sent malformed JSON.
But there no ability to see what exactly received, because used destructive (to avoid memory allocation) JSON parser.
Thank you.

**Comment by serafim61** [comment]
Как отключить вывод такой ошибки. Сильно мешает смотреть статистику
