### ISSUE TITLE
Compile FreeBSD 11 release error

### ISSUE THREAD

**Issue by ptika** [xmrig/xmrig-proxy#44]
/usr/local/scripts/xmrig-proxy/src/Platform_unix.cpp:128:35: error: use of undeclared identifier 'SCHED_IDLE'
        if (sched_setscheduler(0, SCHED_IDLE, &param) != 0) {
                                  ^
/usr/local/scripts/xmrig-proxy/src/Platform_unix.cpp:129:35: error: use of undeclared identifier 'SCHED_BATCH'
            sched_setscheduler(0, SCHED_BATCH, &param);
                                  ^
2 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/local/scripts/xmrig-proxy
*** Error code 1

Stop.
make[1]: stopped in /usr/local/scripts/xmrig-proxy
*** Error code 1

Stop.
make: stopped in /usr/local/scripts/xmrig-proxy

**Comment by ptika** [comment]
In the file "Platform_unix.cpp" added the condition - the compilation went on
#   ifdef SCHED_IDLE
    if (priority == 0) {
        sched_param param;
        param.sched_priority = 0;
        if (sched_setscheduler(0, SCHED_IDLE, &param) != 0) {
            sched_setscheduler(0, SCHED_BATCH, &param);
        }
    }
#   endif

Now another error:
```
[100%] Linking CXX executable xmrig-proxy
/usr/bin/ld: cannot find -luuid
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
```

/usr/local/lib>ls -la | grep uuid
-r--r--r--   1 root  wheel    27260 Dec  1 12:36 libuuid.a
lrwxr-xr-x   1 root  wheel       12 Dec  1 12:36 libuuid.so -> libuuid.so.1
lrwxr-xr-x   1 root  wheel       14 Dec  1 12:36 libuuid.so.1 -> libuuid.so.1.2
-r-xr-xr-x   1 root  wheel    16776 Dec  1 12:36 libuuid.so.1.2


need help )

**Comment by Fneufneu** [comment]
This will fix libuuid linking:
`cmake .. -DCMAKE_EXE_LINKER_FLAGS=-L/usr/local/lib -DCMAKE_SHARED_LINKER_FLAGS=-L/usr/local/lib`

**Comment by DmitriyMazitov** [comment]
Still does not build under FreeBSD 11

ls -la /usr/local/lib | grep uuid
-r--r--r--   1 root  wheel     27020  3 апр.  02:02 libuuid.a
lrwxr-xr-x   1 root  wheel        12  3 апр.  02:02 libuuid.so@ -> libuuid.so.1
lrwxr-xr-x   1 root  wheel        14  3 апр.  02:02 libuuid.so.1@ -> libuuid.so.1.2
-r-xr-xr-x   1 root  wheel     16648  3 апр.  02:02 libuuid.so.1.2*


/home/dmitry/Mining/xmrig-proxy/src/Platform_unix.cpp:124:35: error: use of undeclared identifier 'SCHED_IDLE'
        if (sched_setscheduler(0, SCHED_IDLE, &param) != 0) {
                                  ^
/home/dmitry/Mining/xmrig-proxy/src/Platform_unix.cpp:125:35: error: use of undeclared identifier 'SCHED_BATCH'
            sched_setscheduler(0, SCHED_BATCH, &param);
                                  ^
2 errors generated.
--- CMakeFiles/xmrig-proxy.dir/src/Platform_unix.cpp.o ---
*** [CMakeFiles/xmrig-proxy.dir/src/Platform_unix.cpp.o] Error code 1

Help me please!

**Comment by ptika** [comment]
In the file "Platform_unix.cpp" added the condition - the compilation went on

```
# ifdef SCHED_IDLE
if (priority == 0) {
    sched_param param;
    param.sched_priority = 0;
    if (sched_setscheduler(0, SCHED_IDLE, &param) != 0) {
        sched_setscheduler(0, SCHED_BATCH, &param);
    }
}
# endif
```

**Comment by lisergey** [comment]
I've just successfully compiled xmrig-proxy under FreeBSD-11.1-RELEASE-p9.
everything as in build instruction for Ubuntu, nothing special.
libuv and libmicrohttpd are installed from FreeBSD ports.

**Comment by DmitriyMazitov** [comment]
Hi! Version 2.5.3 has just been compiled successfully! :)
