### ISSUE TITLE
upstreams problem

### ISSUE THREAD

**Issue by aawr** [xmrig/xmrig-proxy#443]
[2021-03-13 03:42:00.884] * upstreams active: 396 sleep: 0 error: 0 total: 396
[2021-03-13 03:42:00.885] * miners    active: 399 max: 400

I dn know, why do I have so many upstreams
this causes each upstream to send a url request to the pool

**Comment by avselang** [comment]
do you have answer?

**Comment by SChernykh** [comment]
If xmrig-proxy is running in simple mode, each connected miner = upstream. Use NiceHash mode where 1 upstream = 256 connected miners.
