### ISSUE TITLE
issues with using xmrig-proxy with MINEXMR pool

### ISSUE THREAD

**Issue by jackalmeida** [xmrig/xmrig-proxy#45]
Thanks for making such a great product to us!!!  I have been using xmrig, and I keep 2% donation on all the time.

When I use xmrig cpu miner alone with pool.minexmr.com,  minexmr auto adjusts the difficulty on their side.
So I use WALLET+DIFF as username in xmrig config,  just to make sure to use fixed difficulty.

But now I'm using xmrig miner + xmrig-proxy,   
should I set WALLET+DIFF in the USER part of the proxy config file? I saw the proxy config file has "custom-diff",  should I also set the difficulty value there.... ?
and in this case what should I set in the USER , PASS, Keepalive settings of the xmrig miner ?  I can just put anything as the nickname of the device for the username? or I still need to use the WALLET+DIFF as username and X as the password from the minexmr pool side?  what about keep alive setting its for the xmrig proxy or minexmr pool ?

btw,  
1.
I learnt GCC compiled X86 xmrig cpu miner has better performance.
what about for X64 xmrig cpu miner?  gcc compiled has better performance or msvc ?  or its the same?

2.
Using 
-o stratum+tcp://pool.minexmr.com:4444
or
-o pool.minexmr.com:4444
for the command line both works,  does it has any difference?  which one is better way to use ?

Great thanks if someone can clear these confusion for me.  I have read all the posts here on GitHub and Reddit forum.  I would like to pay $50 worth of XMR for thank you,  plz leave your XMR address

**Comment by xmrig** [comment]
Originally I suggest use fixed diff, it more predictable, but automatic diff is ok too. With recent tests you can use automatic diff, only cumulative hashrate masters, hashrate of individual workers not so important.

WALLET only need on proxy side (with optional DIFF), on miner side it can be any string, will be used as worker name.

`custom-diff` or per worker diff only useful for miners without keepalive support, to prevent 10 minutes timeout.

Better enable `keepalve` option on miner side to prevent timeouts and enable `nicehash` option.

1. For x86 difference very small, usually msvc little faster.
2. It equal, second shorter.

First connection for pool, up to 256 workers always donation free.

Sorry for late reply, was very busy.
Thank you.

**Comment by jackalmeida** [comment]
Great thanks bro!

1.  now as my understanding,  for both windows x86 and x64 xmrig cpu miner,  the msvc build is smaller and also better performance than GCC build,  correct ?

**Comment by xmrig** [comment]
For x86 msvc builds very slow and I don't provide binaries because of it.
For x64 difference very small, msvc possible can give 1-2 or so hashes more.
