### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by djfinch** [xmrig/xmrig-proxy#5]
10.11.6
Xcode 8.2.1
Build version 8C1002
Latest Homebrew
----------------------

src/proxy/Proxy.cpp:43:5: error: no member named 'srand' in namespace 'std'; did you mean simply 'srand'?
    std::srand(std::time(0) ^ (uintptr_t) this);
    ^~~~~~~~~~
    srand
/usr/include/stdlib.h:161:7: note: 'srand' declared here
void     srand(unsigned);
         ^

**Comment by xmrig** [comment]
OS X support restored.
Thank you.
