### ISSUE TITLE
uuid/uuid.h

### ISSUE THREAD

**Issue by spidero** [xmrig/xmrig-proxy#50]
[  2%] Building CXX object CMakeFiles/xmrig-proxy.dir/src/proxy/Uuid_unix.cpp.o
/root/xmrig-proxy/src/proxy/Uuid_unix.cpp:24:23: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
                       ^
compilation terminated.
CMakeFiles/xmrig-proxy.dir/build.make:997: recipe for target 'CMakeFiles/xmrig-proxy.dir/src/proxy/Uuid_unix.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/proxy/Uuid_unix.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/xmrig-proxy.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by spidero** [comment]
solution uuid-dev package is missing :)

**Comment by qnxdev** [comment]
Will the uuid-dev solve it?

**Comment by spidero** [comment]
yes

**Comment by xmrig** [comment]
Recent versions no longer require uuid.
Thank you.
