### ISSUE TITLE
How to increase max miners count?

### ISSUE THREAD

**Issue by ghost** [xmrig/xmrig-proxy#502]
currently it says max miners: 2

(no docs for max miners)

**Comment by Maz4id** [comment]
There's no limit to how many miners can connect to your proxy, as long as your server doesn't crash.
What ur seeing **_`max miners: 2`_** is the number of miners that have been connected to your proxy at the same time.

Basically, you have 100 miners, and for some reason 10 of them crash.
You will see **_`active: 90 max: 100`_** which means that currently, you have 90 miners running and before you had a maximum of 100 connected to your proxy.

**Comment by sampath017** [comment]
You're right, the first time it showed connection refused and after some tries, it connected.
