### ISSUE TITLE
zmq / 0mq support

### ISSUE THREAD

**Issue by Gingeropolous** [xmrig/xmrig-proxy#507]
Im trying to set this up and I noticed in the configuration that the --daemon has --daemon-poll-interval ,  which indicates that the proxy isn't set up to take advantage of monerod's 0mq magic stuff .

Is this true, or am I just missing something?

**Comment by Gingeropolous** [comment]
so does it connect via zmq be default to the daemon?

**Comment by SChernykh** [comment]
zmq can only be used when connecting to daemon.

**Comment by Gingeropolous** [comment]
ok, so if tried specifying the zmq port and the proxy doesn't connect

            "daemon": true,
            "url": "192.168.1.76:18082",

what am i missing?

if i put the regular rpc port in the url field there, it works fine.

**Comment by SChernykh** [comment]
`url` should have the regular RPC port, and zmq port goes into `daemon-zmq-port` parameter.

**Comment by Gingeropolous** [comment]
ah, thats in neither the readme or the --help. must be a super secret setting only the cool peeps know about

**Comment by Gingeropolous** [comment]
Thank you so much @SChernykh . Sorry im incapable of finding things on my own :/
