### ISSUE TITLE
WHAT JUST HAPPENED??

### ISSUE THREAD

**Issue by cyizard** [xmrig/xmrig-proxy#508]
So I have 12 cpu's with widely varying hash rates.

Yesterday I connected them all to xmrig-proxy and it gave me 12 different instances of jobs from the pool.  Each cpu connection had its own difficutly delivered to it.  Additionally, instead of saying 1 upstream it said 12 upstreams.  Furthermore when something logged from "net" it gave a specific number from 0000 to 0011 depending on which cpu was referring to.

BUT, Now when I restart the proxy it just bunches them all together delivering the same difficulty to all the miners.  I'm not sure what I changed??

Please help me get this feature back!

**Comment by cyizard** [comment]
LOL yea that was it!  Thanks SO much.  I wanted to continue my testing!

**Comment by OlMi1** [comment]
Please close this when done! :)
