### ISSUE TITLE
uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

### ISSUE THREAD

**Issue by bwq90** [xmrig/xmrig-proxy#516]
Today I got the below error and then XMRIG Proxy Aborted.

`src/unix/core.c:932: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.`

The proxy was running fine for last few days. The hashrate was stable and everything looked normal. Until it suddently got aborted with the above error.

Now I have restarted proxy and it is again running fine.

Server Machine:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

**Comment by bwq90** [comment]
Today I again got this error and xmrig proxy crashed. Now I am updating my OS to 20.04 LTS. because the other instance on 20.04 LTS is working fine.

**Comment by SChernykh** [comment]
This is a bug in libuv and it was fixed in libuv v1.41: https://github.com/nodejs/node/issues/33966#issuecomment-1002384565

**Comment by bwq90** [comment]
Thanks @SChernykh . Yes I can confirm that after updating to Ubuntu 20.04 LTS. This bug no longer occurs.
