### ISSUE TITLE
Download for testing yesterday, lose 5.99 coins from mymonero.com today. 

### ISSUE THREAD

**Issue by XliveStudios** [xmrig/xmrig-proxy#52]
I think you have imported a hidden trojan in xmrig-proxy.exe. 
https://www.reddit.com/r/Monero/comments/7k9isn/someone_hack_my_mymonerocom_wallet/

**Comment by XliveStudios** [comment]
https://www.reddit.com/r/Monero/comments/7k9isn/someone_hack_my_mymonerocom_wallet/

**Comment by xmrig** [comment]
SHA2 hashed with exe files provided by you and official releases are equal. There no trojan. Also proxy very bad choice for put trojan, because primary platform for it is Linux servers. Your system got compromised some how else.
Thank you.
