### ISSUE TITLE
Cannot Compile Xmrig-proxy with Raspberry Pi 4B

### ISSUE THREAD

**Issue by Phrazor** [xmrig/xmrig-proxy#521]
Can anyone help with this Issue ? 

cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib/arm-linux-gnueabihf/libuv.a -DWITH_HTTPD=OFF
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found UV: /usr/lib/arm-linux-gnueabihf/libuv.a
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.1n")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_HTTPD

-- Build files have been written to: /home/pi/xmrig-proxy/build

------------------------------------

Tried following this guide on the latest Raspberry OS 64 bit. With ARMV8...

https://safex.org/blog/using-xmrig-proxy-for-multiple-safex-mining-rigs/

**Comment by SChernykh** [comment]
The option is called WITH_HTTP, not WITH_HTTPD.

**Comment by Phrazor** [comment]
ah ok then the creator probably made a small typo, now it works, but there is an error at the end that there is no rule:

`ah ok then the creator probably made a small typo, now it works, but there is an error at the end that there is no rule:

Sorry put in German hope that's not a `problem.`

Greetings

Sorry put in German hope that's not a problem.

Greetings

**Comment by SChernykh** [comment]
It's better to try this build instruction: https://xmrig.com/docs/proxy/ubuntu-build

**Comment by Phrazor** [comment]
AHHH no it works :) With one error but it works :) Think i can ignore it ? Thanks !!

/home/pi/xmrig-proxy/src/base/net/stratum/DaemonClient.cpp:69:20: warning: ‘xmrig::kLastError’ defined but not used [-Wunused-variable]
   69 | static const char* kLastError               = "lasterror";
      |                    ^~~~~~~~~~

**Comment by SChernykh** [comment]
It's not an error, you can ignore it.

**Comment by Phrazor** [comment]
Big thanks and solved

**Comment by Phrazor** [comment]
Another Question:
Is it possible to add a command to config.json in xmrig-proxy to frequently show workers (the same if u hit "w") ?

I run xmrig-proxy as service and cannot use "w" for journal output ...
