### ISSUE TITLE
Add Mysql feature

### ISSUE THREAD

**Issue by ziyaad30** [xmrig/xmrig-proxy#53]
Is it possible to add a save stats to mysql, or how to keep the stats on proxy restart?

**Comment by ORGaniZMo** [comment]
ziyaad30, You can write a program / script that will process data from JSON and store it in MySQL.

**Comment by ORGaniZMo** [comment]
> I want to know how to get the diff variables
It seems to me that in the current version there is no way.

**Comment by xmrig** [comment]
Just for curiosity for what reason you need know diff? Maybe I missed some point. If you use fixed diff you already know it if not diff may be different across pool upstreams.
Thank you.
