### ISSUE TITLE
Cannot get Proxy to work

### ISSUE THREAD

**Issue by Ranchdad86** [xmrig/xmrig-proxy#549]
I finally have enough rigs it makes sense to aggregate with a proxy before mining, tried mining to 2 miners and a couple others with same results. . 
For context I have also in the past run monerod/p2pool and solo mined to my own node on this same computer from multiple other rigs with no firewall or other issues previously, and I ran both last night and they still connected and worked (big shout out to the P2POOL devs for making ridiculously easy detailed instructions and keeping them up to date
Either I'm configuring my miners wrong to point to the proxy or something else.

1. I installed XMRIG proxy.
2. I configured using the instructions found on other threads on here.
3. I configured using instructions on YouTube.
4. I configured using the config creator
5. All had the same result 
- My proxy runs and connects to 2 miners fine.
- From the same system the server is running on, I mine using the 127 IP and it works fine, and mines in the proxy and shows on 2 miners.
- On all other rigs (on the same network) I point to the actual IPv4 IP of the system running the proxy. They all say "connection refused" I've tried the 3333 port as well as a 1111 and can't get anything to work.
Am I making some stupid mistake I'm not thinking about? Thank you!

**Comment by SChernykh** [comment]
Can you attach config.json that you use for the proxy? If it says "connection refused", it means the proxy is not listening on port 3333 on that specific IP. Double check that you have `"host": "0.0.0.0",` next to `"port": 3333,` in config.json

**Comment by Ranchdad86** [comment]
So I just redid everything and used only port 1111 on everything and now it is working? I've got 4 rigs connected so far and going to let them run before connecting all the rest. below is my JSON if I put something wrong in there. 

{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 3333,
            "tls": false
        },
        {
            "host": "0.0.0.0",
            "port": 1111,
            "tls": false
        }
    ],
    "colors": true,
    "title": true,
    "custom-diff": 0,
    "custom-diff-stats": false,
    "donate-level": 0,
    "log-file": null,
    "mode": "simple",
    "pools": [
        {
            "algo":"rx/0",
            "coin": "monero",
            "url": "solo-xmr.2miners.com:4444",
            "user": "(my wallet, hidden for privacy)",
            "pass": "x",
            "rig-id": "00",
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "enabled": true,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}

**Comment by Ranchdad86** [comment]
> [<img alt="@Ranchdad86" width="40" height="40" src="https://avatars.githubusercontent.com/u/142755220?s=80&amp;v=4">](/Ranchdad86)

So I just redid everything and used only port 1111 on everything and now it is working? I've got 4 rigs connected so far and going to let them run before connecting all the rest. below is my JSON if I put something wrong in there.

Also, I'm not getting "read error: "end of file" every few minutes on the proxy

{
"access-log-file": null,
"access-password": null,
"algo-ext": true,
"api": {
"id": null,
"worker-id": null
},
"background": false,
"bind": [
{
"host": "0.0.0.0",
"port": 3333,
"tls": false
},
{
"host": "0.0.0.0",
"port": 1111,
"tls": false
}
],
"colors": true,
"title": true,
"custom-diff": 0,
"custom-diff-stats": false,
"donate-level": 0,
"log-file": null,
"mode": "simple",
"pools": [
{
"algo":"rx/0",
"coin": "monero",
"url": "solo-xmr.2miners.com:4444",
"user": "(my wallet, hidden for privacy)",
"pass": "x",
"rig-id": "00",
"keepalive": false,
"enabled": true,
"tls": false,
"tls-fingerprint": null,
"daemon": false
}
],
"retries": 2,
"retry-pause": 1,
"reuse-timeout": 0,
"tls": {
"enabled": true,
"protocols": null,
"cert": null,
"cert_key": null,
"ciphers": null,
"ciphersuites": null,
"dhparam": null
},
"user-agent": null,
"syslog": false,
"verbose": false,
"watch": true,
"workers": true
}

@Ranchdad86

**Comment by Ranchdad86** [comment]
> Can you attach config.json that you use for the proxy? If it says "connection refused", it means the proxy is not listening on port 3333 on that specific IP. Double check that you have `"host": "0.0.0.0",` next to `"port": 3333,` in config.json

So I just redid everything and used only port 1111 on everything and now it is working? I've got 4 rigs connected so far and going to let them run before connecting all the rest. below is my JSON if I put something wrong in there.

Also, I'm not getting "read error: "end of file" every few minutes on the proxy

{
"access-log-file": null,
"access-password": null,
"algo-ext": true,
"api": {
"id": null,
"worker-id": null
},
"background": false,
"bind": [
{
"host": "0.0.0.0",
"port": 3333,
"tls": false
},
{
"host": "0.0.0.0",
"port": 1111,
"tls": false
}
],
"colors": true,
"title": true,
"custom-diff": 0,
"custom-diff-stats": false,
"donate-level": 0,
"log-file": null,
"mode": "simple",
"pools": [
{
"algo":"rx/0",
"coin": "monero",
"url": "solo-xmr.2miners.com:4444",
"user": "(my wallet, hidden for privacy)",
"pass": "x",
"rig-id": "00",
"keepalive": false,
"enabled": true,
"tls": false,
"tls-fingerprint": null,
"daemon": false
}
],
"retries": 2,
"retry-pause": 1,
"reuse-timeout": 0,
"tls": {
"enabled": true,
"protocols": null,
"cert": null,
"cert_key": null,
"ciphers": null,
"ciphersuites": null,
"dhparam": null
},
"user-agent": null,
"syslog": false,
"verbose": false,
"watch": true,
"workers": true
}

**Comment by SChernykh** [comment]
```
{
"host": "0.0.0.0",
"port": 3333,
"tls": false
},
{
"host": "0.0.0.0",
"port": 1111,
"tls": false
}
```
You should leave only one of the two. If port 1111 works, leave the one with port 1111.

**Comment by Ranchdad86** [comment]
> ```
> {
> "host": "0.0.0.0",
> "port": 3333,
> "tls": false
> },
> {
> "host": "0.0.0.0",
> "port": 1111,
> "tls": false
> }
> ```
> 
> You should leave only one of the two. If port 1111 works, leave the one with port 1111.

Ok. Done. Any idea on the End of File error now? it's showing upstreams and miners and hash, and shows on the 2miners dashboard, but every few min it is suddenly stopping and saying "read error: "end of file""

**Comment by SChernykh** [comment]
"end of file" is when the pool disconnects. Try another pool maybe, or another pool server.

**Comment by Ranchdad86** [comment]
> "end of file" is when the pool disconnects. Try another pool maybe, or another pool server.

Thank you. It hasn't done it for a while. I'll try another if it works. Been a long few days of issues between new BZminer release not working (apparently multiple people have the same issue with it getting stuck loading the config.txt), asic pool issues, etc. Thanks for responding so fast!
