### ISSUE TITLE
running proxy on AWS; where to point my miners?

### ISSUE THREAD

**Issue by gitbit00** [xmrig/xmrig-proxy#55]
Hi and huge thanks for the xmrig series of mining tools! 

So I'm running xmrig-proxy on a T2-micro instance. The software is installed and running.

And I'm using 500 EC2 instances to mine with XMR-STAK v2.1.0 (CPU mining only).

I can't find clear direction on how to point the miners to the proxy.. I'm guessing this must be really a simple question since I can't find anyone asking the same...

The proxy is pointed at my mining pool, now how do I point all my miners to the proxy?

{
    "background": false,
    "log-file": null,
    "access-log-file": null,
    "retries": 5,
    "retry-pause": 5,
    "donate-level": 1,
    "coin": "xmr",
    "custom-diff": 3000,
    "syslog": false,
    "verbose": false,
    "colors": true,
    "workers": true,
    "pools": [
        {
            "url": "mine.xmrpool.net",
            "user": "wallet#",
            "pass": "x"
        }
    ],
    "bind": [
        "0.0.0.0:3333"
    ],
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null
    }
}

**Comment by Mila432** [comment]
Use your ip

**Comment by ORGaniZMo** [comment]
> Use your ip
 
"Use the Force, Luke."

**Comment by gitbit00** [comment]
Got it! Had to add a security exception through AWS. Thank you!

**Comment by iamajeesh** [comment]
@gitbit00 is it profitable?

**Comment by gitbit00** [comment]
I have credits that I'm using so its profitable for my situation. If I were paying for the virtual machines, no it would not be profitable. I've nearly found a break even point, but I haven't been able to make it profitable yet...

**Comment by SnShine** [comment]
Previously I use `./xmrig -o xmr-us-east1.nanopool.org:14444 -u Wallet_ADDR.rig_1 -p x` to mine XMR. Now if I have to connect my miner to a proxy while proxy is running as mentioned in the readme.

I'm trying `./xmrig -o a.b.c.d:3333 -u 1 -p x -k` where a.b.c.d is proxy intranet IP and .3333 is bind address while starting proxy but miner is returning error: `Try "xmrig" --help' for more information.`.

How exactly to configure miner as the only useful info in this issue is only `Use your ip`.

**Comment by okaris** [comment]
@gitbit00 I need to contact you can you ping me ok [at] okaris [dot] com please?

**Comment by gitbit00** [comment]
@okaris I pinged you.

**Comment by gitbit00** [comment]
I had an issue where my machine was not receiving inbound communication on
the port that the proxy was bound to (i.e. 3333). I use AWS so in my
console I changed the inbound rules, and then it works perfectly. My guess
is your have a firewall or something blocking that port. It really was as
simple as IP address and Port.


Cheers!
