### ISSUE TITLE
how to configure miners?

### ISSUE THREAD

**Issue by gitbit00** [xmrig/xmrig-proxy#56]
Hi and thank you!

I have the proxy running on a T2 instance:

$netstat -lntup -
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      24285/proxy.js  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      24285/proxy.js  
tcp        0      0 0.0.0.0:3333            0.0.0.0:*               LISTEN      24285/proxy.js  

I've added in my mining pool details to the config.json file.

My question is on the miner side to configure in xmr-stak.. what address do I point the miner to?
I have tried the IP address and port for my proxy but its not working... 

Here are the results from running '$ ifconfig -a' on my proxy:

eth0      Link encap:Ethernet  HWaddr 06:2e:d8:5a:eb:ea  
          inet addr:172.31.25.90  Bcast:172.31.31.255  Mask:255.255.240.0
          inet6 addr: fe80::42e:d8ff:fe5a:ebea/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:144708 errors:0 dropped:0 overruns:0 frame:0
          TX packets:27092 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:201469803 (201.4 MB)  TX bytes:3032791 (3.0 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:192 errors:0 dropped:0 overruns:0 frame:0
          TX packets:192 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:14456 (14.4 KB)  TX bytes:14456 (14.4 KB)

Any help?

**Comment by gitbit00** [comment]
I should mention all of this is on virtual machines using Amazon Web Services EC2 machines. I'm using a T2 instance for the proxy.
My goal is to use 500 EC2 machines for mining and run them through the proxy.

**Comment by xmrig** [comment]
Dublicate #55
