### ISSUE TITLE
Logging should not be fully read into memory

### ISSUE THREAD

**Issue by arz96** [xmrig/xmrig-proxy#563]
After a period of time the ram will be more and more because logging file is getting bigger, and I can't even truncate it because it's in memory and when you change the file the program change it back once there's new logs, the only way to not let this happen is either disable logging or close the proxy before you modify the log file. XMRig-Proxy should just appened to the file instead of reading it first.

**Comment by SChernykh** [comment]
> XMRig-Proxy should just appened to the file instead of reading it first.

This is exactly what it does. It only keeps data that hasn't been flushed (=written) yet: https://github.com/xmrig/xmrig-proxy/blob/master/src/base/io/log/FileLogWriter.cpp

**Comment by SChernykh** [comment]
No, this is how a filesystem works. If you truncate the file, but some other program has a write pointer to it at a position of 1,000,000 and then writes to it, the size of the file will be 1,000,000 + size of new data. The first 1,000,000 bytes will be technically garbage, but if old data is not overwritten, it will be old data.
