### ISSUE TITLE
Thread count [Question]

### ISSUE THREAD

**Issue by leeroyjkins** [xmrig/xmrig-proxy#59]
Is there an option to set thread count or is that set automatically ?
What's the max thread count it can utilize ?

**Comment by leeroyjkins** [comment]
So it seems it's using only single thread, I've explored how to utilize 2 or 4 threads if available and one way is to set SO_REUSEPORT in Server.cpp and then launch multiple processes of proxy.
```Server::Server(const char *ip, uint16_t port) :
    m_ip(ip),
    m_port(port)
{
    uv_os_fd_t fd;
    uv_tcp_init_ex(uv_default_loop(), &m_server, AF_INET);
    uv_fileno((const uv_handle_t*) &m_server, &fd);
    int enable = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, &enable, sizeof(enable));
    m_server.data = this;

    uv_ip4_addr(ip, port, &m_addr);
    uv_tcp_nodelay(&m_server, 1);
}
```
That way they will be able to share port and os will give them incoming tcp connection equally.
Is there maybe better way to do this, without spawning multiple processes?
Maybe have multiple workers in single process ?
And does it even make sense to do it, at what point is one core not enough ? (connection count)

**Comment by tucksmcgucks** [comment]
This is an excellent question, very interested to read the answer.

Also, how does the threading compare to Atrides proxy?

Warm regards,
- Tuck

**Comment by xmrig** [comment]
How many connections do you want? I was benchmarking it, single thread can easily handle over 100k connections.
Thank you.

**Comment by leeroyjkins** [comment]
Yea that's more than enough connections.
