### ISSUE TITLE
after several accepted jobs, pool doenst accepting any jobs further

### ISSUE THREAD

**Issue by chamcg** [xmrig/xmrig-proxy#60]
HI Guys
i have 1GHz, 2GB ubuntu PC
when i start the xmrig it works well for around 20 minutes
after that it stop accepting any jobs, even it received new jobs regularly
can anyone please help me on this?
please see the screenshot

![image](https://user-images.githubusercontent.com/34935424/34433013-40843578-ecd0-11e7-8bb7-981c7196d108.png)

**Comment by xmrig** [comment]
Hashrate down for some reason, maybe other heavy application ruining, so time required to find share increased.
Thank you.

**Comment by chamcg** [comment]
Hi xmrig
thanks for answer
however there is no other application running on this
