### ISSUE TITLE
Chaining multiple proxy results in rejected shares

### ISSUE THREAD

**Issue by MaxLap** [xmrig/xmrig-proxy#62]
I am pretty sure it should be possible to chain multiple Stratum proxy one after the other. However, it doesn't work with this proxy. If I make my miner go through 2 of them, then every shares will be rejected by the 2nd proxy (the one closer to the pool) with the message: `Invalid nonce; is miner not compatible with NiceHash?`.

The cause is this chunk: https://github.com/xmrig/xmrig-proxy/blob/23b8d9e6fa4c9f22fd97e45cd8954d9adee6efda/src/proxy/Miner.cpp#L183-L185

If I just comment out the `reject` call, then the miner's shares are accepted and I can see them on the pool's website. So I'm not sure exactly what this test is for, but it seems to block some uses cases that seem valid.

I was just curious about what a Stratum proxy does and thought this should work. This might not be much of an issue to anyone, but it might indicate a deeper issue.

**Comment by xmrig** [comment]
It not just stratum proxy, it’s nicehash proxy, it reduce connection count to pool. If you remove this check it undefined behavior, but chaining will work until you have less than 256 workers.
If you need chaining you sould use pure tcp proxy like haproxy.
Thank you.

**Comment by xmrig** [comment]
Merge with #118
