### ISSUE TITLE
Too more Invalid Shares

### ISSUE THREAD

**Issue by crackwei** [xmrig/xmrig-proxy#63]
i have 100 miners to mining on supportxmr.com
so i use xmrig-proxy,it seems good work
but i fould it's too more Invalid Shares on the site (approx 1/10)
how to fixed this problem.
thanks

**Comment by iamajeesh** [comment]
xmrig-proxy performs best when difficulty is fixed.  supportxmr.com doesn't have fixed difficulty.

**Comment by crackwei** [comment]
i connect to nanopool,it's run good with the fixed difficulty.but the nanopool difficulty is to high,do you have some pools to recommended?

**Comment by iamajeesh** [comment]
@crackwei  try hashvault with fixed difficulty.

**Comment by crackwei** [comment]
thank you!
