### ISSUE TITLE
how to change 256 worker per connection to 100 per connection ?

### ISSUE THREAD

**Issue by iamajeesh** [xmrig/xmrig-proxy#64]
Hello, 

i would like to reduce the up to 256 workers to one pool connection.

can i make it 128 or 100 or so in the code? which line to modify?

thanks

**Comment by iamajeesh** [comment]
i have seen that increasing the connections to pool increases the rate of Accepted shares..

so can any one shed some light on, how to increase the pools count or the reduce the number of workers per connection, ?

Thanks

**Comment by xmrig** [comment]
256 it's not a magically chosen constant, it 1 of 4 byte from nonce (miner work), so it not trivial to change it.
About rate of accepted shares, you can just increase fixed diff (how do it depends of pool) or leave diff automatic.
Thank you.

**Comment by iamajeesh** [comment]
i use nanopool now, Difficulty is fixed in nanopool. 

so if, changing it wont effect the working of proxy  , then please guide where to make changes accordingly ?

**Comment by xmrig** [comment]
If pool works fine with high accepted shares rate (without bans, etc) it not a issue. Otherwise limit workers count no so good idea, because need limit hashrate per upstream to about 2-10 KH/s it can be different count of workers.
Thank you.
