### ISSUE TITLE
How to calculate optimal value for static difficult?

### ISSUE THREAD

**Issue by Anton-Beresansky** [xmrig/xmrig-proxy#65]
Please, provide me some formula, or something? Or point me to something to read about. Google didn't help me with that.

P.S. Is it possible to add worker identification by using "password" field? I have many workers mining on same wallet, so when I press "W" I always get 1  worker with many connections. Can You add an option to identify workers "inside" same wallet or help me to do that (point me to function that I can modernize).

**Comment by Anton-Beresansky** [comment]
What a great conversation we have here! XD

**Comment by xmrig** [comment]
Diff not to much important, with recent research you can use automatic diff, at least on nodejs-pool based pools. Usually good if proxy submit few shares in 2 minutes. More often increase pool load, but give more precise hashrate on pool side (without big peaks) but overall hashrate will be same.

Example, your hashrate 10 KH/s this is 600000 (10000 * 60) hashes per minute, so with 100% effort you will be found 1 share each minute, in reality you can found 2+ shares per minute or zero, but on long time period it doesn't mater.

With diff 10000 you will be found share about each second, it bad for pool.

Also 600000 diff it's ok for 100 H/s worker to, it will be found share about each 100 minutes, for miners without keepalive support useful custom diff, to prevent timeouts.

`password` field ignored by proxy, use `user` field without wallet address.
Thank you, sorry for later answer.

**Comment by Anton-Beresansky** [comment]
Thank you so much!
Hope someone like me will find this from google, or whatever...

**Comment by tinyema** [comment]
@xmrig you said
> Diff not to much important, with recent research you can use automatic diff, at least on nodejs-pool based pools.

...and if the pool isn't based on nodejs?

**Comment by huserbg** [comment]
I usually set my difficulty to be such that on average one result is sent every 30 seconds.
The calculation is extremely simple, just multiply your actual hashrate by the number of seconds you want as a target.
For example, if your hashrate is 500 H/s and you want result every 30 seconds, set the difficulty to 15000.
