### ISSUE TITLE
xmrig-proxy nohup issues,thank you

### ISSUE THREAD

**Issue by alexeverH** [xmrig/xmrig-proxy#66]
cd /xmrig-proxy/build
nohup ./xmrig-proxy &

and get a error:
xmrig-proxy: src/unix/stream.c:1485: uv_read_start: Assertion `stream->type == UV_TCP || stream->type == UV_NAMED_PIPE || stream->type == UV_TTY' failed.

our system is ubuntu.

second question：

How many miners can be supported with xmrig-proxy? 2000 miner is ok? 
If not, how do I need to set up？

Thank you

**Comment by xmrig** [comment]
Looks like same issue https://github.com/xmrig/xmrig/issues/167 miner and proxy use same codebase.

2000 is ok, but you need increase limits of open files: https://github.com/xmrig/xmrig-proxy/wiki/Ubuntu-setup
Thank you.

**Comment by alexeverH** [comment]
First question have resolved,thank you

and i will try to  increase limits for 1K miners.

**Comment by alexeverH** [comment]
Hi,
Thank you, i will send the XMR to your wallet,
and give you a email,
one more questions,xmring-proxy support nicehash.com's pool?
Thank you
Regards, 

    On Tuesday, January 2, 2018 3:10 PM, xmrig <notifications@github.com> wrote:
 

 Looks like same issue xmrig/xmrig#167 miner and proxy use same codebase.2000 is ok, but you need increase limits of open files: https://github.com/xmrig/xmrig-proxy/wiki/Ubuntu-setup
Thank you.—

**Comment by kimats** [comment]
@alexeverH 
what to do to solve the  `stream->type == UV_TCP || stream->type == UV_NAMED_PIPE || stream->type == UV_TTY' failed.?
