### ISSUE TITLE
Use with Nicehash

### ISSUE THREAD

**Issue by angel12** [xmrig/xmrig-proxy#67]
Doesnt seem like I can get the proxy to work with Nicehash, it reports just like I was using xmrig directly to nicehash without "true" being set. Is it possible to use proxy with nicehash?

**Comment by xmrig** [comment]
xmrig detects nicehash in 255 of 256 connections. in 1 of 256 nicehash blob equal to generic pool and no way to detect it, in this case time after connection and before found first share, will be lose.

Proxy can't work with the nicehash.com because it work like nicehash.com.
Thank you.

**Comment by mikef147** [comment]
As a workaround for Nicehash, if you are using xmrig for your miner, set up your miners with a backup pool of nice hash, primary pool of xmrig proxy. if you decide you want your miners on nice hash, just kill xmrig proxy and they'll start mining nice hash. to start back on proxy, just start up xmrig proxy again and miners will switch back to your proxy.

**Comment by PhatWheZ** [comment]
the issue is for the proxy and NH to communicate to allow savings on
Packets out onto the internet.
I have seen issues when too many rigs connect up from the same Public IP to
NH where i actually get a drop in hash rate
