### ISSUE TITLE
Auto-Diff Feature

### ISSUE THREAD

**Issue by tknecht** [xmrig/xmrig-proxy#69]
Is there any chance of Auto-Diff coming along our ways with xmrig-proxy soon?

Thanks for the great work.

**Comment by Anton-Beresansky** [comment]
Look at this answer, may be useful: https://github.com/xmrig/xmrig-proxy/issues/65#issuecomment-355274839

**Comment by xmrig** [comment]
Auto-Diff will be not implemented ever, it useless feature for proxy.
Thank you.
