### ISSUE TITLE
Correct the symbol for kilo- (lower-case "k")

### ISSUE THREAD

**Issue by Anton-Beresansky** [xmrig/xmrig-proxy#70]
> Please note, that the symbol for kilo- is a lower-case "k". As "K" is the symbol for kelvin, the unit of thermodynamic temperature.
> 
> The [following table from Wikipedia](https://en.wikipedia.org/wiki/Metric_prefix) shows an overview of the prefixes, symbols, and factors they correspond to. 

https://bitcoin.stackexchange.com/a/21498

**Comment by xmrig** [comment]
Fixed.
