### ISSUE TITLE
Persisting workers.json / or resetting

### ISSUE THREAD

**Issue by cambazz** [xmrig/xmrig-proxy#73]
Hello,

Is there a way to persist the data from the workers.json on the api? 

Also is there a way to reset the cumulative data for workers periodically?

Bestr Regards,
C.

**Comment by xmrig** [comment]
For both question answer no, but good ideas anyway. I mark this issue as **enhancement** for don't forget about it.
Thank you.

**Comment by cambazz** [comment]
Perhaps if you guide me, I can do it and submit a pull request. Best regards,
C.

**Comment by xmrig** [comment]
2 ways to reset workers list:
1. Use API `GET/PUT /1/config` to change config file.
2. Change config file on disk, proxy will reload it.

Details #251
