### ISSUE TITLE
is possible to have multiple instances of xmrig-proxy sharing the same pool user?

### ISSUE THREAD

**Issue by frotunato** [xmrig/xmrig-proxy#74]
Hello, I would like to know if there is any issue having in having two different machines an instance of xmrig-proxy both with the same pool user.

As for the pool side, it would appear as two different workers right?

Thank you in advance.

**Comment by xmrig** [comment]
It normal situation, think about proxy is a miner.
For 2 different workers:
1. Pool should support worker id.
2. You manually set different worker id for both instances.

Thank you.
