### ISSUE TITLE
How to create an config for the proxy

### ISSUE THREAD

**Issue by isheirff** [xmrig/xmrig-proxy#75]
Hi xmrig, 

how can i create an config file to include 3 pools live nice hash, nanopool and supportxmr?

how do i conpose the json file to just run it via command ./xmrig-proxy

**Comment by PhatWheZ** [comment]
Nicehash won't work. I have tried and waiting for an update from nicehash
themselves. If you want to have a primary and backup if the primary goes
down is easy, but switching I don't know if it can be done or not without a
timer feature

**Comment by isheirff** [comment]
yea they only accepting hightbpower rigs, if hash rate it 350 or above it works for me if not they reject connection plus diffulty is absurd 200007

**Comment by isheirff** [comment]
also does anyone know how to check on what works are connected like the stacts of working connected to proxy

**Comment by PhatWheZ** [comment]
i dont understand your question?
Are you asking which pools are supported using xmrig-proxy?

**Comment by isheirff** [comment]
like what workers are connecting to proxy

**Comment by xmrig** [comment]
https://config.xmrig.com/ helps create config.json.
Thank you.
