### ISSUE TITLE
How can I log submitted shares from pool workers

### ISSUE THREAD

**Issue by cambazz** [xmrig/xmrig-proxy#78]
Hello,

How can I log submitted shares, and current hashrate from pool workers to a text file?

Best regards,
C.

**Comment by isheirff** [comment]
yea i am interested on this as well

**Comment by 4Reallive** [comment]
same

**Comment by xmrig** [comment]
Please provide more details what exactly you need.
Thank you.

**Comment by 4Reallive** [comment]
With multiple workers connected to the proxy. How would i be able to record effort contributed by the individual workers (i.e shares) with the goal of reporting on the workers with the most effort contributed and the least, i.e worker analytics.
Thanks for the reply i love your work and respect your craft.

**Comment by xmrig** [comment]
Per worker monitoring `GET /workers.json` from API or `w` key in console, it required some worker configuration (set different worker id as user). Individual per worker statistics without manual worker id configuration required to add non standard extensions in stratum protocol.
Thank you.
