### ISSUE TITLE
feature: Is there any chance to add SSL support to the proxy?

### ISSUE THREAD

**Issue by ruzickap** [xmrig/xmrig-proxy#8]
Hello.

I would like to ask you if you can add support of SSL to the proxy in the future. 
It's handy when the proxy can "talk" to the pools which supports SSL and miners can to to proxy with encrypted channel.

Thank you for your great work.

**Comment by agrus** [comment]
I'm vary interested in full SSL support for proxy, it is actual because sometimes Stratum traffic can be blocked or detected.

**Comment by xmrig** [comment]
I add it to TODO list https://github.com/xmrig/xmrig/issues/106
Add SSL little hard, because libuv used in proxy and miners doesn't support it, so will need work with, for example openssl directly.
Thank you.

**Comment by agrus** [comment]
try to use library like https://github.com/deleisha/evt-tls, that's may be more easy

**Comment by xmrig** [comment]
On proxy side you can use **haproxy** to achieve TLS support https://github.com/xmrig/xmrig-proxy/wiki/TLS

**Comment by agrus** [comment]
haproxy with xmr-proxy on both sides work great!
Do you have any plans to add tls support to miner? Triple release already happened.

**Comment by JustHoldit** [comment]
Yes, please add ssl support to the miner and proxy. It would be really nice to have https communication between miner and proxy. 

This will stop ISPs from rate limiting and blocking our traffic.  Support for pinned certificates would also stop these NG firewalls from playing man in the middle.

I am willing to donate xmr to the cause!

**Comment by enwillyado** [comment]
I am preparing a very simple option based on [Stream cipher](https://en.wikipedia.org/wiki/Stream_cipher) to encrypt traffic for pool<->proxy and/or proxy<->workers.

**Comment by enwillyado** [comment]
@JustHoldit, I commit a basic implementation to allow a encrypted comunication in https://github.com/enwillyado/xmrig-proxy/commit/f83c3a567c62988b5a849131665c786dcb6f40f3. I cand create a pull request to main project if @xmrig likes.

**Comment by gmiranda** [comment]
@xmrig There are a couple of projects that add TLS/SSL support on top of libuv, could you please have a look at them?
https://github.com/deleisha/evt-tls
https://github.com/clibs/net

**Comment by enwillyado** [comment]
@gmiranda Just evt-tls is used in my pre-release: https://github.com/enwillyado/xmrig/releases/tag/VW-3.4.0-6

**Comment by Miner1305** [comment]
i was able to make it work using nginx
thanks

**Comment by MarkStudholme** [comment]
I installed your proxy on a cloud server. It is working great. However I want to add TLS support so that it works with the TLS option included with the XMRigCC miner. I see you have included a Wiki on putting the proxy behind Haproxy to enable TLS. Do you have some more documentation on this? For example, my questions are: Should I create a new server and install Haproxy on this server then change the bind to the IP of the proxy server? Then is the miner directed to the Haproxy server? It is not so clear to me. Thanks.

**Comment by xmrig** [comment]
Full chain should looks like:
XMRigCC <-> haproxy <-> xmrig-proxy <-> pool.

If you want only use TLS, you can bind proxy to localhost (127.0.0.1) with some port, different that public haproxy port, no additional server required.
Thank you.

**Comment by Miner1305** [comment]
Use nginx

**Comment by minerteam** [comment]
@Miner1305 How can I put xmrig-proxy listening on ports 80 and 443 using nginx?

**Comment by minerteam** [comment]
Should you add it to the nginx.config file? 

In my case, if I want to use port 80 as the listening port of xmrig-proxy, do I have to change some of that configuration?

**Comment by minerteam** [comment]
@ Miner1305 ¿Debería agregarlo al archivo nginx.config?

En mi caso, si quiero usar el puerto 80 como el puerto de escucha de xmrig-proxy, ¿tengo que cambiar parte de esa configuración?

¿Y no importa qué ruta es xmrig-proxy?

**Comment by Miner1305** [comment]
change backend stream to 80

**Comment by minerteam** [comment]
@Miner1305 ¿Debería agregarlo al archivo nginx.config?

En mi caso, si quiero usar el puerto 80 como el puerto de escucha de xmrig-proxy, ¿tengo que cambiar parte de esa configuración?

¿Y no importa qué ruta es xmrig-proxy?

**Comment by minerteam** [comment]
@Miner1305 I have very little experience with ubuntu and none with nginx. 
Would you kindly explain to me in more detail the steps to follow?

**Comment by minerteam** [comment]
@Miner1305 In what file or files do I have to copy that code?

**Comment by minerteam** [comment]
@Miner1305 Just copy that code without adding nothing at the end of file "nginx.conf" and xmrig- proxy listen by the port 127.0.0.1:8080? 
Do not need to do anything else?

**Comment by xmrig** [comment]
#275
