### ISSUE TITLE
Mine to two different wallets with each assigned to a different bind port

### ISSUE THREAD

**Issue by azaryc2s** [xmrig/xmrig-proxy#81]
Hi!
I was wondering if it's possible to run one instance of this proxy and be able to mine to 2 different wallets depending on the port the workers connect to.
So let's say i have wallet1 for pool1 and wallet2 for pool2 and i have 4 mining rigs. Then i want to bind two ports to the proxy. The 3333 and 5555. I want all workers, that connect to the port 3333 to mine to wallet1 (against pool1) and the workers that connect to port 5555 to mine to wallet2 (against pool2).

Is this somehow possible or am i just better off running two instances of this proxy for each wallet/pool and bind those on different ports? I'd really like to avoid running 2 instances of the proxy

**Comment by isheirff** [comment]
its just easy if u fun two instances of the xmrig proxy have two folders  each with preferred port and wallet
