### ISSUE TITLE
Different difficulty settings for individual workers?

### ISSUE THREAD

**Issue by cranefist** [xmrig/xmrig-proxy#85]
Is there a way to set different difficulties for individual workers? LIke if i have one worked doing only 250h and one doing 1900h? Currently, the slow workers gets the same difficulty as the fast one, and can't submit any shares at all.

**Comment by huserbg** [comment]
You can use different fixed difficulty for each worker. In the wallet_address put WORKER_ID+DIFF and it will use that difficulty. All results lower than the pool difficulty will be ignored so you will not gain any shares, but this will help to keep the connection alive - for me it was timing out and was causing delays before reconnect.

**Comment by cranefist** [comment]
Thank you for this info.

Do i loose anything by setting the difficulty lower? How is it possible to find shares that the pool will accept is the difficulty is lower than the pools?

**Comment by marki555** [comment]
By setting miner diff lower, you are just increasing traffic between miner and proxy, but as mentioned it can prevents timeouts for slow miners.
Proxy will still send to the pool only shares which have diff larger than the pool's diff. The pool calculates your hashrate (and your earnings) based on how often you submit shares with diff X. It doesn't matter if you submit diff X share every 10 seconds, or if you submit diff X/10 shares every 1 second.

**Comment by kim0** [comment]
Thanks @huserbg .. To be clear, I would put WORKER_ID+DIFF in the wallet address of the individual miner to set the difficulty it gets, correct?

On a related note, the Comparison wiki page says xmrig-proxy is not able to "reduce worker diff" .. Can someone explain what this means? What diff are we talking about ?

**Comment by xmrig** [comment]
@kim0 first versions was't don't touch diff at all, just forgot update the table, anyway custom diff not to much useful feature.
