### ISSUE TITLE
Compile error in CentOS 7.4.1708

### ISSUE THREAD

**Issue by JustHoldit** [xmrig/xmrig-proxy#86]
[root@localhost build]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

[root@localhost build]# uname -a
Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost build]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 

-----------------------Error -----------------------------------

/usr/local/src/proxy/xmrig-proxy/build/xmrig-proxy/src/api/Httpd.cpp: In member function âbool Httpd::start()â:
/usr/local/src/proxy/xmrig-proxy/build/xmrig-proxy/src/api/Httpd.cpp:49:34: error: âMHD_FEATURE_EPOLLâ was not declared in this scope
     if (MHD_is_feature_supported(MHD_FEATURE_EPOLL)) {
                                  ^
/usr/local/src/proxy/xmrig-proxy/build/xmrig-proxy/src/api/Httpd.cpp:49:51: error: âMHD_is_feature_supportedâ was not declared in this scope
     if (MHD_is_feature_supported(MHD_FEATURE_EPOLL)) {
                                                   ^
make[2]: *** [CMakeFiles/xmrig-proxy.dir/src/api/Httpd.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig-proxy.dir/all] Error 2
make: *** [all] Error 2

**Comment by newkent** [comment]
@JustHoldit looks like the same issue which i've faced with when i've tried to build the v2.4.2
I suggest you to disable httpd.
add the -DWITH_HTTPD=OFF option and should be fine.

@xmrig 
the httpd code isn't fixed yet ? The api doesn't work without it :(

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-proxy/blob/master/src/api/Httpd.cpp#L49 libmicrohttpd too old and not support epoll, actually epoll support optional and API can work without it, but I was faced random connection issues on heavy loaded proxy.
Thank you.

**Comment by myxuchangbin** [comment]
Install the latest version of libmicrohttpd, this problem is indeed solved, thank you very much!
libmicrohttpd download address : https://ftp.gnu.org/gnu/libmicrohttpd/

**Comment by JustHoldit** [comment]
Thanks everyone. You are correct that did solve my issue.

Update libmicrohttpd
