### ISSUE TITLE
Failover pool question

### ISSUE THREAD

**Issue by DarrenRainey** [xmrig/xmrig-proxy#89]
Hello I was wondering how long does the proxy keep mining on the fail over pool?
Does it keep using the fail over pool until the main one is back online or until the fail over pool disconnects

**Comment by xmrig** [comment]
> keep using the fail over pool until the main one is back online

Exactly. Proxy/miner forever try reach main pool.
Thank you.

**Comment by DarrenRainey** [comment]
Ok thanks
