### ISSUE TITLE
server 2003 r2 x64 

### ISSUE THREAD

**Issue by madstas-ua** [xmrig/xmrig-proxy#90]
Hi!
Its me again )
Before 2.4.4 everything worked just fine. But in 2.4.4 i get error: 
the entry point to the convertinterfaceluidtoguid procedure was not found in the iphpapi.dll dll
Im running x32 version, x64 not start at all because #27

**Comment by xmrig** [comment]
I know about this issue, already reported https://github.com/xmrig/xmrig/issues/338
I will upload another x32 build with older libuv version later.
Thank you.

**Comment by madstas-ua** [comment]
Thank you!

**Comment by xmrig** [comment]
I rebuilt and replaced `xmrig-proxy-2.4.4-win32.zip` with older libuv version. 1.15.0 last version with Windows XP/2003 support.
Thank you.
