### ISSUE TITLE
Suggestion for the average hashrate calculation

### ISSUE THREAD

**Issue by huserbg** [xmrig/xmrig-proxy#92]
Hello,

Currently the average hashrate calculation is not useful after you restart the proxy until enough time has passed, because it assumes that the hashrate was 0 for the time with no data.
There are 2 options to improve this:

1. Use the time passed since start if it's lower than the period
2. Show N/A for the periods which are longer than the time passed since the start

I would prefer option 1 because the average hashrate can still be useful, even though it's only for part of the period. But the currently displayed value is not useful at all.

Regards!

**Comment by xmrig** [comment]
In upcoming release (dev branch) added hashrate report since restart, but only via API.
Thank you.
