### ISSUE TITLE
Monitor low hashrate miners

### ISSUE THREAD

**Issue by DeadManWalkingTO** [xmrig/xmrig-proxy#96]
To monitor low hashrate miners (lower than 0.1 kH/s) need increase decimal from 1 to 3.
It's important to monitor all miners (old pc, phones, arm devices etc) from proxy, not from pool.

Thank you.

**Comment by xmrig** [comment]
Proxy don't know real hashrate, it calculated using sent shares, exactly same it calculated on pool side, with high diff and slow miners, hashrate may highly inaccurate.
Thank you.

**Comment by DeadManWalkingTO** [comment]
It's useful for solo mining also. Any chance to add as option or something like that in the future?
Thank you.

**Comment by marki555** [comment]
Also it seems proxy calculates the hashrate only using `shares > pool_diff`. Would it be possible to calculate it using all shares submitted by the miner in case of customer diff on miner side? (`shares > proxy_cust_diff`). That way the hashrates calculated would be more stable.
