### ISSUE TITLE
too many invalid result.......

### ISSUE THREAD

**Issue by windrunner414** [xmrig/xmrig-proxy#99]
hi,i'm using this proxy and i have 1000+ miners.but i got many invalid shares,why?
`{
    "id": "84d50db5dc590dad",
    "worker_id": "172_21_0_6",
    "version": "2.4.4",
    "kind": "proxy",
    "ua": "xmrig-proxy/2.4.4 (Windows NT 6.1; Win64; x64) libuv/1.19.0 msvc/2017",
    "uptime": 38226,
    "donate_level": 0,
    "donated": 0.0,
    "hashrate": {
        "total": [
            31.7,
            9.31,
            62.45,
            36.27,
            18.13
        ]
    },
    "miners": {
        "now": 1064,
        "max": 1131
    },
    "upstreams": 6,
    "results": {
        "accepted": 21976,
        "rejected": 258,
        "invalid": 3411,
        "expired": 700,
        "avg_time": 1,
        "latency": 473,
        "hashes_total": 1566946324,
        "hashes_donate": 0,
        "best": [
            634935038,
            582299319,
            554783536,
            408221070,
            391856630,
            391112326,
            322674220,
            306036298,
            298724511,
            282723219
        ]
    }
}`
you can see it has 20% invalid results... why.... and i have another question.
if the pool diff is 100000 and i set the custom-diff is 1000.if the miner submit 10 times(10000 hashes),then it disconnect.the proxy will how to deal with the 10000 hashes?It's going to be wasted?

**Comment by xmrig** [comment]
Custom diff only useable to prevent timeouts for miners without keepalive support. What pool and miners do you use? probably on some of then not enabled nicehash.
Thank you.

**Comment by windrunner414** [comment]
@xmrig but if it not enabled nicehash.why i have many accepted results?and i change pool,now i use supportxmr.maybe too diffcult.i set diff fixed 4000 and it seems good.only 1% invalid.

**Comment by windrunner414** [comment]
@xmrig so if i use custom diff and the miner don't submit enough hashes ,and it disconnect.the hashes will be lost?i think i lost many hashes because the pool diff is 10000 but my hash rate only 60H/s.....and it only work 5 minutes in 30 minutes.what can i do?i try to fixed diff and the pool say i can fixed diff to add +2000 after wallet address but it don't useful.

**Comment by windrunner414** [comment]
no.....Inadvertently turn off

**Comment by Mila432** [comment]
so you have 1000+ miner and only 60h/s poor..

**Comment by windrunner414** [comment]
@Mila432 yes........

**Comment by windrunner414** [comment]
i change tht pool and i find many expired...why? socket timeout or ...?
the diff only 5000
